import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';

test('production React / DuckDB connected notebook journey',async({page,request})=>{
 const errors:string[]=[];const workers:string[]=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('worker',w=>workers.push(w.url()));
 const headers={Authorization:'Bearer core-pass-browser'};
 await page.goto('/#token=core-pass-browser');
 await page.getByRole('button',{name:/Retail revenue lakehouse/}).click();
 await expect(page.locator('.runtime-strip')).toContainText('duckdb');
 await expect(page.locator('.monaco-editor').first()).toBeVisible();
 await page.getByText('Canvas presets, notebook skins and source tools',{exact:true}).click();
 await page.getByText('Optional runtime profiles and capabilities',{exact:true}).click();
 const workspace=await page.getByLabel('Open workspace').inputValue();
 const doc=async()=>{const r=await request.get(`/api/workspaces/${workspace}`,{headers});expect(r.ok()).toBeTruthy();return r.json()};
 const idle=()=>expect(page.getByRole('button',{name:'Save',exact:true})).toBeEnabled();
 await page.getByRole('button',{name:'Run Load source orders into Bronze',exact:true}).click();await idle();
 expect((await doc()).runs.map((r:any)=>r.cell_id)).toEqual(['ingest']);
 await page.getByRole('button',{name:'Run notebook',exact:true}).click();await idle();
 let saved=await doc();expect(saved.runs.slice(-4).map((r:any)=>r.cell_id)).toEqual(['ingest','clean','aggregate','report']);
 expect(saved.runs.at(-1).result.rows).toEqual([{total_revenue:4985,valid_orders:10,customers:5}]);
 for(const label of ['Notebook','Two-page','Code + explanation','2 + 1','Dashboard','Free canvas','Practice']){
  await page.getByRole('tab',{name:label,exact:true}).click();
  await expect(page.locator('.notebook-block').first()).toBeVisible();
  await expect(page.getByRole('tab',{name:label,exact:true})).toHaveAttribute('aria-selected','true');
 }
 await page.locator('.react-resizable-handle-se').first().scrollIntoViewIfNeeded();
 const handle=await page.locator('.react-resizable-handle-se').first().boundingBox();expect(handle).not.toBeNull();
 await page.mouse.move(handle!.x+3,handle!.y+3);await page.mouse.down();await page.mouse.move(handle!.x+3,handle!.y+55,{steps:8});await page.mouse.up();
 await page.getByRole('button',{name:'Save',exact:true}).click();await idle();
 const before=(await doc()).notebook;
 expect(before.practiceLayouts.ingest).toBeDefined();
 await page.reload();await expect(page.locator('.monaco-editor').first()).toBeVisible();
 expect((await doc()).notebook.blockState).toEqual(before.blockState);
 expect((await doc()).notebook.practiceLayouts).toEqual(before.practiceLayouts);
 await page.getByRole('button',{name:'Workflow',exact:true}).click();
 await page.getByRole('button',{name:'Run workflow',exact:true}).click();await idle();
 expect((await doc()).runs.slice(-4).every((r:any)=>r.status==='success')).toBeTruthy();
 await page.getByRole('button',{name:'KPI preview',exact:true}).click();
 await expect(page.locator('.report-metrics')).toContainText('4,985');
 await page.screenshot({path:'qa/qualification/core-pass-1-react-retail.png',fullPage:true});
 await page.getByRole('button',{name:'Notebook',exact:true}).click();
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'.ipynb',exact:true}).click();
 const download=await downloadPromise;const filename=await download.path();const exported=JSON.parse(readFileSync(filename!,'utf8'));
 const code=exported.cells.filter((c:any)=>c.cell_type==='code');expect(code.map((c:any)=>c.id)).toEqual(['ingest','clean','aggregate','report']);
 const runCount=(await doc()).runs.length;
 await page.locator('.command-bar input[type=file]').setInputFiles({name:'roundtrip.ipynb',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});await idle();
 await expect(page.getByText(/Imported without execution/)).toBeVisible();
 saved=await doc();expect(saved.runs).toHaveLength(runCount);
 const roundtrip=saved.notebook.blocks.filter((b:any)=>b.notebook?.cellType==='code');
 expect(roundtrip.map((b:any)=>b.notebook.cellId)).toEqual(code.map((c:any)=>c.id));
 for(const b of roundtrip)expect(saved.notebook.blockState[`mosaic:v2:code:${b.id}`]).toBe(before.blockState[`mosaic:v2:code:${b.notebook.cellId}`]);
 await page.getByRole('button',{name:'Workflow',exact:true}).click();await page.getByRole('button',{name:'Run workflow',exact:true}).click();await idle();
 await page.getByRole('button',{name:'Notebook',exact:true}).click();
 await expect(page.locator('.result-view')).toHaveCount(4);
 await page.locator('.command-bar input[type=file]').setInputFiles({name:'broken.ipynb',mimeType:'application/json',buffer:Buffer.from('{bad')});await idle();
 await expect(page.getByText(/^SyntaxError:/)).toBeVisible();
 expect((await doc()).notebook.id).toBe(saved.notebook.id);
 await page.getByRole('button',{name:'Save',exact:true}).click();await idle();
 await page.setViewportSize({width:600,height:900});
 await page.getByLabel('Shared notebook layout').selectOption('practice');
 await page.screenshot({path:'qa/qualification/core-pass-1-react-narrow.png',fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 await page.getByRole('button',{name:'Workspace',exact:true}).click();
 await expect(page.getByLabel('Open workspace')).toBeVisible();
 await page.getByRole('button',{name:'Workspace',exact:true}).click();
 expect(workers.some(url=>url.includes('editor.worker'))).toBeTruthy();expect(errors).toEqual([]);
});

test('editing, keyboard execution, stale lineage, recovery and distinct run scopes',async({page,request})=>{
 await page.goto('/#token=core-pass-browser');
 await page.getByRole('button',{name:/Retail revenue lakehouse/}).click();
 await expect(page.locator('.monaco-editor').first()).toBeVisible();
 await page.getByText('Canvas presets, notebook skins and source tools',{exact:true}).click();
 await page.getByText('Optional runtime profiles and capabilities',{exact:true}).click();
 const id=await page.getByLabel('Open workspace').inputValue();
 const headers={Authorization:'Bearer core-pass-browser'};
 const doc=async()=>(await request.get(`/api/workspaces/${id}`,{headers})).json();
 const catalog=async()=>(await request.get(`/api/workspaces/${id}/catalog`,{headers})).json();
 const idle=()=>expect(page.getByRole('button',{name:'Save',exact:true})).toBeEnabled();
 await page.getByRole('button',{name:'Use plain editor',exact:true}).click();
 const source=page.getByRole('textbox',{name:'sql cell source',exact:true});
 await source.fill('SELECT missing_column FROM source.orders');
 await expect(page.getByLabel('Open workspace')).toBeDisabled();
 await source.press('Control+Enter');await idle();
 await expect(page.locator('.error-output')).toBeVisible();
 await source.fill('SELECT * FROM source.orders');
 await page.getByLabel('Cell kernel',{exact:true}).selectOption('python');
 await expect(page.getByRole('textbox',{name:'python cell source',exact:true})).toHaveValue('SELECT * FROM source.orders');
 await page.getByLabel('Cell kernel',{exact:true}).selectOption('sql');
 await source.press('Control+Enter');await idle();
 expect((await doc()).runs.at(-1).status).toBe('success');
 await page.getByRole('button',{name:'Run notebook',exact:true}).click();await idle();
 const kpi=(await doc()).runs.at(-1).result.rows;
 const profile=page.locator('#profile');const options=await profile.locator('option').evaluateAll(elements=>elements.map(e=>(e as HTMLOptionElement).value));
 await profile.selectOption(options.find(p=>p!=='generic_8x8')!);
 await page.getByRole('button',{name:'Run notebook',exact:true}).click();await idle();
 expect((await doc()).runs.at(-1).result.rows).toEqual(kpi);
 await page.getByRole('button',{name:'Cell',exact:true}).click();
 await page.getByRole('button',{name:'Use plain editor',exact:true}).click();
 await source.fill('SELECT * FROM source.orders');
 await page.getByLabel('Output asset',{exact:true}).fill('bronze.orders');
 await source.press('Control+Enter');await idle();
 expect((await catalog()).find((a:any)=>a.name==='gold.customer_revenue').fresh).toBe(false);
 await page.getByRole('button',{name:'Check case',exact:true}).click();await idle();
 await page.getByRole('button',{name:'Workflow',exact:true}).click();
 await page.getByRole('button',{name:'Run workflow',exact:true}).click();await idle();
 expect((await catalog()).find((a:any)=>a.name==='gold.customer_revenue').fresh).toBe(true);
 expect((await doc()).runs.slice(-4).map((r:any)=>r.cell_id)).toEqual(['ingest','clean','aggregate','report']);
 await page.getByRole('button',{name:'Run notebook',exact:true}).click();await idle();
 expect((await doc()).runs.at(-1).cell_id).toMatch(/^cell-/);
 expect((await catalog()).find((a:any)=>a.name==='gold.customer_revenue').fresh).toBe(false);
 await page.getByRole('button',{name:'Run workflow',exact:true}).click();await idle();
 await page.getByRole('button',{name:'Restart kernel',exact:true}).click();await idle();
 expect((await catalog()).find((a:any)=>a.name==='gold.customer_revenue').fresh).toBe(true);
 await page.getByRole('button',{name:'Save',exact:true}).focus();await page.keyboard.press('Tab');
 await expect(page.getByRole('button',{name:'Open',exact:true})).toBeFocused();
 await page.getByRole('button',{name:'Notebook',exact:true}).click();
 await page.getByLabel('Shared notebook layout').selectOption('notebook');
 await page.screenshot({path:'qa/qualification/core-pass-1-react-notebook.png',fullPage:true});
});


test('V1 playground launcher keeps free-canvas geometry and reopens the selected product shell',async({page,request})=>{
 const headers={Authorization:'Bearer core-pass-browser'};
 await page.goto('/#token=core-pass-browser');
 await page.getByRole('button',{name:/Free coding canvas/}).click();
 await expect(page.getByRole('tab',{name:'Free canvas',exact:true,includeHidden:true})).toHaveAttribute('aria-selected','true');
 await expect(page.locator('.notebook-block')).toHaveCount(5);
 const workspace=await page.getByLabel('Open workspace').inputValue();
 const doc=async()=>(await request.get(`/api/workspaces/${workspace}`,{headers})).json();
 expect((await doc()).title).toBe('Free coding canvas');
 expect((await doc()).notebook.playground).toBe('free');

 await page.getByText('Canvas presets, notebook skins and source tools',{exact:true}).click();
 await page.getByLabel('New cell kernel').selectOption('sql');
 await page.getByRole('button',{name:'Cell',exact:true}).click();
 await expect(page.getByRole('tab',{name:'Free canvas',exact:true,includeHidden:true})).toHaveAttribute('aria-selected','true');
 await page.getByRole('button',{name:'Save',exact:true}).click();
 await expect(page.getByText(/checkpoint/i)).toBeVisible();

 await page.getByRole('button',{name:'Data',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Tables',exact:true})).toBeVisible();
 await page.getByRole('button',{name:/source\.orders/}).click();
 await expect(page.getByRole('tab',{name:'Free canvas',exact:true,includeHidden:true})).toHaveAttribute('aria-selected','true');
 await page.getByRole('button',{name:'Save',exact:true}).click();

 await page.reload();
 await expect(page.getByRole('tab',{name:'Free canvas',exact:true,includeHidden:true})).toHaveAttribute('aria-selected','true');
 await expect(page.getByLabel('Open workspace')).toHaveValue(workspace);

 await page.getByLabel('Quick playground').selectOption('fabric');
 await expect(page.getByLabel('Workspace presentation')).toHaveValue('fabric');
 await expect(page.getByRole('tab',{name:'Notebook',exact:true,includeHidden:true})).toHaveAttribute('aria-selected','true');
 await page.getByRole('tab',{name:'Notebooks',exact:true}).click();
 await expect(page.locator('.dp-explorer')).toBeVisible();
 await expect(page.locator('.dp-explorer').getByText('sparklab',{exact:true})).toBeVisible();

 await page.getByRole('button',{name:'Save',exact:true}).click();
 await expect(page.getByLabel('Quick playground')).toBeEnabled();
 await page.getByLabel('Quick playground').selectOption('leetcode');
 await expect(page.locator('.interview-browser')).toBeVisible();
});
