/* Dependency-free HTTP diagnostic. Not a substitute implementation of the React shell. */
const $=id=>document.getElementById(id);const state={cases:[],workspace:null,case:null,step:null,codes:{},outputs:{},assets:[],runs:[],busy:false,area:'notebook'};
let token=new URLSearchParams(location.hash.slice(1)).get('token')||sessionStorage.getItem('datapass-local-token')||'';
if(token){sessionStorage.setItem('datapass-local-token',token);history.replaceState(null,'',location.pathname)}
const text=(tag,value,cls)=>{const n=document.createElement(tag);n.textContent=String(value??'');if(cls)n.className=cls;return n};
function message(value,isError=false){$('message').hidden=!value;$('message').textContent=value;$('message').className=isError?'error':''}
async function api(path,body,method){const response=await fetch('/api'+path,{method:method||(body?'POST':'GET'),headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));return data}
async function job(fn){if(state.busy)return;state.busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);$('code').readOnly=true;message('');try{await fn()}catch(e){message(e.message,true)}finally{state.busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);$('code').readOnly=false}}
function capture(){if(state.step){state.codes[state.step.id]=$('code').value;state.outputs[state.step.id]=$('output-asset').value||null}}
function selectStep(id){capture();state.step=state.case.steps.find(s=>s.id===id);const s=state.step;if(!s)return;state.area='notebook';showArea();$('persona').textContent=s.module.toUpperCase()+' / '+state.case.difficulty;$('title').textContent=s.title;$('language').textContent=s.language;$('cell-title').textContent=s.title;$('code').value=state.codes[s.id]??s.code;$('output-asset').value=state.outputs[s.id]===undefined?(s.output_asset||''):(state.outputs[s.id]||'');$('concept').textContent=s.concept;$('task').textContent=s.task;$('hint').textContent=s.hint||'Inspect the source and expected result.';$('solution').textContent=s.solution;renderSteps();renderResult([...state.runs].reverse().find(r=>r.cell_id===id))}
function renderSteps(){$('steps').replaceChildren();state.case.steps.forEach((s,i)=>{const b=text('button','');b.className=s.id===state.step?.id?'active':'';b.append(text('span',i+1));const d=text('div',s.title);d.append(text('small',s.module));b.append(d);b.onclick=()=>selectStep(s.id);$('steps').append(b)})}
function renderAssets(){$('assets').replaceChildren();state.assets.forEach(a=>{const d=text('div','', 'asset');d.append(text('span',a.layer,'layer'),text('span',a.name.split('.')[1]),text('b',a.row_count));d.title=a.fresh?'Fresh':'Stale';$('assets').append(d)});$('catalog').replaceChildren(text('h2','One shared catalog'));const grid=text('div','','dag-grid');for(const a of state.assets){const d=text('article','','dag-card');d.append(text('span',a.fresh?'FRESH':'STALE','pill'),text('h3',a.name),text('p',a.row_count+' physical rows'),text('p','Inputs: '+(Object.keys(a.inputs||{}).join(', ')||'source fixture')),text('p','Producer: '+(a.producer||'source')));grid.append(d)}$('catalog').append(grid)}
function table(result){const wrap=text('div','','table-wrap');const t=text('table','');const head=text('tr','');result.columns.forEach(c=>head.append(text('th',c)));const thead=text('thead','');thead.append(head);t.append(thead);const body=text('tbody','');result.rows.forEach(row=>{const tr=text('tr','');result.columns.forEach(c=>tr.append(text('td',typeof row[c]==='object'&&row[c]!==null?JSON.stringify(row[c]):row[c]===null?'NULL':row[c])));body.append(tr)});t.append(body);wrap.append(t);return wrap}
function renderResult(run){const root=$('result');root.replaceChildren();$('run-status').textContent=run?.status||'Not run';$('acceptance').textContent=run?.check?.message||'Checks inspect actual rows and input freshness, not just code keywords.';if(!run){root.append(text('p','Run the cell or its upstream workflow. No sample result is substituted.','muted'));return}const meta=text('div','','run-meta');meta.append(text('span',run.engine||'worker'),text('span',(run.elapsed_ms??0)+' ms local wall time'),text('span','Run '+(run.sequence??'-')),text('span',run.check?.passed?'ACCEPTANCE PASSED':run.check?.status||'No acceptance rule'));root.append(meta);if(run.error)root.append(text('pre',run.error.message));if(run.reason)root.append(text('p',run.reason));if(run.result)root.append(table(run.result));if(run.stdout)root.append(text('pre',run.stdout));if(run.compiled_sql){const detail=text('details','');detail.append(text('summary','Executed SQL'),text('pre',run.compiled_sql));root.append(detail)}if(run.simulation){const sim=run.simulation;root.append(text('div',sim.status==='modeled'?`SIMULATED: ${sim.virtual_fact_rows.toLocaleString()} virtual rows on ${sim.profile_id}. Actual input: ${sim.physical_fixture_rows} rows. Model duration: ${sim.metrics.total_duration_s.toFixed(2)} s. This is not a real cluster benchmark.`:sim.reason,'metric-line'))}if(run.input_versions&&Object.entries(run.input_versions).some(([name,v])=>!state.assets.some(a=>a.name===name&&a.version===v&&a.fresh)))root.prepend(text('p','Historical output: upstream data changed. Rerun to refresh.','metric-line'))}
function showArea(){document.querySelectorAll('[data-area]').forEach(b=>b.classList.toggle('active',b.dataset.area===state.area));['notebook','graph','catalog','history'].forEach(id=>$(id).hidden=id!==state.area);document.querySelector('.viewbar').hidden=state.area!=='notebook';if(state.area==='graph')renderGraph();if(state.area==='history')renderHistory()}
function renderGraph(){$('graph').replaceChildren(text('h2','Portable task graph'));$('graph').append(text('p','Actual dependencies are listed on each task. This is not the Airflow scheduler or Azure pipeline runtime.','muted'));const grid=text('div','','dag-grid');for(const s of state.case.steps){const d=text('article','','dag-card');const run=[...state.runs].reverse().find(r=>r.cell_id===s.id);d.append(text('span',run?.status||'not run','pill'),text('h3',s.title),text('p',s.module),text('p','Needs: '+(s.depends_on.join(', ')||'source fixture')),text('code',s.output_asset||'Result preview'));const b=text('button','Open step');b.onclick=()=>selectStep(s.id);d.append(document.createElement('br'),document.createElement('br'),b);grid.append(d)}$('graph').append(grid)}
function renderHistory(){$('history').replaceChildren(text('h2','Execution evidence'));for(const r of [...state.runs].reverse()){const d=text('article','','history-card');d.append(text('b',r.cell_id+' / '+r.status));if(r.result)d.append(table(r.result));if(r.error)d.append(text('pre',r.error.message));$('history').append(d)}}
async function workspaceList(){const list=await api('/workspaces');$('workspaces').replaceChildren(new Option('Select a workspace',''));list.forEach(w=>$('workspaces').add(new Option(w.title,w.id)));if(state.workspace)$('workspaces').value=state.workspace.id}
async function openWorkspace(id){const w=await api('/workspaces/'+id);const [assets,caps]=await Promise.all([api('/workspaces/'+id+'/catalog'),api('/workspaces/'+id+'/capabilities')]);state.workspace=w;state.case=state.cases.find(c=>c.id===w.case_id);state.step=null;state.codes={};state.outputs={};state.runs=w.runs;state.assets=assets;$('welcome').hidden=true;$('workspace').hidden=false;$('engine').textContent=caps.storage;$('truth').textContent=caps.storage==='sqlite'?'Compatibility mode; not DuckDB':caps.storage_truth;$('physical').textContent=state.case.physical_data;$('footer').textContent=caps.storage_truth;$('case-status').textContent='Not checked';renderAssets();selectStep(state.case.steps[0].id);await workspaceList()}
async function initialize(){if(!token){$('connect').hidden=false;return}const [cases,profiles]=await Promise.all([api('/cases'),api('/profiles')]);state.cases=cases;$('connect').hidden=true;$('cases').replaceChildren();cases.forEach(c=>$('cases').add(new Option(c.title,c.id)));$('profiles').replaceChildren();profiles.forEach(p=>$('profiles').add(new Option(p.name,p.id)));$('profiles').value='generic_8x8';$('case-grid').replaceChildren();cases.forEach(c=>{const b=text('button','','case-card');b.append(text('span',c.domain.toUpperCase(),'pill'),text('h2',c.title),text('p',c.subtitle),text('p',c.steps.length+' steps / '+c.physical_data));b.onclick=()=>job(async()=>{const w=await api('/workspaces',{case_id:c.id});await openWorkspace(w.id)});$('case-grid').append(b)});await workspaceList();$('engine').textContent='API connected'}
$('create').onclick=()=>job(async()=>{const w=await api('/workspaces',{case_id:$('cases').value});await openWorkspace(w.id)});
$('workspaces').onchange=e=>{if(e.target.value)job(()=>openWorkspace(e.target.value))};
$('run').onclick=()=>job(async()=>{if(!state.workspace||!state.step)return;capture();const s=state.step;const run=await api(`/workspaces/${state.workspace.id}/execute`,{notebook_id:'diagnostic',cell_id:s.id,step_id:s.id,language:s.language,code:state.codes[s.id],output_asset:state.outputs[s.id],profile:$('profiles').value,aqe:true});state.runs.push(run);if(run.catalog)state.assets=run.catalog;renderAssets();renderResult(run);message(run.status==='error'?run.error.message:'Cell executed against the shared catalog.',run.status==='error')});
$('workflow').onclick=()=>job(async()=>{if(!state.workspace)return;capture();const r=await api(`/workspaces/${state.workspace.id}/workflow`,{notebook_id:'diagnostic',overrides:state.codes,profile:$('profiles').value,aqe:true});state.runs.push(...r.runs);state.assets=r.catalog;renderAssets();selectStep(state.case.steps.at(-1).id);message('Workflow '+r.status+'. '+r.scheduler_truth,r.status!=='success')});
$('check').onclick=()=>job(async()=>{if(!state.workspace)return;const checks=await api(`/workspaces/${state.workspace.id}/check`,{},'POST');const passed=Object.values(checks).filter(c=>c.passed).length;$('case-status').textContent=passed+' / '+Object.keys(checks).length+' checks passed';message($('case-status').textContent);state.assets=await api(`/workspaces/${state.workspace.id}/catalog`);renderAssets()});
$('restart').onclick=()=>job(async()=>{if(!state.workspace)return;await api(`/workspaces/${state.workspace.id}/restart`,{},'POST');message('Kernel restarted. Tables persist. Python and Spark variables were cleared.')});
$('connect-button').onclick=()=>job(async()=>{token=$('token').value;sessionStorage.setItem('datapass-local-token',token);await initialize()});
$('code').addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();$('run').click()}if(e.key==='Tab'){e.preventDefault();const t=e.target,start=t.selectionStart,end=t.selectionEnd;t.value=t.value.slice(0,start)+'    '+t.value.slice(end);t.setSelectionRange(start+4,start+4)}});
document.querySelectorAll('[data-area]').forEach(b=>b.onclick=()=>{if(state.workspace){state.area=b.dataset.area;showArea()}});
document.querySelectorAll('[data-layout]').forEach(b=>b.onclick=()=>{$('notebook').className='layout-'+b.dataset.layout;document.querySelectorAll('[data-layout]').forEach(v=>v.classList.toggle('active',v===b))});
window.addEventListener('unhandledrejection',e=>message(e.reason?.message||String(e.reason),true));job(initialize);
