const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');
const {loadTs}=require('../scripts/analytics-m2-load-ts.cjs');
const root=path.resolve(__dirname,'../apps/web/src/studio/analytics');
const P=loadTs(path.join(root,'project.ts')),D=loadTs(path.join(root,'dbt.ts')),M=loadTs(path.join(root,'modeling.ts')),C=loadTs(path.join(root,'charts.ts')),V=loadTs(path.join(root,'validation.ts')),S=loadTs(path.join(root,'guidedSpark.ts'));
function manifest(){return {metadata:{dbt_schema_version:'https://schemas.getdbt.com/dbt/manifest/v12.json',project_name:'UNIT TEST FIXTURE - not a dbt build',invocation_id:'test-invocation',generated_at:'2026-09-21T00:00:00Z'},nodes:{'model.demo.stage':{unique_id:'model.demo.stage',name:'stage',resource_type:'model',original_file_path:'models/stage.sql',raw_code:'select 1',compiled_code:'select 1',depends_on:{nodes:['seed.demo.raw']},config:{materialized:'view'},columns:{id:{name:'id',data_type:'INTEGER'}}},'test.demo.key':{unique_id:'test.demo.key',name:'key',resource_type:'test',depends_on:{nodes:['model.demo.stage']}}},sources:{'seed.demo.raw':{unique_id:'seed.demo.raw',name:'raw',resource_type:'seed'}}};}
function results(invocation='test-invocation'){return {metadata:{dbt_schema_version:'https://schemas.getdbt.com/dbt/run-results/v6.json',invocation_id:invocation},results:[{unique_id:'model.demo.stage',status:'success',execution_time:0.12,failures:null,message:'Synthetic unit-test evidence, not a real run'}]};}
const enc=JSON.stringify;
test('new project survives validated JSON roundtrip without losing source/model/board rows',()=>{const p=P.newProject(),n=P.importProject(enc(p));assert.deepEqual(n.files,p.files);assert.deepEqual(n.model,p.model);assert.equal(enc(n.board.snapshot.rows),enc(p.board.snapshot.rows));assert.equal(n.board.query,p.board.query);});
test('namespaced analytics attachment does not require another notebook document',()=>{assert.equal(P.LAB_KEY,'datapass:analytics:v1');});
test('new tab reuses existing layer and does not mutate prior session',()=>{const s=P.defaultSession(),old=enc(s),next=P.openLayer(s,'charts');assert.equal(s.panes[0].tabs.length,2);assert.equal(enc(s),old);assert.equal(P.openLayer(next,'charts').panes[0].tabs.length,3);});
test('split opens an empty second pane, not a notebook clone',()=>{const s=P.splitSession(P.defaultSession(),'horizontal');assert.deepEqual(s.panes[1].tabs,[]);assert.equal(s.activePane,'b');assert.equal(P.validateSession(s).panes.length,2);});
test('moving tabs preserves identity; closing never deletes project source',()=>{const p=P.newProject(),s=P.splitSession(p.session,'vertical'),id=s.panes[0].tabs[0].id,next=P.moveTab(s,'a',id);assert.equal(next.panes[1].tabs[0].id,id);assert.equal(next.panes[0].tabs.length,1);assert.equal(p.files.length,9);});
test('single pane retains distinct tabs and active layer',()=>{let s=P.splitSession(P.defaultSession(),'horizontal');s=P.openLayer(s,'charts','b');const n=P.singlePaneSession(s);assert.equal(n.panes.length,1);assert.equal(n.panes[0].tabs.length,3);assert.equal(n.panes[0].tabs.find(t=>t.id===n.panes[0].active).layer,'charts');});
test('invalid pane ratio/active tab/collapse are rejected',()=>{for(const patch of [{ratio:NaN},{ratio:99},{activePane:'c'},{collapsed:'b'}])assert.throws(()=>P.validateSession({...P.defaultSession(),...patch}));const s=P.defaultSession();s.panes[0].active='missing';assert.throws(()=>P.validateSession(s));});
test('unsupported analytics schema and fractional revision are rejected',()=>{assert.throws(()=>P.importProject(enc({...P.newProject(),schemaVersion:2})));assert.throws(()=>P.validateProject({...P.newProject(),revision:.5}));});
test('invalid restored attachment reports error and leaves supplied object untouched',()=>{const broken={schemaVersion:99,source:'retain me'},before=enc(broken);assert.match(P.readProject(broken).error,/original value is retained/);assert.equal(enc(broken),before);});
test('edits to files are pure and enforce the source limit',()=>{const p=P.newProject(),n=P.updateFile(p,p.selectedFile,'select 42');assert.notEqual(p.files.find(f=>f.path===p.selectedFile).source,'select 42');assert.equal(n.files.find(f=>f.path===p.selectedFile).source,'select 42');assert.throws(()=>P.updateFile(p,p.selectedFile,'x'.repeat(100001)));});
for(const name of ['../secrets.sql','models/../../x.sql','models//x.sql','models/.x.sql','profiles.yml','models/CON.sql','models/a./x.sql','models\\a.sql','/models/a.sql'])test('reject unsafe source path '+name,()=>assert.throws(()=>V.sourcePath(name)));
test('prototype keys and deep/oversized JSON are rejected',()=>{assert.throws(()=>V.safeJson('{"__proto__":{"polluted":true}}'));assert.throws(()=>V.safeJson('['.repeat(42)+'0'+']'.repeat(42)));assert.throws(()=>V.safeJson('"'+'x'.repeat(21)+'"',20));});
test('parse manifest schema and native dependency identities',()=>{const b=D.importManifest(enc(manifest()));assert.equal(b.nodes.length,3);assert.equal(b.provenance,'imported-dbt-artifact');assert.equal(b.results.length,0);assert.equal(b.nodes.find(n=>n.name==='stage').compiled,'select 1');});
test('unsupported manifest schema fails closed',()=>{const m=manifest();m.metadata.dbt_schema_version='https://schemas.getdbt.com/dbt/manifest/v99.json';assert.throws(()=>D.importManifest(enc(m)),/not qualified/);});
test('node identity mismatch and duplicate dependencies are rejected',()=>{let m=manifest();m.nodes['model.demo.stage'].unique_id='other';assert.throws(()=>D.importManifest(enc(m)));m=manifest();m.nodes['model.demo.stage'].depends_on.nodes.push('seed.demo.raw');assert.throws(()=>D.importManifest(enc(m)));});
test('unresolved manifest dependencies are explicitly warned',()=>{const m=manifest();m.nodes['model.demo.stage'].depends_on.nodes=['missing'];assert.equal(D.importManifest(enc(m)).warnings.length,1);});
test('manifest graph excludes test nodes by default',()=>{const b=D.importManifest(enc(manifest()));assert.equal(D.manifestGraph(b).nodes.length,2);assert.equal(D.manifestGraph(b,true).nodes.length,3);});
test('run results require matching invocation; never attach stale results',()=>{const b=D.importManifest(enc(manifest()));assert.throws(()=>D.attachRunResults(b,enc(results('wrong'))),/same invocation/);assert.equal(b.results.length,0);assert.equal(D.attachRunResults(b,enc(results())).results[0].seconds,.12);});
test('run results reject orphan IDs, duplicate IDs and negative durations',()=>{const b=D.importManifest(enc(manifest()));let r=results();r.results[0].unique_id='other';assert.throws(()=>D.attachRunResults(b,enc(r)));r=results();r.results.push({...r.results[0]});assert.throws(()=>D.attachRunResults(b,enc(r)));r=results();r.results[0].execution_time=-1;assert.throws(()=>D.attachRunResults(b,enc(r)));});
test('imported run evidence roundtrips without becoming live evidence',()=>{const p=P.newProject();p.artifacts=D.attachRunResults(D.importManifest(enc(manifest())),enc(results()));const n=P.importProject(enc(p));assert.equal(n.artifacts.provenance,'imported-dbt-artifact');assert.equal(n.artifacts.results[0].status,'success');});
test('sample dbt graph derives five nodes and four references from source',()=>{const g=D.draftGraph(P.starterFiles());assert.equal(g.nodes.length,5);assert.equal(g.edges.length,4);assert.equal(g.origin,'draft-reference-scan');assert.equal(g.warnings.length,0);});
test('draft scanner does not count SQL or Jinja comments',()=>{const g=D.draftGraph([{path:'models/a.sql',source:"-- {{ ref('fake') }}\n/* {{ ref('bad') }} */\n{# {{ ref('bad2') }} #}\nselect 1"}]);assert.equal(g.edges.length,0);});
test('missing and dynamic ref warnings never claim successful compile',()=>{const g=D.draftGraph([{path:'models/a.sql',source:"select * from {{ ref('missing') }} join {{ ref(var('dynamic')) }} on true\n{% if something %} x {% endif %}"}]);assert.ok(g.warnings.length);assert.ok(g.nodes.some(n=>n.kind==='unresolved'));});
test('cycles are detected and layout is finite',()=>{const g=D.draftGraph([{path:'models/a.sql',source:"{{ ref('b') }}"},{path:'models/b.sql',source:"{{ ref('a') }}"}]);assert.equal(D.cyclicNodes(g).length,2);assert.ok(g.warnings.some(w=>w.includes('cycle')));assert.equal(D.graphLevels(g).size,2);});
test('upstream and downstream traversal preserves directed meaning',()=>{const g=D.draftGraph(P.starterFiles());assert.equal(D.relatedNodes(g,'models/marts/fct_sales.sql','upstream').size,5);assert.equal(D.relatedNodes(g,'models/marts/fct_sales.sql','downstream').size,1);});
test('schema checks flag nullable primary keys and type mismatches',()=>{const m=P.starterModel();m.tables[0].columns[0].nullable=true;m.tables[1].columns[1].type='VARCHAR';assert.ok(M.modelChecks(m).filter(c=>c.severity==='error').length>=2);});
test('relationship endpoints and duplicate edges are validated',()=>{const m=P.starterModel(),r={...m.relationships[0]};delete r.id;assert.throws(()=>M.addRelationship(m,r));assert.throws(()=>M.addRelationship(m,{...r,toColumn:'missing'}));});
test('removing table removes dangling relationships and column mappings',()=>{const m=M.removeTable(P.starterModel(),'customers');assert.equal(m.relationships.length,1);assert.equal(m.mappings.length,0);assert.equal(P.validateModel(m).tables.length,2);});
test('DDL generation quotes identifiers and is a design, not execution',()=>{const sql=M.ddlPreview(P.starterModel());assert.match(sql,/CREATE TABLE "fct_sales"/);assert.match(sql,/PRIMARY KEY/);assert.match(sql,/Not introspected/);const t=M.newTable('dim_product');t.name='x; drop table y';assert.throws(()=>M.ddlPreview({tables:[t],relationships:[],mappings:[]}));});
test('Type 1 retains two rows and latest cities',()=>{const r=M.replayScd(M.CHANGE_EVENTS,1);assert.equal(r.length,2);assert.equal(r.find(x=>x.customer_id===101).city,'Trondheim');});
test('Type 2 records four rows; unchanged event adds none',()=>{assert.equal(M.replayScd(M.CHANGE_EVENTS,2,3).length,3);assert.equal(M.replayScd(M.CHANGE_EVENTS,2,4).length,3);const r=M.replayScd(M.CHANGE_EVENTS,2);assert.equal(r.length,4);assert.equal(r.filter(x=>x.is_current).length,2);});
test('Type 2 as-of join is half-open and unique at change boundary',()=>{const r=M.replayScd(M.CHANGE_EVENTS,2);assert.equal(M.lookupAt(r,101,'2026-02-09').city,'Geneva');assert.equal(M.lookupAt(r,101,'2026-02-10').city,'Oslo');assert.equal(M.lookupAt(r,101,'2026-03-05').city,'Trondheim');assert.equal(M.lookupAt(r,101,'2025-12-01'),undefined);});
test('Type 3 retains only immediate previous city',()=>{const r=M.replayScd(M.CHANGE_EVENTS,3);assert.equal(r.length,2);assert.equal(r.find(x=>x.customer_id===101).previous_city,'Oslo');});
test('SCD replay leaves input unchanged and rejects impossible dates/order',()=>{const prior=enc(M.CHANGE_EVENTS);M.replayScd(M.CHANGE_EVENTS,2);assert.equal(enc(M.CHANGE_EVENTS),prior);assert.throws(()=>M.replayScd([{customerId:1,name:'A',city:'X',at:'2026-02-31'}],2));assert.throws(()=>M.replayScd([M.CHANGE_EVENTS[0],M.CHANGE_EVENTS[0]],2));});
test('SCD exercise answer is tied to displayed type and event index',()=>{assert.equal(M.scdExerciseAnswer(2,5).expected,'4');assert.equal(M.scdExerciseAnswer(3,5).expected,'2');assert.equal(M.scdExerciseAnswer(1,0).expected,'0');});
test('chart sample totals match the seed fixture',()=>{const d=C.aggregateBoard(C.sampleBoard());assert.equal(d.total,3855);assert.deepEqual(d.points.map(p=>p.value),[695,920,1090,1150]);assert.equal(d.stale,false);});
test('chart query edit marks evidence stale rather than generating new rows',()=>{const b=C.sampleBoard();b.query='select 99';const d=C.aggregateBoard(b);assert.equal(d.stale,true);assert.equal(d.total,3855);});
test('chart mean KPI is over rows, not an unweighted mean of group means',()=>{const b=C.sampleBoard();b.snapshot=C.importRows(enc([{a:'x',v:2},{a:'x',v:4},{a:'y',v:12}]),b.query);b.x='a';b.y='v';b.aggregation='mean';b.chartType='kpi';assert.equal(C.aggregateBoard(b).total,6);assert.match(C.boardYaml(b),/AVG\("v"\)/);assert.doesNotMatch(C.boardYaml(b),/AVG\(metric\)/);});
test('count includes rows with null measures and numeric zero is preserved',()=>{const b=C.sampleBoard();b.snapshot=C.importRows(enc([{a:'x',v:0},{a:'x',v:null}]),b.query);b.x='a';b.y='v';assert.equal(C.aggregateBoard(b).total,0);assert.equal(C.aggregateBoard(b).ignored,1);b.aggregation='count';assert.equal(C.aggregateBoard(b).total,2);});
test('chart imports reject nested cells, mismatched schemas and excess rows',()=>{assert.throws(()=>C.importRows('[{"a":{}}]',''));assert.throws(()=>C.importRows('[{"a":1},{"b":2}]',''));assert.throws(()=>C.importRows(enc(Array.from({length:2001},()=>({a:1}))),''));});
test('numeric overflow is rejected instead of rendering Infinity',()=>{const b=C.sampleBoard();b.snapshot=C.importRows('[{"x":"a","y":1e308},{"x":"a","y":1e308}]',b.query);b.x='x';b.y='y';assert.throws(()=>C.aggregateBoard(b),/overflow/);});
test('chart exports use dct board grammar with no execution claim',()=>{const y=C.boardYaml(C.sampleBoard());assert.match(y,/source: db/);assert.match(y,/queries:\n  analysis:/);assert.match(y,/rows:\n  - analysis_chart/);assert.match(y,/NOT the dbt Charts renderer/);});
test('guided Spark is explicit consent plus fixture-bound allowed operations',()=>{const c={source_table:'orders',operations:[{op:'filter',args:{condition:'net_amount > 0'}}],warnings:[]};assert.throws(()=>S.prepareLessonRequest(c,false),/consent/);const r=S.prepareLessonRequest(c,true);assert.equal(r.tables.length,1);assert.equal(r.tables[0].rows.length,3);assert.equal(r.collect_limit,100);assert.equal(r.runtime_id,'datapass-free');});
test('guided Spark rejects another dataset, unsupported operations and warnings',()=>{for(const c of [{source_table:'secret',operations:[]},{source_table:'orders',operations:[{op:'join',args:{}}]},{source_table:'orders',operations:[],warnings:['ignored action']}])assert.throws(()=>S.validateCompiledLesson(c));});

test('chart groups preserve typed scalar identities despite matching display labels',()=>{const b=C.sampleBoard();b.snapshot=C.importRows(enc([{a:null,v:1},{a:'(null)',v:2},{a:1,v:3},{a:'1',v:4}]),b.query);b.x='a';b.y='v';assert.equal(C.aggregateBoard(b).groups,4);assert.equal(C.aggregateBoard(b).total,10);});

test('root restore preserves only the bounded analytics namespace, including invalid schemas for recovery',()=>{const value={[P.LAB_KEY]:{schemaVersion:99,source:'keep me'},evil:42};const restored=P.preserveAnalyticsAttachment(value);assert.equal(enc(restored),enc({[P.LAB_KEY]:value[P.LAB_KEY]}));assert.deepEqual(P.preserveAnalyticsAttachment(null),{});assert.throws(()=>P.preserveAnalyticsAttachment({[P.LAB_KEY]:{text:'x'.repeat(1200000)}}));});

test('native chart freshness detects changed, missing, and stale registered inputs without claiming untracked lineage',()=>{
  const {snapshotFreshness}=loadTs(path.resolve('apps/web/src/studio/analytics/charts.ts'));
  const snapshot={origin:'real_local',input_versions:{'bronze.orders':'v1'}};
  assert.equal(snapshotFreshness(snapshot,[{name:'bronze.orders',version:'v1',fresh:true}]).state,'current');
  assert.equal(snapshotFreshness(snapshot,[{name:'bronze.orders',version:'v2',fresh:true}]).state,'stale');
  assert.equal(snapshotFreshness(snapshot,[{name:'bronze.orders',version:'v1',fresh:false}]).state,'stale');
  assert.equal(snapshotFreshness(snapshot,[]).state,'stale');
  assert.equal(snapshotFreshness({origin:'real_local',input_versions:{}},[]).state,'unknown');
  assert.equal(snapshotFreshness({origin:'imported'},[]).state,'unknown');
});

test('local chart project import preserves authenticated versions and empty result schema',()=>{
 const p=P.newProject();p.board.snapshot={label:'empty',origin:'real_local',columns:['id'],rows:[],query:'select id from bronze.t where 1=0',run_id:'a'.repeat(32),workspace_id:'b'.repeat(32),input_versions:{'bronze.t':'version-1'}};
 const imported=P.importProject(enc(p));assert.deepEqual(imported.board.snapshot,p.board.snapshot);
});

test('Windows dbt manifest paths map to canonical project files',()=>{const m=manifest();m.nodes['model.demo.stage'].original_file_path='models\\stage.sql';assert.equal(D.importManifest(enc(m)).nodes.find(n=>n.name==='stage').path,'models/stage.sql');});
