const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');
const {loadTs}=require('../scripts/analytics-m2-load-ts.cjs');
const S=loadTs(path.resolve('apps/web/src/studio/figures/semantics.ts'));
const W=loadTs(path.resolve('packages/contracts/src/workbench.ts'));
test('equality join preserves duplicates and does not match two NULL keys',()=>{const f=S.joinFixture;assert.equal(S.equalityJoin(f.left,f.right,'inner').length,2);const result=S.equalityJoin(f.left,f.right,'left');assert.equal(result.length,4);assert.equal(result.filter(r=>r.right_id===null).length,2);assert.ok(!result.some(r=>r.right_id==='R3'))});
test('empty input and duplicate left rows retain correct cardinality',()=>{const f=S.joinFixture;assert.deepEqual(S.equalityJoin([],f.right,'left'),[]);assert.equal(S.equalityJoin([f.left[0],{...f.left[0],id:'L4'}],f.right,'inner').length,4);assert.equal(S.equalityJoin(f.left,[],'left').length,3)});
test('partition fixture is deterministic, covers all row identities and exposes skew',()=>{const bins=S.partitionBuckets([1,1,1,1,2,3,4,5],3);assert.equal(bins[1].length,5);assert.deepEqual(bins.flat().sort((a,b)=>a-b),[0,1,2,3,4,5,6,7]);assert.throws(()=>S.partitionBuckets([1],0));assert.deepEqual(S.partitionBuckets([-1,2],3),[[],[],[0,1]])});
test('all frozen figure frames have stable unique IDs, truth and text without motion',()=>{for(const family of ['join','partitions','workflow','lineage']){const frames=S.figureFrames(family),again=S.figureFrames(family);assert.deepEqual(frames,again);for(const frame of frames){const ids=frame.lanes.flatMap(l=>l.objects.map(o=>o.id));assert.equal(new Set(ids).size,ids.length);assert.ok(frame.explanation&&frame.checkpoint&&frame.answer&&frame.truth)}}});
test('two figure panes preserve one canonical resource and independent playback cursors',()=>{let s=W.emptyWorkbench();s=W.addResource(s,{schema_version:1,kind:'figure',id:'figure1',title:'Join',revision:0,figure_version:1,family:'join',description:'Fixture'});s=W.openResource(s,'figure1');s=W.splitPane(s);const [a,b]=s.views,before=JSON.stringify(s.resources);s=W.patchView(s,a.id,{state:{figure_step:3,join_mode:'left'}});s=W.patchView(s,b.id,{state:{figure_step:1,join_mode:'inner'}});assert.equal(JSON.stringify(s.resources),before);assert.equal(s.views[0].state.figure_step,3);assert.equal(s.views[1].state.figure_step,1);});
