import { Button } from '@fluentui/react-components';

interface Props {
  label: string;
  language: string;
  value: string;
  onChange: (value: string) => void;
  readOnly?: boolean;
  footer?: string;
  dirty?: boolean;
  onReset?: () => void;
}

export function CodeEditor({label,language,value,onChange,readOnly=false,footer,dirty=false,onReset}:Props){
  const lines=value.split('\n').length;
  return <section className="code-panel">
    <div className="code-toolbar">
      <div><span className="code-mode">{readOnly?'GENERATED OUTPUT':'CODE PRACTICE'}</span><strong>{label}</strong>{dirty&&<span className="edited-badge">edited locally</span>}</div>
      <div className="code-actions">{onReset&&<Button size="small" appearance="subtle" onClick={onReset} disabled={!dirty}>Restore example</Button>}<span className="language-badge">{language}</span></div>
    </div>
    <div className="editor-shell">
      <div className="line-numbers" aria-hidden>{Array.from({length:lines},(_,index)=><span key={index}>{index+1}</span>)}</div>
      <textarea aria-label={label} spellCheck={false} value={value} readOnly={readOnly} onChange={(event)=>onChange(event.target.value)} />
    </div>
    <div className="editor-footer">{footer??(readOnly?'Generated by the bounded learning compiler.':'Saved locally. This editor does not execute arbitrary code.')}</div>
  </section>;
}
