import fs from 'node:fs';
const read=(p)=>fs.readFileSync(p,'utf8');
const pkg=JSON.parse(read('package.json'));
const app=read('src/App.tsx');
const dbx=read('src/components/DatabricksStudios.tsx');
const copy=read('src/components/FabricCopyJobStudio.tsx');
const dataflow=read('src/components/DataflowStudio.tsx');
const ops=read('src/lib/operationsRuntime.ts');
const results=[]; const check=(name,ok)=>results.push({name,ok:Boolean(ok)});
check('V19 package version declared', Number(pkg.version.split('.')[1]??0)>=19);
check('App wires shared workspace into Lakeflow Jobs', app.includes('<LakeflowJobsStudio caseStudy={caseStudy} workspace={workspace} onWorkspace={setWorkspace} />'));
check('Jobs workbench applies run data effects', dbx.includes('applyDatabricksJobRunToWorkspace(workspace,caseStudy,run)'));
check('Jobs workbench applies repair data effects', dbx.includes('applyDatabricksJobRunToWorkspace(workspace,caseStudy,repaired)'));
check('Jobs workbench restores durable history', dbx.includes('loadDatabricksJobRunsFromWorkspace(workspace)'));
check('Jobs workbench shows shared workspace evidence', dbx.includes('Shared workspace evidence')&&dbx.includes('Durable job evidence'));
check('Job runtime persists run history table', ops.includes("ops.databricks_job_runs"));
check('Job runtime persists task matrix table', ops.includes("ops.databricks_job_tasks"));
check('Repair applies only executed task effects', ops.includes("task.repairDisposition === 'Executed'"));
check('Run-history loader reconstructs repairs', ops.includes('loadDatabricksJobRunsFromWorkspace')&&ops.includes('repairedFrom'));
check('App wires shared workspace into Fabric Copy Job', app.includes('<FabricCopyJobStudio caseStudy={caseStudy} workspace={workspace} onWorkspace={setWorkspace} />'));
check('Fabric Copy Job commits ingest evidence', copy.includes("runFabricProductionStage(workspace, caseStudy, 'ingest')"));
check('App wires shared workspace into Dataflow Gen2', app.includes('<DataflowStudio caseStudy={caseStudy} workspace={workspace} onWorkspace={setWorkspace} />'));
check('Dataflow Gen2 publishes through executable runtime', dataflow.includes('runDataflowGen2Publish(workspace')); 
const failed=results.filter(r=>!r.ok); for(const r of results) console.log(`${r.ok?'PASS':'FAIL'}  ${r.name}`); console.log(`\n${results.length-failed.length}/${results.length} V19 durable Lakeflow Jobs static/depth QA checks passed.`); if(failed.length) process.exit(1);
