import fs from 'node:fs';
const read=(file)=>fs.readFileSync(file,'utf8');
const checks=[]; const check=(name,ok)=>checks.push({name,ok:Boolean(ok)});
const types=read('src/types/app.ts');
const insights=read('src/lib/workspaceInsights.ts');
const runtime=read('src/lib/dataRuntime.ts');
const lakehouse=read('src/components/FabricLakehouseStudio.tsx');
const app=read('src/App.tsx');
const storage=read('src/lib/storage.ts');
const tutorial=read('src/components/TutorialPanel.tsx');
const cases=read('src/data/caseStudies.ts');
const notebook=read('src/components/NotebookStudio.tsx');
const dbt=read('src/components/DbtStudio.tsx');
const airflowRuntime=read('src/lib/airflowRuntime.ts');
const airflow=read('src/components/AirflowStudio.tsx');
const shell=read('src/components/AppShell.tsx');
check('Workspace type records lineage',types.includes('WorkspaceLineageEdge')&&types.includes('lineage: WorkspaceLineageEdge[]'));
check('Workspace type records checkpoints',types.includes('WorkspaceCheckpoint')&&types.includes('checkpoints: WorkspaceCheckpoint[]'));
check('Case studies carry engineering decisions',types.includes('engineeringDecision?:')&&types.includes('productionScale'));
check('Workspace insights profiles data quality',insights.includes('profileWorkspaceTable')&&insights.includes('qualityScore')&&insights.includes('duplicatePrimaryKeyRows'));
check('Workspace insights compares seed to current state',insights.includes('compareWorkspaceToSeed')&&insights.includes("kind: 'created'"));
check('Workspace checkpoints can be created and restored',insights.includes('createWorkspaceCheckpoint')&&insights.includes('restoreWorkspaceCheckpoint'));
check('Lakehouse exposes Data quality tab',lakehouse.includes("'Data quality'")&&lakehouse.includes('Table profiles'));
check('Lakehouse exposes generated lineage/history',lakehouse.includes("'Lineage & history'")&&lakehouse.includes('Generated lineage')&&lakehouse.includes('<LearningGraph'));
check('Lakehouse exposes checkpoint controls',lakehouse.includes('Create checkpoint')&&lakehouse.includes('Restore'));
check('App passes mutable workspace into Lakehouse',app.includes('<FabricLakehouseStudio')&&app.includes('onWorkspace={setWorkspace}'));
check('Saved labs migrate lineage and checkpoints',storage.includes('normalizeWorkspace')&&storage.includes('lineage:')&&storage.includes('checkpoints:'));
check('Tutorial panel explains tool choice',tutorial.includes('Why these tools?')&&tutorial.includes('Preferred approach')&&tutorial.includes('Avoid'));
check('Tutorial panel exposes workspace evidence',tutorial.includes('workspace.snapshot')&&tutorial.includes('lineage')&&tutorial.includes('compareWorkspaceToSeed'));
check('All case studies explain when to avoid Spark',((cases.match(/avoid:/g)||[]).length>=3)&&cases.includes('Do not use Spark')&&cases.includes('do not force Spark'));
check('Retail case explicitly prefers simpler relational tools',cases.includes('SQL + dbt for relational modeling'));
check('Turbine case justifies Spark only at distributed scale',cases.includes('multi-TB historical telemetry')&&cases.includes('Spark is justified'));
check('ERP case focuses on state/idempotency/history',cases.includes('safe state, idempotency, dependency management and dimensional history'));
check('Learning Python supports rename',runtime.includes('.rename\\(columns')||runtime.includes('rename\\(columns'));
check('Learning Python supports fillna',runtime.includes('.fillna\\(')||runtime.includes('fillna\\('));
check('Learning Python supports merge',runtime.includes('.merge\\(')||runtime.includes('merge\\('));
check('Learning Python supports groupby aggregation',runtime.includes('.groupby\\(')||runtime.includes('groupby\\('));
check('Notebook help documents expanded pandas subset',notebook.includes('fillna')&&notebook.includes('merge')&&notebook.includes('groupby'));
check('Notebook shows PySpark equivalent only when production scale justifies Spark',notebook.includes('Production PySpark equivalent')&&notebook.includes('sparkIsJustified')&&notebook.includes('Distributed Spark compute is intentionally simulated'));
check('Writes emit runtime lineage',runtime.includes('WorkspaceLineageEdge')||runtime.includes('newEdges = sources.map'));
check('SQL lineage extracts source tables',runtime.includes('extractSqlSourceNames')&&runtime.includes('actor: context.actor'));
check('dbt models support source(), materialization and unique keys',runtime.includes("materialization: 'table' | 'view' | 'incremental'")&&runtime.includes('uniqueKey?: string')&&runtime.includes("source('"));
check('dbt UI exposes sources and materialization',dbt.includes('sources/')&&dbt.includes('Materialization')&&dbt.includes('Unique key'));
check('ERP Copy Job stages both order and customer changes',runtime.includes("for (const entity of ['sales_order', 'customer'])")&&runtime.includes('customer_incremental'));
check('ERP source model contains changed customer rows',cases.includes("schema: 'erp', name: 'customer'")&&cases.includes('Nordic Wind Group AS')&&cases.includes('Boreal Service GmbH'));
check('Stored procedure runtime performs retail MERGE',runtime.includes('MERGE fact table')&&runtime.includes('dw.fact_sales'));
check('Stored procedure runtime inserts turbine alerts',runtime.includes('Insert operational alert')&&runtime.includes('ops.maintenance_alerts'));
check('Stored procedure runtime performs ERP SCD2',runtime.includes('SCD Type 2 merge')&&runtime.includes('Advance watermarks'));
check('Airflow supports retries and trigger rules',airflowRuntime.includes("triggerRule: 'all_success' | 'all_done'")&&airflowRuntime.includes('retryDelaySeconds'));
check('Airflow runtime enforces all_success skip behavior',airflowRuntime.includes('upstream task did not succeed')&&airflowRuntime.includes("task.triggerRule !== 'all_done'"));
check('Airflow runtime executes retry attempts',airflowRuntime.includes('TRY ${attempt}/${maxAttempts}')&&airflowRuntime.includes('RETRY scheduled'));
check('Airflow workbench edits retry/recovery settings',airflow.includes('Retries')&&airflow.includes('Retry delay (seconds)')&&airflow.includes('Trigger rule')&&airflow.includes('Simulate task failure'));
check('Power BI remains deferred',shell.includes('Power BI · next pass'));
const failed=checks.filter(c=>!c.ok); for(const c of checks) console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}`);
console.log(`\n${checks.length-failed.length}/${checks.length} V10 static/depth QA checks passed.`); if(failed.length) process.exit(1);
