import fs from 'node:fs';
const read=(file)=>fs.readFileSync(file,'utf8');
const checks=[]; const check=(name,ok)=>checks.push({name,ok:Boolean(ok)});
const types=read('src/types/app.ts');
const app=read('src/App.tsx');
const storage=read('src/lib/storage.ts');
const runtime=read('src/lib/dataRuntime.ts');
const notebook=read('src/components/NotebookStudio.tsx');
const explorer=read('src/components/DataExplorer.tsx');
const sql=read('src/components/SqlStudio.tsx');
const dbt=read('src/components/DbtStudio.tsx');
const shell=read('src/components/AppShell.tsx');
const pipelineStudio=read('src/components/PipelineStudio.tsx');
const pipeline=read('src/lib/pipeline.ts');
const cases=read('src/data/caseStudies.ts');
check('Shared DataWorkspace type exists',types.includes('export interface DataWorkspace')&&types.includes('WorkspaceTable'));
check('NotebookDocument type exists',types.includes('export interface NotebookDocument'));
check('Workspace and notebook persist with lab state',storage.includes('workspace?: DataWorkspace')&&storage.includes('notebook?: NotebookDocument'));
check('App hydrates shared workspace and notebook',app.includes('seedWorkspace(caseStudy)')&&app.includes('seedNotebook(caseStudy)'));
check('Fabric notebook executes real learning cells',notebook.includes('executeNotebookCell')&&notebook.includes('executeNotebook(workspace, notebook)'));
check('Notebook supports adding Python SQL Markdown cells',notebook.includes("addCell('python')")&&notebook.includes("addCell('sql')")&&notebook.includes("addCell('markdown')"));
check('Notebook shows live Lakehouse explorer',notebook.includes('Lakehouse · live')&&notebook.includes('workspace.history'));
check('Data Explorer runs local SQL against shared workspace',explorer.includes('executeWorkspaceSql(workspace, query)'));
check('SQL Studio runs against shared workspace',sql.includes('executeWorkspaceSql(workspace, sql)'));
check('Pipeline executes learning data activities',pipelineStudio.includes('executePipelineLearningData')&&pipelineStudio.includes('onWorkspace(dataExecution.workspace)'));
check('Runtime handles Copy and Notebook pipeline activities',runtime.includes("node.type === 'copy'")&&runtime.includes("node.type === 'notebook'"));
check('Runtime handles Copy Job and Dataflow learning mutations',runtime.includes("node.type === 'copyJob'")&&runtime.includes("node.type === 'dataflow'"));
check('dbt workbench exists',dbt.includes('dbt Job learning workbench')&&dbt.includes('compileDbtModel'));
check('Fabric navigation exposes dbt Job',shell.includes("{ key: 'dbt', label: 'dbt Job' }"));
check('Pipeline palette includes dbt activity',pipeline.includes("dbt: 'dbt Job'")&&pipeline.includes("'copy', 'copyJob', 'dataflow', 'dbt'"));
check('dbt pipeline execution is wired',runtime.includes("node.type === 'dbt'")&&runtime.includes('runDbtBuild'));
check('dbt ref dependency compiler exists',runtime.includes('compileDbtModel')&&runtime.includes('dbtDependencies'));
check('dbt basic data tests exist',runtime.includes("type: 'not_null'")&&runtime.includes("type: 'unique'"));
check('ERP case study now teaches dbt build',cases.includes("validateKey: 'erp-dbt'")&&cases.includes("type: 'dbt'"));
check('Local backend is described honestly',app.includes("'Local workspace'")&&!app.includes("'Mock DuckLake'"));
check('MotherDuck remains optional',read('src/components/DataEngineDialog.tsx').includes('MotherDuck WASM'));
check('Power BI remains deferred',shell.includes('Power BI · next pass'));
const failed=checks.filter(c=>!c.ok); for(const c of checks) console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}`);
console.log(`\n${checks.length-failed.length}/${checks.length} V8 static/depth QA checks passed.`); if(failed.length) process.exit(1);
