import fs from 'node:fs';
const read=(file)=>fs.readFileSync(file,'utf8');
const checks=[]; const check=(name,ok)=>checks.push({name,ok:Boolean(ok)});
const props=read('src/components/PropertiesPanel.tsx');
const mapping=read('src/components/CopyMappingEditor.tsx');
const nested=read('src/components/NestedActivityEditor.tsx');
const nestedLib=read('src/lib/nestedActivities.ts');
const copyLib=read('src/lib/copyMapping.ts');
const expr=read('src/components/ExpressionBuilder.tsx');
const monitor=read('src/components/MonitorView.tsx');
const pipeline=read('src/lib/pipeline.ts');
check('Structured nested activity helper exists',nestedLib.includes('parseNestedActivities')&&nestedLib.includes('serializeNestedActivities'));
check('Legacy nested strings remain supported',nestedLib.includes('fromLegacy'));
check('Nested editor uses shared LearningGraph',nested.includes('<LearningGraph'));
check('Nested editor exposes pipeline breadcrumb',nested.includes('nested-breadcrumb')&&nested.includes('Pipeline'));
check('Nested child positions are persisted',nested.includes('onMove={move}')&&nestedLib.includes('x: Math.round(item.x)'));
check('ForEach drill-down editor is wired',props.includes("setNestedTarget({ key: 'innerActivities'"));
check('Mini nested preview uses structured parser',props.includes('parseNestedActivities(value)')&&props.includes('serializeNestedActivities'));
check('Mini nested add preserves structured format',props.includes('nestedActivityChoices')&&!props.includes("split('|')"));
check('If true and false drill-down editors are wired',props.includes("key: 'trueActivities'")&&props.includes("key: 'falseActivities'"));
check('Copy mapping editor is wired',props.includes('<CopyMappingEditor'));
check('Copy mapping supports Import schemas',mapping.includes('Import schemas'));
check('Copy mapping supports New mapping Clear Reset',mapping.includes('+ New mapping')&&mapping.includes('Clear')&&mapping.includes('Reset'));
check('Copy mapping exposes source/destination types',mapping.includes('sourceType')&&mapping.includes('destinationType'));
check('Mock schema inference covers learning datasets',copyLib.includes("text.includes('sales')")&&copyLib.includes("text.includes('turbine')")&&copyLib.includes("text.includes('customer')"));
check('Copy metrics report mapping behavior',pipeline.includes('mappedColumns')&&pipeline.includes('autoMap'));
check('Expression builder groups dynamic content',expr.includes('Pipeline parameters')&&expr.includes('Activity outputs')&&expr.includes('Iteration & trigger'));
check('Expression builder supports search',expr.includes('Search parameters, outputs, functions'));
check('Expression builder exposes runtime context summary',expr.includes('Runtime context'));
check('Monitor has Trigger history view',monitor.includes('Trigger history')&&monitor.includes('triggerGroups'));
check('Trigger history excludes Debug runs',monitor.includes("run.trigger !== 'Debug'"));
check('Trigger history reports success/failure counts',monitor.includes('succeeded:')&&monitor.includes('failed:'));
const failed=checks.filter((c)=>!c.ok); for(const c of checks) console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}`);
console.log(`\n${checks.length-failed.length}/${checks.length} V7 static/depth QA checks passed.`); if(failed.length) process.exit(1);
