import fs from 'node:fs';
const read=(p)=>fs.readFileSync(p,'utf8');
const pkg=JSON.parse(read('package.json'));
const types=read('src/types/app.ts');
const app=read('src/App.tsx');
const shell=read('src/components/AppShell.tsx');
const icons=read('src/components/Icons.tsx');
const studio=read('src/components/CaseStudyStudio.tsx');
const cases=read('src/data/caseStudies.ts');
const evidence=read('src/lib/caseStudyEvidence.ts');
const hub=read('src/components/FabricHub.tsx');
const dbx=read('src/components/DatabricksStudios.tsx');
const css=read('src/styles.css');
const results=[]; const check=(name,ok)=>results.push({name,ok:Boolean(ok)});
check('V20 package version declared',Number(pkg.version.split('.')[1])>=20);
check('Case-study page key added',types.includes("| 'case-study'"));
check('Case-study brief model exists',types.includes('export interface CaseStudyBrief'));
check('Source-system contract exists',types.includes('export interface CaseStudySourceSystem'));
check('Acceptance-criterion contract exists',types.includes('export interface CaseStudyAcceptanceCriterion'));
check('Case study route wired in App',app.includes("case 'case-study'"));
check('Fabric navigation exposes case brief',shell.includes("{ key: 'case-study', label: 'Case study brief' }"));
check('Databricks navigation exposes case brief',(shell.match(/key: 'case-study'/g)||[]).length>=2);
check('Case-study icon is registered',icons.includes("'case-study': 'CS'"));
check('CaseStudyStudio renders business brief',studio.includes('Business brief')&&studio.includes('Problem, people, outcome'));
check('CaseStudyStudio renders requirements',studio.includes('Non-functional requirements')&&studio.includes('Data contracts'));
check('CaseStudyStudio compares Fabric and Databricks',studio.includes('Microsoft Fabric')&&studio.includes('Azure Databricks'));
check('CaseStudyStudio renders live acceptance',studio.includes('Acceptance criteria backed by live evidence'));
check('CaseStudyStudio renders incident lifecycle',studio.includes('Operational incident')&&studio.includes('Root cause')&&studio.includes('Prevention'));
check('Acceptance engine excludes case-study seed',evidence.includes("runtimeSource !== 'Case-study seed'"));
check('Acceptance engine evaluates lineage',evidence.includes("evidence.kind === 'lineage'"));
check('Acceptance engine evaluates non-baseline checkpoints',evidence.includes("item.id !== 'baseline'"));
check('All three cases define detailed briefs',(cases.match(/brief: \{/g)||[]).length===3);
check('All three briefs define source estates',(cases.match(/sourceSystems: \[/g)||[]).length===3);
check('All three briefs define service levels',(cases.match(/serviceLevels: \{/g)||[]).length===3);
check('All three briefs define data contracts',(cases.match(/dataContracts: \[/g)||[]).length===3);
check('All three briefs define acceptance criteria',(cases.match(/acceptanceCriteria: \[/g)||[]).length===3);
check('All three briefs define operational incidents',(cases.match(/incident: \{/g)||[]).length===3);
check('Fabric hub opens case-study brief',hub.includes("onNavigate('case-study')"));
check('Databricks hub opens case-study brief',dbx.includes("onNavigate('case-study')"));
check('Case-study semantic CSS tokens are defined',css.includes('--surface: #ffffff')&&css.includes('--brand-soft:')&&css.includes('--success-soft:'));
const failed=results.filter(r=>!r.ok); for(const r of results) console.log(`${r.ok?'PASS':'FAIL'}  ${r.name}`); console.log(`\n${results.length-failed.length}/${results.length} V20 case-study static/depth QA checks passed.`); if(failed.length) process.exit(1);
