import fs from 'node:fs';
const read=(file)=>fs.readFileSync(file,'utf8');
const checks=[]; const check=(name,ok)=>checks.push({name,ok:Boolean(ok)});
const types=read('src/types/app.ts');
const app=read('src/App.tsx');
const shell=read('src/components/AppShell.tsx');
const hub=read('src/components/FabricHub.tsx');
const curriculum=read('src/data/curriculum.ts');
const airflow=read('src/components/AirflowStudio.tsx');
const airflowRuntime=read('src/lib/airflowRuntime.ts');
const choice=read('src/components/ToolChoiceStudio.tsx');
const dbt=read('src/components/DbtStudio.tsx');
const properties=read('src/components/PropertiesPanel.tsx');
const pipeline=read('src/lib/pipeline.ts');
const dataRuntime=read('src/lib/dataRuntime.ts');
const spark=read('src/components/FabricRuntimeStudio.tsx');
check('Airflow and tool-choice routes exist',types.includes("| 'airflow'")&&types.includes("| 'toolchoice'"));
check('App routes Airflow workbench',app.includes("case 'airflow'")&&app.includes('<AirflowStudio'));
check('App routes engineering decision lab',app.includes("case 'toolchoice'")&&app.includes('<ToolChoiceStudio'));
check('Fabric navigation exposes Airflow',shell.includes("label: 'Apache Airflow Job'"));
check('Fabric navigation exposes decision lab',shell.includes("label: 'Engineering decision lab'"));
check('Fabric curriculum includes Airflow module',curriculum.includes("id: 'fabric-airflow'")&&curriculum.includes('FabricRunItemOperator'));
check('Fabric curriculum includes tool-choice module',curriculum.includes("id: 'fabric-tool-choice'"));
check('Fabric curriculum includes dbt module',curriculum.includes("id: 'fabric-dbt'"));
check('Hub maps Airflow module to workbench',hub.includes("'fabric-airflow': 'airflow'"));
check('Hub uses dynamic module count',hub.includes('{fabricModules.length} learning workbenches'));
check('Decision lab compares transformation and orchestration tools',choice.includes('SQL, dbt, Python, Spark, Pipeline or Airflow')&&choice.includes('Do not use distributed compute'));
check('Decision lab includes explicit no-Spark reasoning',choice.includes('Starting Spark only because')&&choice.includes('One-off aggregation'));
check('Airflow workbench has graph and Python code',airflow.includes('DAG graph')&&airflow.includes('DAG Python'));
check('Airflow workbench can apply code back to graph',airflow.includes('parseAirflowDagCode')&&airflow.includes('Apply code → graph'));
check('Airflow runtime validates DAG cycles',airflowRuntime.includes('Airflow DAG contains a cycle'));
check('Airflow runtime invokes notebook',airflowRuntime.includes('executeNotebook(workspace, notebook)'));
check('Airflow runtime invokes dbt',airflowRuntime.includes("command: 'dbt build'"));
check('Airflow runtime invokes authored pipeline state',airflowRuntime.includes('executePipelineLearningData(workspace, notebook, input.pipelineNodes'));
check('Airflow Spark task is explicitly simulated',airflowRuntime.includes('Simulated Spark semantics on representative rows'));
check('dbt workbench exposes build/run/compile/test',dbt.includes('<option>dbt build</option>')&&dbt.includes('<option>dbt test</option>'));
check('dbt workbench exposes select/exclude/full refresh/fail fast/threads',dbt.includes('setSelect')&&dbt.includes('setExclude')&&dbt.includes('Full refresh')&&dbt.includes('Fail fast')&&dbt.includes('Threads'));
check('Pipeline dbt activity exposes advanced settings',properties.includes('dbtSettings')&&properties.includes('dbt Select')&&properties.includes('Full refresh'));
check('Pipeline dbt validation checks command and threads',pipeline.includes('unsupported dbt command')&&pipeline.includes('dbt threads must be between 1 and 64'));
check('Pipeline dbt runtime uses command semantics',dataRuntime.includes('runDbtCommand(nextWorkspace, project'));
check('dbt command runner supports selection',dataRuntime.includes('selectDbtModels')&&dataRuntime.includes('dbt compile')&&dataRuntime.includes('dbt test'));
check('Spark workbench teaches when not to use Spark',spark.includes('not by default')&&spark.includes('Prefer SQL/dbt'));
check('Power BI remains deferred',shell.includes('Power BI · next pass'));
const failed=checks.filter(c=>!c.ok); for(const c of checks) console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}`);
console.log(`\n${checks.length-failed.length}/${checks.length} V9 static/depth QA checks passed.`); if(failed.length) process.exit(1);
