import fs from 'node:fs';
const read = (file) => fs.readFileSync(file, 'utf8');
const checks = [];
const check = (name, ok) => checks.push({ name, ok: Boolean(ok) });
const types = read('src/types/app.ts');
const app = read('src/App.tsx');
const shell = read('src/components/AppShell.tsx');
const hub = read('src/components/FabricHub.tsx');
const curriculum = read('src/data/curriculum.ts');
const recovery = read('src/components/RecoveryStudio.tsx');
const reliability = read('src/lib/reliability.ts');
const pipelineStudio = read('src/components/PipelineStudio.tsx');
const monitor = read('src/components/MonitorView.tsx');
const tutorial = read('src/components/TutorialPanel.tsx');
const dbt = read('src/components/DbtStudio.tsx');
const runtime = read('src/lib/dataRuntime.ts');
const pipeline = read('src/lib/pipeline.ts');
const styles = read('src/styles.css');

check('Recovery route is typed', types.includes("| 'recovery'"));
check('App routes Reliability & recovery workbench', app.includes("case 'recovery'") && app.includes('<RecoveryStudio'));
check('Fabric rail exposes recovery workbench', shell.includes("key: 'recovery'") && shell.includes('Reliability / recovery'));
check('Fabric hub maps recovery module', hub.includes("'fabric-recovery': 'recovery'") && hub.includes('Reliability & recovery'));
check('Fabric curriculum includes recovery engineering', curriculum.includes("id: 'fabric-recovery'") && curriculum.includes('Failure containment') && curriculum.includes('Idempotent rerun'));
check('Recovery lab injects incidents', recovery.includes('Inject incident') && recovery.includes('injectReliabilityIncident'));
check('Recovery lab shows quality rules', recovery.includes('Data contract / quality checks') && recovery.includes('assessment.rules'));
check('Recovery lab supports checkpoints', recovery.includes('Create checkpoint') && recovery.includes('Restore checkpoint'));
check('Recovery lab runs dbt evidence', recovery.includes('Run dbt build/tests') && recovery.includes('runReliabilityDbt'));
check('Recovery lab teaches wrong-tool reasoning', recovery.includes('Wrong instinct') && recovery.includes('Why not?'));
check('Recovery lab exposes proof state', recovery.includes('Recovery evidence is clean') && recovery.includes('PROVEN'));
check('Recovery lab counts quarantined rows', recovery.includes('Quarantined rows') && recovery.includes("table.schema === 'quarantine'"));
check('Recovery postmortem closes detection-to-prevention loop', recovery.includes('Incident postmortem') && recovery.includes("step: 'Detection'") && recovery.includes("step: 'Prevention'") && styles.includes('.postmortem-steps'));
check('Reliability module defines all three incidents', reliability.includes("'retail-medallion'") && reliability.includes("'turbine-realtime'") && reliability.includes("'erp-incremental'"));
check('Retail reliability checks duplicates and invalid quantity', reliability.includes('retail-unique-sale') && reliability.includes('retail-positive-qty'));
check('Turbine reliability checks replay and contract drift', reliability.includes('turbine-unique-event') && reliability.includes('turbine-temperature'));
check('ERP reliability checks watermark and SCD state', reliability.includes('erp-watermark') && reliability.includes('erp-current-scd'));
check('Targeted repair writes quarantine tables', reliability.includes('quarantine.sales_rejected') && reliability.includes('quarantine.turbine_events_rejected') && reliability.includes('quarantine.customer_changes_rejected'));
check('Incident injection auto-creates pre-incident checkpoint', reliability.includes('Pre-incident safe point') && reliability.includes('createWorkspaceCheckpoint'));
check('Pipeline Debug auto-checkpoints data state', pipelineStudio.includes('createWorkspaceCheckpoint(workspace, `Before ${trigger} run`)'));
check('Failed pipeline can restore pre-run data', pipelineStudio.includes('Restore pre-run data') && pipelineStudio.includes('restoreWorkspaceCheckpoint'));
check('Pipeline learning runtime returns effective statuses', runtime.includes('statusByNode: effectiveStatus') && runtime.includes('runtimeErrors'));
check('Runtime dbt test errors fail activity', runtime.includes('dbt quality gate failed') && runtime.includes("effectiveStatus.set(node.id, 'Failed')"));
check('Runtime dependency conditions can skip downstream', runtime.includes('runtime dependency condition was not satisfied') && runtime.includes("effectiveStatus.set(node.id, 'Skipped')"));
check('Pipeline run records runtime root cause', pipeline.includes('LearningDataRuntimeError') && pipeline.includes('runtimeErrors'));
check('Monitor exposes failure analysis', monitor.includes('Failure analysis') && monitor.includes('Downstream skipped'));
check('Monitor links failure to recovery lab', monitor.includes("onNavigate('recovery')") && monitor.includes('Open recovery lab'));
check('Tutorial ends with failure/recovery drill CTA', tutorial.includes('Run failure & recovery drill') && tutorial.includes('onRecovery'));
check('dbt workbench exposes promotion gate', dbt.includes('Promotion gate') && dbt.includes('BLOCKED') && dbt.includes('READY'));
check('V11 recovery styling is present', styles.includes('.recovery-studio') && styles.includes('.monitor-failure-insight') && styles.includes('.dbt-promotion-gate'));
check('Power BI remains deferred', shell.includes('Power BI · next pass'));

const failed = checks.filter((c) => !c.ok);
for (const c of checks) console.log(`${c.ok ? 'PASS' : 'FAIL'}  ${c.name}`);
console.log(`\n${checks.length - failed.length}/${checks.length} V11 static/depth QA checks passed.`);
if (failed.length) process.exit(1);
