import fs from 'node:fs';
const read = (p) => fs.readFileSync(p, 'utf8');
const app = read('src/App.tsx');
const types = read('src/types/app.ts');
const shell = read('src/components/AppShell.tsx');
const hub = read('src/components/FabricHub.tsx');
const curriculum = read('src/data/curriculum.ts');
const studio = read('src/components/PracticeStudio.tsx');
const engine = read('src/lib/practiceEngine.ts');
const styles = read('src/styles.css');
const pkg = JSON.parse(read('package.json'));
const results=[]; const check=(name,ok)=>results.push({name,ok:Boolean(ok)});
check('V13 package version declared', Number(pkg.version.split('.')[1] ?? 0) >= 13);
check('Practice route is typed', types.includes("| 'practice'"));
check('App routes PracticeStudio', app.includes("case 'practice'") && app.includes('<PracticeStudio'));
check('Fabric navigation exposes Hands-on practice', shell.includes("key: 'practice'") && shell.includes('Hands-on practice'));
check('Fabric hub maps practice module', hub.includes("'fabric-practice': 'practice'"));
check('Curriculum includes executable practice module', curriculum.includes("id: 'fabric-practice'") && curriculum.includes('Executable evidence'));
check('Practice engine defines difficulty levels', engine.includes("'Easy' | 'Medium' | 'Challenge'"));
check('Practice engine defines SQL Python dbt decision exercises', ['kind: \'sql\'','kind: \'python\'','kind: \'dbt\'','kind: \'decision\''].every((token)=>engine.includes(token)));
check('Practice executes shared SQL runtime', engine.includes('executeWorkspaceSql'));
check('Practice executes shared Python runtime', engine.includes('executePythonLearning'));
check('Practice executes shared dbt runtime', engine.includes('runDbtCommand'));
check('Practice validates observable target tables', engine.includes('validateTarget') && engine.includes('findWorkspaceTable'));
check('Practice persists progress', engine.includes('loadPracticeProgress') && engine.includes('savePracticeProgress'));
check('Practice supports hint and solution penalties', engine.includes('hintPenalty') && engine.includes('solutionPenalty'));
check('Practice exports durable report', studio.includes('practiceReport') && studio.includes('practice-report.json'));
check('Practice filters by difficulty and kind', studio.includes('All levels') && studio.includes('Architecture'));
check('Practice supports direct workbench navigation', studio.includes('Open workbench') && studio.includes('onNavigate(selected.route)'));
check('Practice displays workspace snapshot evidence', studio.includes('workspace snapshot'));
check('Practice filters cannot leave a hidden exercise selected', studio.includes('filtered.some((exercise) => exercise.id === selectedId)'));
check('Architecture evidence does not reveal answer before completion', studio.includes("selected.kind === 'decision' && !state?.completed"));
check('Practice includes deliberate Spark avoidance scenarios', engine.includes('Do not start Spark') && engine.includes('Do not solve metadata-driven CDC with Spark'));
check('Practice includes justified Spark scenario', engine.includes('When Spark is actually justified'));
check('Practice styling exists', styles.includes('V13 executable hands-on practice') && styles.includes('.practice-layout'));
check('Power BI remains deferred', shell.includes('Power BI · next pass'));
const failed=results.filter((r)=>!r.ok); for(const r of results) console.log(`${r.ok?'PASS':'FAIL'}  ${r.name}`); console.log(`\n${results.length-failed.length}/${results.length} V13 exercise-depth static/depth QA checks passed.`); if(failed.length) process.exit(1);
