import fs from 'node:fs';
const read = (file) => fs.readFileSync(file, 'utf8');
const checks = [];
const check = (name, ok) => checks.push({ name, ok: Boolean(ok) });
const types = read('src/types/app.ts');
const learning = read('src/lib/tutorialLearning.ts');
const storage = read('src/lib/storage.ts');
const app = read('src/App.tsx');
const pipeline = read('src/components/PipelineStudio.tsx');
const tutorial = read('src/components/TutorialPanel.tsx');
const styles = read('src/styles.css');

check('Tutorial progress is first-class typed state', types.includes('interface TutorialProgress') && types.includes('interface TutorialStepProgress') && types.includes("TutorialMode = 'Guided' | 'Challenge'"));
check('Tutorial engine creates progress per case-study step', learning.includes('createTutorialProgress') && learning.includes('caseStudy.steps.map'));
check('Tutorial engine records validation attempts', learning.includes('recordTutorialValidation') && learning.includes('failedAttempts'));
check('Tutorial engine scores mastery', learning.includes('calculateStepScore') && learning.includes('masteryScore'));
check('Challenge mode penalizes assistance more strongly', learning.includes("mode === 'Challenge' ? 10 : 6") && learning.includes("mode === 'Challenge' ? 20 : 12"));
check('Hint ladder is capped at three levels', learning.includes('Math.min(3, step.hintLevel + 1)'));
check('Old saves migrate tutorial progress', storage.includes('normalizeTutorialProgress') && storage.includes('tutorialProgress?: TutorialProgress'));
check('App persists tutorial progress', app.includes('tutorialProgress') && app.includes('saveLab') && app.includes('normalizeTutorialProgress'));
check('Solution reveal and apply are tracked', app.includes('recordSolutionReveal') && app.includes('recordSolutionApplied'));
check('Pipeline validation updates tutorial mastery', pipeline.includes('recordTutorialValidation') && pipeline.includes('onTutorialProgress'));
check('Tutorial exposes Guided and Challenge modes', tutorial.includes('Guided') && tutorial.includes('Challenge'));
check('Tutorial exposes mastery dashboard', tutorial.includes('mastery-summary') && tutorial.includes('Mastery') && tutorial.includes('Completion'));
check('Tutorial exposes three-level hint ladder', tutorial.includes('Hint ladder') && tutorial.includes('Reveal hint'));
check('Next is locked until validation', tutorial.includes('navigationUnlocked') && tutorial.includes('Validate the current step to unlock Next'));
check('Tutorial exposes evidence navigation', tutorial.includes('Inspect evidence in other workbenches') && tutorial.includes("onNavigate('lakehouse')") && tutorial.includes("onNavigate('monitor')"));
check('Tutorial can reset only current step attempts', tutorial.includes('Reset step attempts') && tutorial.includes('resetTutorialStep'));
check('Tutorial exports a durable learning report', tutorial.includes('Export mission report') && tutorial.includes('learning-report.json') && learning.includes('buildTutorialReport'));
check('V12 learning styles are present', styles.includes('V12 guided-learning / mastery engine') && styles.includes('.hint-ladder') && styles.includes('.mastery-summary'));
check('Mission completion exposes mastery proof', tutorial.includes('Core mission complete') && tutorial.includes('mission-complete-banner'));
check('Recovery drill remains gated by final validation', tutorial.includes('Validate final step to unlock recovery drill') && tutorial.includes('disabled={!navigationUnlocked}'));
check('Power BI remains deferred', app.includes('Power BI is reserved for the next pass'));

const failed = checks.filter((c) => !c.ok);
for (const c of checks) console.log(`${c.ok ? 'PASS' : 'FAIL'}  ${c.name}`);
console.log(`\n${checks.length - failed.length}/${checks.length} V12 learning-system static/depth QA checks passed.`);
if (failed.length) process.exit(1);
