import fs from 'node:fs';
const read=(p)=>fs.readFileSync(p,'utf8');
const pkg=JSON.parse(read('package.json'));
const types=read('src/types/app.ts'); const app=read('src/App.tsx'); const shell=read('src/components/AppShell.tsx'); const hub=read('src/components/FabricHub.tsx'); const curriculum=read('src/data/curriculum.ts'); const production=read('src/components/ProductionWorkflowStudio.tsx'); const runtime=read('src/lib/productionWorkflow.ts'); const dbx=read('src/components/DatabricksStudios.tsx'); const fabricRuntime=read('src/components/FabricRuntimeStudio.tsx'); const styles=read('src/styles.css');
const results=[]; const check=(name,ok)=>results.push({name,ok:Boolean(ok)});
check('V15 package version declared', Number(pkg.version.split('.')[1] ?? 0)>=15);
check('Fabric production route is typed',types.includes("| 'production'"));
check('Databricks production route is typed',types.includes("| 'dbx-production'"));
check('App routes Fabric production workflow',app.includes("case 'production'")&&app.includes('platform="fabric"'));
check('App routes Databricks production workflow',app.includes("case 'dbx-production'")&&app.includes('platform="databricks"'));
check('Fabric navigation exposes production workflow',shell.includes("key: 'production'")&&shell.includes('Production workflow'));
check('Databricks navigation exposes production case study',shell.includes("key: 'dbx-production'")&&shell.includes('Production case study'));
check('Fabric curriculum adds production module',curriculum.includes("id: 'fabric-production'")&&curriculum.includes('Copy Job vs Copy activity'));
check('Databricks curriculum adds production module',curriculum.includes("id: 'dbx-production'")&&curriculum.includes('Managed vs external assets'));
check('Fabric hub maps production module',hub.includes("'fabric-production': 'production'"));
check('Production studio has seven lifecycle stages',production.includes('Production lifecycle')&&runtime.includes("'design' | 'govern' | 'ingest' | 'transform' | 'orchestrate' | 'serve' | 'operate'"));
check('Production studio separates real and learning behavior',production.includes('What a real engineer does')&&production.includes('What this simulator executes'));
check('Production progress derives from workspace evidence',production.includes('productionCompletedStages(workspace, caseStudy, platform)')&&runtime.includes('productionStageCompleted'));
check('Production walkthrough enforces recommended sequence',production.includes('Recommended production sequence')&&production.includes('disabled={!prerequisiteMet}'));
check('Fabric ERP production ingests both order and customer change feeds',runtime.includes('staging.fabric_sales_order_incremental')&&runtime.includes('staging.fabric_customer_incremental'));
check('Databricks ERP production ingests separate Bronze CDC feeds',runtime.includes('bronze.dbx_sales_order_changes')&&runtime.includes('bronze.dbx_customer_changes'));
check('Fabric plan teaches Workspace default vs Environment',runtime.includes('Workspace default vs attached environment')||runtime.includes('Workspace default')&&runtime.includes('Environment'));
check('Fabric Spark is case-specific',runtime.includes("caseStudy.id === 'turbine-realtime'")&&runtime.includes('distributed telemetry'));
check('Databricks plan includes Unity Catalog volume pattern',runtime.includes('external landing volume')&&runtime.includes('managed medallion tables'));
check('Databricks plan includes Auto Loader state',runtime.includes('checkpoint/schema location')&&runtime.includes('schema-evolution'));
check('Databricks plan includes Lakeflow expectations and AUTO CDC',runtime.includes('expectations')&&runtime.includes('AUTO CDC'));
check('Databricks notebook models SQL Warehouse language restriction',dbx.includes("compute==='SQL Warehouse'")&&dbx.includes('SQL Warehouse notebooks run SQL/Markdown cells only'));
check('Databricks compute models serverless classic and SQL Warehouse',dbx.includes("'Serverless'|'Classic'|'SQL Warehouse'"));
check('Unity Catalog workbench models external volume and READ VOLUME',dbx.includes('CREATE EXTERNAL VOLUME')&&dbx.includes('READ VOLUME'));
check('Auto Loader exposes schema evolution strategies',dbx.includes('addNewColumnsWithTypeWidening')&&dbx.includes('failOnNewColumns')&&dbx.includes('_rescued_data'));
check('Lakeflow pipeline exposes expectation actions',dbx.includes('Drop invalid')&&dbx.includes('Fail update')&&dbx.includes('Triggered')&&dbx.includes('Continuous'));
check('Lakeflow Jobs exposes current trigger categories',dbx.includes('Table update')&&dbx.includes('File arrival')&&dbx.includes('Continuous'));
check('Lakeflow Jobs supports repair-run learning',dbx.includes('Repair failed + skipped tasks'));
check('Fabric Spark Job Definition models main/reference/default Lakehouse/retry/snapshot',fabricRuntime.includes('Reference files')&&fabricRuntime.includes('Default Lakehouse')&&fabricRuntime.includes('Retry policy')&&fabricRuntime.includes('View run snapshot'));
check('V15 production styles exist',styles.includes('V15 production workflow')&&styles.includes('.production-layout'));
const failed=results.filter(r=>!r.ok); for(const r of results) console.log(`${r.ok?'PASS':'FAIL'}  ${r.name}`); console.log(`\n${results.length-failed.length}/${results.length} V15 production-fidelity static/depth QA checks passed.`); if(failed.length) process.exit(1);
