import fs from 'node:fs';
const read=(p)=>fs.readFileSync(p,'utf8');
const pkg=JSON.parse(read('package.json'));
const types=read('src/types/app.ts');
const app=read('src/App.tsx');
const monitor=read('src/components/MonitorView.tsx');
const dbx=read('src/components/DatabricksStudios.tsx');
const ops=read('src/lib/operationsRuntime.ts');
const styles=read('src/styles.css');
const results=[]; const check=(name,ok)=>results.push({name,ok:Boolean(ok)});
check('V16 package version declared', Number(pkg.version.split('.')[1] ?? 0)>=16);
check('Pipeline runs persist rerun metadata', types.includes('parentRunId?: string')&&types.includes("rerunMode?: 'Full retry' | 'From failed activity' | 'From selected activity'"));
check('Fabric retry runtime exists', ops.includes('createFabricRetryRun')&&ops.includes("From failed activity")&&(ops.includes('preserved_upstream')||ops.includes("rerunDisposition: 'Preserved'")));
check('Monitor exposes full retry', monitor.includes('Retry full run')&&monitor.includes("onRetry(r, 'Full retry')"));
check('Monitor exposes rerun from failed activity', monitor.includes('Rerun from failed activity')&&monitor.includes("onRetry(r, 'From failed activity')"));
check('Monitor exposes rerun from selected activity', monitor.includes('Rerun from here')&&monitor.includes("'From selected activity'"));
check('App wires Monitor retries into run history', app.includes('createFabricRetryRun')&&app.includes('onRetry='));
check('Auto Loader drift engine models restart requirement', ops.includes('Restart required')&&ops.includes('firmware_version'));
check('Auto Loader supports strict and rescue strategies', ops.includes('failOnNewColumns')&&ops.includes("status: 'Rescued'"));
check('Auto Loader workbench can inject schema drift', dbx.includes('Inject schema drift')&&dbx.includes('Restart stream'));
check('Auto Loader teaches rescued-data semantics', dbx.includes('Do not confuse rescue with success')&&dbx.includes('_rescued_data'));
check('Lakeflow Jobs exposes job parameters', dbx.includes('Job parameters')&&dbx.includes('{{job.parameters.processing_date}}'));
check('Lakeflow Jobs exposes task values', dbx.includes('{{tasks.ingest_bronze.values.rows_ingested}}'));
check('Lakeflow Jobs models queueing and concurrency', dbx.includes('Queue runs when concurrency is full')&&dbx.includes('Max concurrent runs'));
check('Lakeflow Jobs has run matrix history', dbx.includes('Matrix history')&&dbx.includes('job-run-matrix'));
check('Lakeflow Jobs repair warns about idempotency', (dbx.includes('Repair is not rollback')||dbx.includes('Repair is graph-aware, not rollback'))&&dbx.includes('idempotent writes'));
check('Databricks hub workbench count wording updated', dbx.includes('mapped into nine interactive workbenches'));
check('V16 operational styles exist', styles.includes('V16 operational realism')&&styles.includes('.monitor-retry-actions'));
const failed=results.filter(r=>!r.ok); for(const r of results) console.log(`${r.ok?'PASS':'FAIL'}  ${r.name}`); console.log(`\n${results.length-failed.length}/${results.length} V16 operational-realism static/depth QA checks passed.`); if(failed.length) process.exit(1);
