import fs from 'node:fs';
const read=(p)=>fs.readFileSync(p,'utf8');
const pkg=JSON.parse(read('package.json'));
const types=read('src/types/app.ts');
const pipeline=read('src/lib/pipeline.ts');
const ops=read('src/lib/operationsRuntime.ts');
const monitor=read('src/components/MonitorView.tsx');
const props=read('src/components/PropertiesPanel.tsx');
const dbx=read('src/components/DatabricksStudios.tsx');
const diag=read('src/components/ActivityDiagnostics.tsx');
const styles=read('src/styles.css');
const results=[]; const check=(name,ok)=>results.push({name,ok:Boolean(ok)});
check('V17 package version declared', Number(pkg.version.split('.')[1] ?? 0)>=17);
check('Pipeline activity run stores dependency snapshot', types.includes('PipelineRunDependency')&&types.includes('dependencies?: PipelineRunDependency[]'));
check('Pipeline activity run distinguishes preserved vs executed', types.includes("rerunDisposition?: 'Executed' | 'Preserved'"));
check('Pipeline run stores parameter and variable snapshots', types.includes('parameterValues?: Record<string, string>')&&types.includes('variableValues?: Record<string, string>'));
check('Pipeline createRun records dependency conditions', pipeline.includes("dependencies: edges.filter((edge) => edge.to === n.id)"));
check('Pipeline createRun records runtime parameter snapshot', pipeline.includes('parameterValues: Object.fromEntries(parameters.map'));
check('Fabric rerun scope follows descendants', ops.includes('descendantScope')&&ops.includes('fabricRetryScopeKeys'));
check('Fabric rerun re-evaluates dependency conditions', ops.includes('dependencyMatches')&&ops.includes('dependency condition was not satisfied after the rerun outcome changed'));
check('Fabric rerun preserves unrelated activity evidence', ops.includes("rerunDisposition: 'Preserved'")&&ops.includes("rerun_scope: 'preserved'"));
check('Fabric rerun carries runtime context forward', ops.includes('parameterValues: { ...(source.parameterValues ?? {}) }')&&ops.includes('variableValues: { ...(source.variableValues ?? {}) }'));
check('Monitor exposes runtime parameter snapshot', monitor.includes('Parameter + variable snapshot')&&monitor.includes('parameterValues'));
check('Monitor renders preserved activities distinctly', monitor.includes("activity.rerunDisposition === 'Preserved'")&&styles.includes('.status-pill.preserved'));
check('Activity diagnostics show rerun disposition', diag.includes('Execution')&&diag.includes('rerunDisposition'));
check('Fabric policy exposes increasing-delay retry', props.includes('Increasing Delay')&&props.includes('Max retry interval (seconds)'));
check('Fabric policy exposes conditional retry preview', props.includes('Retry condition (preview)')&&props.includes('Condition operator')&&props.includes('Condition value'));
check('ADF policy does not blindly inherit Fabric retry controls', props.includes("const fabricRetryFeatures = experience === 'fabric'"));
check('Retry runtime records condition matching and wait evidence', pipeline.includes('retry_condition_match')&&pipeline.includes('retry_wait_seconds'));
check('Retry validation caps count and validates max interval', pipeline.includes('retry must be between 0 and 1000')&&pipeline.includes('max retry interval must be at least'));
check('Databricks Jobs includes independent audit branch', dbx.includes('publish_audit')&&dbx.includes('independent branch'));
check('Databricks repair runtime computes dependent closure', ops.includes('repairTaskKeys')&&ops.includes('repairScope'));
check('Databricks repair marks executed vs preserved tasks', ops.includes("repairDisposition: 'Executed'")&&ops.includes("repairDisposition: 'Preserved'"));
check('Databricks Jobs exposes planned repair scope', dbx.includes('Planned repair scope')&&dbx.includes('plannedRepair'));
check('V17 operational styles are present', styles.includes('V17 graph-aware reruns and operational context')&&styles.includes('.monitor-runtime-context'));
const failed=results.filter(r=>!r.ok); for(const r of results) console.log(`${r.ok?'PASS':'FAIL'}  ${r.name}`); console.log(`\n${results.length-failed.length}/${results.length} V17 operational-depth static/depth QA checks passed.`); if(failed.length) process.exit(1);
