import fs from 'node:fs';
const read=(p)=>fs.readFileSync(p,'utf8');
const pkg=JSON.parse(read('package.json'));
const app=read('src/App.tsx');
const dbx=read('src/components/DatabricksStudios.tsx');
const governance=read('src/components/FabricGovernanceStudio.tsx');
const runtime=read('src/lib/dataRuntime.ts');
const ops=read('src/lib/operationsRuntime.ts');
const styles=read('src/styles.css');
const results=[]; const check=(name,ok)=>results.push({name,ok:Boolean(ok)});
check('V18 package version declared', Number(pkg.version.split('.')[1]??0)>=18);
check('App wires live workspace into Fabric Governance', app.includes('<FabricGovernanceStudio caseStudy={caseStudy} workspace={workspace} />'));
check('Fabric Governance renders live workspace catalog', governance.includes('workspace.tables')&&governance.includes('Search live OneLake catalog'));
check('Fabric Governance renders emitted lineage + impact', governance.includes('workspace.lineage')&&governance.includes('Analyze downstream impact'));
check('App wires live workspace into Unity Catalog', app.includes('<UnityCatalogStudio caseStudy={caseStudy} workspace={workspace} />'));
check('App wires live workspace into Auto Loader', app.includes('<DatabricksStreamingStudio caseStudy={caseStudy} workspace={workspace} onWorkspace={setWorkspace} />'));
check('App wires live workspace into Lakeflow Pipelines', app.includes('<LakeflowPipelinesStudio caseStudy={caseStudy} workspace={workspace} onWorkspace={setWorkspace} />'));
check('App wires live workspace into Databricks SQL', app.includes('<DatabricksSqlStudio caseStudy={caseStudy} workspace={workspace} onWorkspace={setWorkspace} />'));
check('Unity Catalog renders workspace tables', dbx.includes('workspace.tables.filter((table)=>table.schema===schema)'));
check('Unity Catalog reads emitted lineage', dbx.includes('workspace.lineage')&&dbx.includes('Live lineage'));
check('Auto Loader commits representative ingestion state', dbx.includes("runDatabricksProductionStage(workspace,caseStudy,'ingest')"));
check('Auto Loader schema evolution mutates target evidence', dbx.includes('applyAutoLoaderSchemaDriftToWorkspace'));
check('Auto Loader requires checkpoint for commit drill', dbx.includes('Enable checkpointing before this learning runtime will commit'));
check('Lakeflow Pipelines materializes transform stage', dbx.includes("runDatabricksProductionStage(next,caseStudy,'transform')"));
check('Lakeflow Pipelines materializes serving stage', dbx.includes("runDatabricksProductionStage(next,caseStudy,'serve')"));
check('Lakeflow fail-update drill stops downstream materialization', dbx.includes("expectationAction==='fail'")&&dbx.includes("setRunStatus('Failed')"));
check('Databricks SQL executes against workspace runtime', dbx.includes('executeWorkspaceSql(workspace,query'));
check('Databricks SQL catalog tree is live', dbx.includes('workspace.tables.filter((table)=>table.schema===schema)'));
check('Three-level SQL names are documented in workbench', dbx.includes('Three-level names'));
check('Workspace table lookup resolves catalog.schema.table', runtime.includes("const schemaTable = parts.length >= 2 ? parts.slice(-2).join('.')"));
check('Workspace writes strip catalog prefix to local schema.table', runtime.includes('const objectParts = parts.length >= 3 ? parts.slice(-2) : parts'));
check('Schema drift helper writes firmware_version evidence', ops.includes('applyAutoLoaderSchemaDriftToWorkspace')&&ops.includes("firmware_version: 'v3.8.1'"));
check('Schema drift helper writes rescued-data evidence', ops.includes('_rescued_data')&&ops.includes('rescue unexpected payload'));
check('V18 live-catalog styles are present', styles.includes('V18 live Databricks catalog and shared-workspace evidence'));
const failed=results.filter(r=>!r.ok); for(const r of results) console.log(`${r.ok?'PASS':'FAIL'}  ${r.name}`); console.log(`\n${results.length-failed.length}/${results.length} V18 live-workspace static/depth QA checks passed.`); if(failed.length) process.exit(1);
