import fs from 'node:fs';
const read=(p)=>fs.readFileSync(p,'utf8');
const pkg=JSON.parse(read('package.json'));
const insights=read('src/lib/workspaceInsights.ts');
const production=read('src/lib/productionWorkflow.ts');
const evidence=read('src/lib/caseStudyEvidence.ts');
const caseStudio=read('src/components/CaseStudyStudio.tsx');
const workflowStudio=read('src/components/ProductionWorkflowStudio.tsx');
const css=read('src/styles.css');
const results=[]; const check=(name,ok)=>results.push({name,ok:Boolean(ok)});
check('V21 package version declared',pkg.version==='0.21.0');
check('Workspace canonical name resolver exists',insights.includes('export function workspaceObjectCanonicalName'));
check('Workspace freshness model exists',insights.includes('export interface WorkspaceObjectFreshness')&&insights.includes("status: 'fresh' | 'stale' | 'missing'"));
check('Freshness recursively evaluates upstream lineage',insights.includes('sourceFreshness.status')&&insights.includes('sourceSnapshot > writeSnapshot'));
check('Production stage evidence has stale state',production.includes("export type ProductionStageEvidenceStatus = 'missing' | 'fresh' | 'stale'"));
check('Production stage freshness uses lifecycle ordering',production.includes('laterPrerequisite')&&production.includes('was refreshed at snapshot'));
check('ERP ingest requires both Fabric staged objects',production.includes("['staging.fabric_sales_order_incremental', 'staging.fabric_customer_incremental']"));
check('ERP ingest requires both Databricks Bronze objects',production.includes("['bronze.dbx_sales_order_changes', 'bronze.dbx_customer_changes']"));
check('Audit rows store evidence snapshots',production.includes('evidence_snapshot: workspace.snapshot + 1'));
check('Acceptance table evidence requires freshness',evidence.includes("freshness.status === 'fresh'")&&evidence.includes('Stale evidence:'));
check('Acceptance can select a fresh candidate among multiple platforms',evidence.includes('evaluated.find((item) => item.freshness.status ==='));
check('Lineage acceptance rejects stale downstream evidence',evidence.includes("Lineage exists, but its downstream evidence is stale"));
check('Case-study track syncs to selected product',caseStudio.includes('useEffect(() => setTrack(platform)'));
check('Case-study implementation exposes stale stage reason',caseStudio.includes('stale-reason')&&caseStudio.includes('staleStages'));
check('Case-study acceptance warns on stale evidence',caseStudio.includes('Downstream evidence is stale'));
check('Production workflow distinguishes Fresh/Stale/Not run',workflowStudio.includes('Fresh evidence')&&workflowStudio.includes('Stale evidence'));
check('Production workflow blocks on stale prerequisite',workflowStudio.includes("priorEvidence?.status === 'fresh'")&&workflowStudio.includes('Refresh “'));
check('V21 stale styling exists',css.includes('case-implementation-track article.stale')&&css.includes('case-acceptance-list article.stale'));
const failed=results.filter(r=>!r.ok); for(const r of results) console.log(`${r.ok?'PASS':'FAIL'}  ${r.name}`); console.log(`\n${results.length-failed.length}/${results.length} V21 freshness/consistency static QA checks passed.`); if(failed.length) process.exit(1);
