import fs from 'node:fs';
const read=(p)=>fs.readFileSync(p,'utf8');
const app=read('src/App.tsx'); const types=read('src/types/app.ts'); const shell=read('src/components/AppShell.tsx'); const hub=read('src/components/FabricHub.tsx'); const curriculum=read('src/data/curriculum.ts'); const challenge=read('src/lib/challengeEngine.ts'); const studio=read('src/components/ChallengeStudio.tsx'); const practice=read('src/lib/practiceEngine.ts'); const runtime=read('src/lib/dataRuntime.ts'); const styles=read('src/styles.css'); const pkg=JSON.parse(read('package.json'));
const results=[]; const check=(name,ok)=>results.push({name,ok:Boolean(ok)});
check('V14 package version declared',Number(pkg.version.split('.')[1] ?? 0)>=14);
check('Challenge route is typed',types.includes("| 'challenge'"));
check('App routes ChallengeStudio',app.includes("case 'challenge'")&&app.includes('<ChallengeStudio'));
check('Challenge receives workspace pipeline and run state',app.includes('nodes={nodes} edges={edges} runs={runs}'));
check('Fabric navigation exposes end-to-end challenge',shell.includes("key: 'challenge'")&&shell.includes('End-to-end challenge'));
check('Fabric hub maps challenge module',hub.includes("'fabric-challenge': 'challenge'"));
check('Curriculum includes challenge workbench',curriculum.includes("id: 'fabric-challenge'")&&curriculum.includes('Cross-surface state'));
check('Challenge engine defines three case missions',(challenge.match(/caseStudyId: '(retail-medallion|turbine-realtime|erp-incremental)'/g)||[]).length>=3);
check('Challenge validates observable tables',challenge.includes("type: 'table'")&&challenge.includes('findWorkspaceTable'));
check('Challenge validates pipeline graph not array order',challenge.includes('const outgoing = new Map')&&challenge.includes('walk(next'));
check('Challenge validates activity configuration',challenge.includes("type: 'node-config'"));
check('Challenge validates run evidence',challenge.includes("type: 'latest-run'"));
check('Challenge validates reliability and checkpoints',challenge.includes("type: 'reliability'")&&challenge.includes("type: 'checkpoint'"));
check('Challenge persists progress',challenge.includes('loadChallengeProgress')&&challenge.includes('saveChallengeProgress'));
check('Challenge exports report',studio.includes('challengeReport')&&studio.includes('end-to-end-challenge.json'));
check('Challenge stages are sequentially gated',studio.includes('previousComplete')&&studio.includes('Complete previous stage'));
check('Challenge can navigate to real workbenches',studio.includes('onNavigate(selected.route)'));
check('Challenge creates safe start checkpoint',studio.includes('Create start checkpoint')&&studio.includes('createWorkspaceCheckpoint'));
check('SQL runtime supports INNER and LEFT joins',runtime.includes("(LEFT|INNER)")&&runtime.includes('JOIN\\s+')&&runtime.includes('rightRows'));
check('SQL token resolver understands qualified aliases',runtime.includes('if (cleaned in row) return row[cleaned]'));
check('Practice adds retail join exercise',practice.includes("id: 'retail-sql-join'"));
check('Practice adds turbine join exercise',practice.includes("id: 'turbine-sql-join'"));
check('Practice adds ERP LEFT JOIN exercise',practice.includes("id: 'erp-sql-left-join'"));
check('Practice adds idempotent incremental dbt rerun',practice.includes("id: 'erp-dbt-idempotent'")&&practice.includes('repeatRuns: 2'));
check('Practice dbt runner checks stable row counts',practice.includes('stableCounts.every'));
check('V14 challenge styles exist',styles.includes('V14 cross-surface end-to-end challenge engine')&&styles.includes('.challenge-layout'));
check('Power BI remains deferred',shell.includes('Power BI · next pass'));
const failed=results.filter(r=>!r.ok); for(const r of results) console.log(`${r.ok?'PASS':'FAIL'}  ${r.name}`); console.log(`\n${results.length-failed.length}/${results.length} V14 static/depth QA checks passed.`); if(failed.length) process.exit(1);
