import {useEffect,useState} from 'react';
import type {FigureResource} from '../../../../../packages/contracts/src/foundation.ts';
import {patchView,replaceResource} from '../../../../../packages/contracts/src/workbench.ts';
import {figureFrames,type FigureFrame} from './semantics';
import type {ResourceHostProps} from '../workspace/ResourceHost';
import './figures.css';
/** One renderer for every frozen semantic frame; no per-concept canvas engines. */
export function SemanticFigure({frame}:{frame:FigureFrame}) {return <figure className="dp-semantic-figure"><figcaption><strong>{frame.title}</strong><p>{frame.explanation}</p></figcaption><div className="dp-figure-lanes">{frame.lanes.map(lane=><section key={lane.id} aria-label={lane.title}><h4>{lane.title}</h4>{lane.objects.map(item=><article key={item.id} data-state={item.state}><strong>{item.label}</strong><small>{item.detail}</small><span>{item.state}</span></article>)}</section>)}</div>{frame.columns.length>0&&<div className="table-scroller"><table><caption>Deterministic teaching result / {frame.result.length} rows</caption><thead><tr>{frame.columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{frame.result.map((row,i)=><tr key={i}>{frame.columns.map(c=><td key={c}>{row[c]===null?'NULL':row[c]}</td>)}</tr>)}</tbody></table></div>}</figure>}
export function FigureHost({resource,view,change,disabled}:ResourceHostProps&{resource:FigureResource}) {
 const [playing,setPlaying]=useState(false),[revealed,setRevealed]=useState(false),[reduced,setReduced]=useState(()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches);
 const mode=view.state?.join_mode==='inner'?'inner':'left';const frames=figureFrames(resource.family,mode),step=Math.max(0,Math.min(frames.length-1,Math.floor(Number(view.state?.figure_step)||0))),frame=frames[step];
 const advance=(index:number)=>change(s=>{const current=s.views.find(v=>v.id===view.id);return current?patchView(s,view.id,{state:{...current.state,figure_step:index}}):s},false);
 useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');const update=()=>{setReduced(media.matches);if(media.matches)setPlaying(false)};media.addEventListener('change',update);return()=>media.removeEventListener('change',update)},[]);
 useEffect(()=>{if(!playing||disabled||reduced)return;if(step===frames.length-1){setPlaying(false);return}const timer=setTimeout(()=>advance(step+1),1600);return()=>clearTimeout(timer)},[playing,disabled,reduced,step,resource.family,mode]);
 useEffect(()=>{setPlaying(false);setRevealed(false)},[resource.family,mode]);
 function freeze(){const blob=new Blob([JSON.stringify({schema_version:1,resource_id:resource.id,figure_version:resource.figure_version,family:resource.family,frame},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='datapass-figure-frame.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <section className="dp-figure-host"><header><small>ConceptMotion / focused Datapass FigureResource host</small><h2>{resource.title}</h2><p>{resource.description}</p><p className="dp-figure-truth">{frame.truth}. No workspace execution or table writes.</p></header><fieldset disabled={disabled}><label>Canonical figure family <select value={resource.family} onChange={e=>change(s=>replaceResource(s,{...resource,family:e.target.value as FigureResource['family']}))}>{(['join','partitions','workflow','lineage'] as const).map(f=><option key={f} value={f}>{f}</option>)}</select></label>{resource.family==='join'&&<label>This view's join <select value={mode} onChange={e=>change(s=>patchView(s,view.id,{state:{...view.state,join_mode:e.target.value,figure_step:0}}),false)}><option value="left">LEFT JOIN</option><option value="inner">INNER JOIN</option></select></label>}<div className="an-actions"><button disabled={step===0} onClick={()=>{setPlaying(false);advance(step-1)}}>Previous</button><button disabled={reduced} onClick={()=>{if(step===frames.length-1)advance(0);setPlaying(!playing)}}>{playing?'Pause':'Play'}</button><button disabled={step===frames.length-1} onClick={()=>{setPlaying(false);advance(step+1)}}>Next</button><button onClick={()=>{setPlaying(false);advance(0)}}>Reset view</button><button onClick={freeze}>Freeze frame JSON</button><span aria-live="polite">Step {step+1} / {frames.length}</span></div>{reduced&&<p>Reduced motion: manual stepping only.</p>}<SemanticFigure frame={frame}/><section className="dp-checkpoint"><h3>Checkpoint</h3><p>{frame.checkpoint}</p><button aria-expanded={revealed} onClick={()=>setRevealed(!revealed)}>{revealed?'Hide':'Reveal'} explanation</button>{revealed&&<p>{frame.answer}</p>}</section></fieldset></section>;
}
