/** Original, deterministic teaching specs. Never an execution engine or Spark profiler.
 * Renderer contract: stable object IDs + frozen semantic frames + explanatory text.
 * Source/version lives on FigureResource. Playback cursor lives on ViewInstance.
 */
export type FigureFamily='join'|'partitions'|'workflow'|'lineage';
export interface FigureObject {id:string;label:string;detail:string;state:'waiting'|'active'|'matched'|'null'|'failed'|'skipped'}
export interface FigureLane {id:string;title:string;objects:FigureObject[]}
export interface FigureFrame {id:string;title:string;explanation:string;lanes:FigureLane[];result:Array<Record<string,string|number|null>>;columns:string[];checkpoint:string;answer:string;truth:'authored teaching fixture'|'simulated task states'|'simulated partition assignment'}
export interface JoinRow {id:string;key:number|null;label:string}
export function equalityJoin(left:JoinRow[],right:JoinRow[],kind:'inner'|'left') {
 const result:Array<{left_id:string;right_id:string|null;key:number|null;value:string|null}>=[];
 for(const row of left){const matches=row.key===null?[]:right.filter(r=>r.key!==null&&r.key===row.key);for(const match of matches)result.push({left_id:row.id,right_id:match.id,key:row.key,value:match.label});if(!matches.length&&kind==='left')result.push({left_id:row.id,right_id:null,key:row.key,value:null})}
 return result;
}
export const joinFixture={left:[{id:'L1',key:1,label:'Order A'},{id:'L2',key:2,label:'Order B'},{id:'L3',key:null,label:'Order C'}],right:[{id:'R1',key:1,label:'Retail'},{id:'R2',key:1,label:'Wholesale'},{id:'R3',key:null,label:'Unassigned'}]} satisfies {left:JoinRow[];right:JoinRow[]};
const object=(id:string,label:string,detail:string,state:FigureObject['state']='waiting'):FigureObject=>({id,label,detail,state});
export function partitionBuckets(keys:number[],count:number):number[][] {if(!Number.isInteger(count)||count<1||count>8||keys.length>200||keys.some(k=>!Number.isSafeInteger(k)))throw new Error('Bounded integer teaching keys and 1-8 partitions required.');const buckets=Array.from({length:count},()=>[] as number[]);keys.forEach((key,i)=>buckets[((key%count)+count)%count].push(i));return buckets}
function joinFrames(kind:'inner'|'left'):FigureFrame[]{
 const {left,right}=joinFixture;
 return [0,1,2,3].map(step=>{const current=left[step-1];const partial=equalityJoin(left.slice(0,step),right,kind);
 return {id:`join-${kind}-${step}`,title:step===0?'Declare input grain':`Compare ${current.id}: key ${current.key??'NULL'}`,truth:'authored teaching fixture',explanation:step===0?'Each input row has its own stable identity. The right key 1 occurs twice; it is not unique.':current.key===1?'One left row pairs with two right rows. A join preserves both matches, not one arbitrary lookup.':kind==='left'?'No equality match. A LEFT JOIN emits one null-extended row; NULL = NULL is not true.':'No equality match. An INNER JOIN emits no row for this left input.',
 lanes:[{id:'left',title:'Orders (left)',objects:left.map(r=>object(r.id,r.id+' / '+r.label,'customer_key = '+(r.key??'NULL'),r.id===current?.id?'active':'waiting'))},{id:'right',title:'Customer segments (right)',objects:right.map(r=>object(r.id,r.id+' / '+r.label,'customer_key = '+(r.key??'NULL'),current?.key!==null&&current?.key!==undefined&&current.key===r.key?'matched':r.key===null?'null':'waiting'))}],result:partial,columns:['left_id','right_id','key','value'],checkpoint:'How many rows does the full LEFT JOIN return? Why not three?',answer:'Four rows: L1 matches twice, L2 is null-extended once, and L3 is null-extended once. INNER JOIN returns two.'};});
}
function partitionFrames():FigureFrame[]{
 const keys=[1,1,1,1,2,3,4,5],buckets=partitionBuckets(keys,3);
 return [0,1,2].map(step=>({id:`partitions-${step}`,title:['Input batches','Shuffle by a teaching key hash','Inspect skew, not measured time'][step],truth:'simulated partition assignment',explanation:step===0?'Input position is not a partition key. Rows have stable identities r1 through r8.':step===1?'For this figure only, partition = key modulo 3. Equal keys route together; this is not the actual Spark hash function.':'Bucket 1 contains five rows. More partitions alone cannot split one hot key while preserving this grouping rule.',lanes:step===0?[{id:'input',title:'Eight teaching rows',objects:keys.map((k,i)=>object(`r${i+1}`,`r${i+1}`,`key ${k}`))}]:buckets.map((indices,i)=>({id:`p${i}`,title:`Partition ${i} / ${indices.length} rows`,objects:indices.map(index=>object(`r${index+1}`,`r${index+1}`,`key ${keys[index]}`,i===1&&step===2?'active':'matched'))})),result:buckets.map((b,i)=>({partition:i,rows:b.length})),columns:['partition','rows'],checkpoint:'Would doubling the partitions necessarily remove the hot-key imbalance?',answer:'No. Equal-key grouping keeps a hot key together; a different data strategy or qualified runtime optimization is needed.'}));
}
function graphFrames(family:'workflow'|'lineage'):FigureFrame[]{
 const workflow=family==='workflow';const names=workflow?['Extract','Validate','Publish']:['Raw orders','Clean orders','Revenue model'];
 return [0,1,2,3].map(step=>({id:`${family}-${step}`,title:workflow?['Declared dependency','First task succeeds','Quality task fails','Downstream is skipped'][step]:['Authored data derivation','Read raw rows','Transform valid orders','Aggregate customer revenue'][step],truth:workflow?'simulated task states':'authored teaching fixture',explanation:workflow?'This timeline explains success-only dependencies. These are simulated states, not local job evidence. Real task attempts appear in Pipeline Lab.':'Arrows describe intended table-level derivation. This is not an observed run or automatically inferred column lineage.',lanes:names.map((name,i)=>({id:`node-${i}`,title:i===0?'Source':i===1?'Transform':'Consumer',objects:[object(`graph-${i}`,name,i<2?'Next: '+names[i+1]:'End of authored chain',workflow?(step===0?'waiting':i===0?'matched':i===1&&step>=2?'failed':i===2&&step===3?'skipped':'waiting'):(i===step-1?'active':i<step?'matched':'waiting'))]})),result:[],columns:[],checkpoint:workflow?'Why does Publish not run after Validate fails?':'Does a lineage arrow prove that its target has been refreshed?',answer:workflow?'The declared success-only dependency is not met. A separate independent branch could still run.':'No. The authored graph records intent. Inspect timestamped execution artifacts and freshness evidence for actual refresh.'}));
}
export function figureFrames(family:FigureFamily,mode:'inner'|'left'='left'):FigureFrame[]{switch(family){case 'join':return joinFrames(mode);case 'partitions':return partitionFrames();case 'workflow':case 'lineage':return graphFrames(family)}}
