import {useState} from 'react';
import {Badge,Button,Field,Input,Select} from '@fluentui/react-components';
import type {ExerciseDefinition,ExerciseAttempt,ExerciseResult,PracticeReview,PracticeProgress} from '../../../packages/contracts/src/index.ts';
export function InterviewBrowser({exercises,attempts,reviews,resume,onOpen,busy,progress,compact=false}:{exercises:ExerciseDefinition[];attempts:ExerciseAttempt[];reviews:Record<string,PracticeReview>;resume:Record<string,string>;onOpen:(e:ExerciseDefinition)=>void;busy:boolean;progress?:PracticeProgress;compact?:boolean}){
 const [topic,setTopic]=useState(''),[difficulty,setDifficulty]=useState(''),[status,setStatus]=useState(''),[search,setSearch]=useState(''),[language,setLanguage]=useState('');
 const solved=(e:ExerciseDefinition)=>progress?.exercises[e.id]?.solved??attempts.some(a=>a.exercise_id===e.id&&a.exercise_version===e.version&&a.status==='passed');
 const list=exercises.filter(e=>(!language||e.language===language)&&(!topic||e.topics.includes(topic))&&(!difficulty||e.difficulty===difficulty)&&(!search||`${e.title} ${e.tags.join(' ')}`.toLowerCase().includes(search.toLowerCase()))&&(!status||(status==='solved'?solved(e):status==='review'?reviews[e.id]?.review:status==='wrong-only'?progress?.exercises[e.id]?.latest_result==='failed':status==='retry'?!!progress?.exercises[e.id]?.attempt_count&&!solved(e):!solved(e))));
 return <div className={`surface-page interview-browser ${compact?'compact-browser':''}`}><h1>LeetCode-style Coding Arena</h1><p>Standalone interview exercises in the shared notebook. Run tries visible checks; Submit records a versioned attempt against visible, hidden and edge checks.</p><p className="notice">Internal demo fixtures only. No CodeDELeet question corpus has been migrated. Progress covers all saved attempts; detailed history shows the latest 200.</p>
 <div className="practice-filters"><Field label="Search"><Input value={search} onChange={(_,d)=>setSearch(d.value)}/></Field><Field label="Topic"><Select value={topic} onChange={(_,d)=>setTopic(d.value)}><option value="">All topics</option>{[...new Set(exercises.flatMap(e=>e.topics))].map(t=><option key={t}>{t}</option>)}</Select></Field><Field label="Difficulty"><Select value={difficulty} onChange={(_,d)=>setDifficulty(d.value)}><option value="">All difficulties</option>{['easy','medium','hard'].map(t=><option key={t}>{t}</option>)}</Select></Field><Field label="Kernel"><Select value={language} onChange={(_,d)=>setLanguage(d.value)}><option value="">All kernels</option>{[...new Set(exercises.map(e=>e.language))].map(k=><option key={k}>{k}</option>)}</Select></Field><Field label="Status"><Select value={status} onChange={(_,d)=>setStatus(d.value)}><option value="">All statuses</option>{['solved','unsolved','review','wrong-only','retry'].map(t=><option key={t}>{t}</option>)}</Select></Field></div>
 {progress&&<details open={!compact}><summary>Curriculum progress</summary>{Object.entries(progress.topics).map(([name,p])=><p key={name}>{name}: {p.solved}/{p.total} solved {exercises.filter(e=>e.topics.includes(name)&&resume[`${e.language}/${e.canonical_placement.topic}`]===e.id).map(e=><Button key={e.id} size="small" disabled={busy} onClick={()=>onOpen(e)}>Resume {e.language}</Button>)}</p>)}{Object.entries(progress.difficulty).map(([name,p])=><p key={name}>{name}: {p.solved}/{p.total}</p>)}</details>}
 {(()=>{const next=[...list].filter(e=>!solved(e)&&e.recommendation).sort((a,b)=>a.recommendation!.rank-b.recommendation!.rank||a.id.localeCompare(b.id))[0];return next&&<Button disabled={busy} onClick={()=>onOpen(next)}>Next recommended: {next.title}</Button>})()}
 <div className="case-grid">{list.map(e=><article className="case-card" key={e.id}><Badge appearance="tint">{e.difficulty} · {e.language}</Badge><h2>{e.title}</h2><p>{e.prompt}</p><p>Canonical: {e.canonical_placement.domain} / {e.canonical_placement.topic}<br/>Related: {e.related_associations.join(', ')}</p><p>{solved(e)?'Previously solved':'Unsolved'} · {progress?.exercises[e.id]?.attempt_count??attempts.filter(a=>a.exercise_id===e.id&&a.exercise_version===e.version).length} attempts · latest {progress?.exercises[e.id]?.latest_result??'none'} · best {progress?.exercises[e.id]?.best_status??'none'}{progress?.exercises[e.id]?.last_attempted&&<small>Last attempted: {progress.exercises[e.id].last_attempted}</small>}{reviews[e.id]?.review?' · Review':''}</p>{e.recommendation&&<p>Recommendation {e.recommendation.rank}: {e.recommendation.reason}</p>}<Button disabled={busy} onClick={()=>onOpen(e)}>{resume[`${e.language}/${e.canonical_placement.topic}`]===e.id?'Resume practice':'Open exercise'}</Button></article>)}</div>{!list.length&&<p>No exercises match these filters.</p>}</div>;
}
export function ExerciseGuidance({exercise,hints,onHint,solution,onSolution,busy}:{exercise:ExerciseDefinition;hints:number;onHint:()=>void;solution?:string;onSolution:()=>void;busy:boolean}){
 return <div className="lesson-pane"><h3>Hints</h3>{exercise.hints.slice(0,hints).map((h,i)=><p key={i}>{h}</p>)}<Button size="small" disabled={busy||hints>=exercise.hints.length} onClick={onHint}>Reveal next hint</Button><h3>Reference solution</h3><Button size="small" disabled={busy||!exercise.solution.available} onClick={onSolution}>{solution?'Hide solution':'Reveal reference solution'}</Button>{solution&&<pre>{solution}</pre>}<details><summary>Explanation</summary><p>{exercise.explanation}</p></details><h3>Follow-up / reflection</h3>{exercise.follow_ups.map(p=><p key={p}>{p}</p>)}</div>;
}
export function ExerciseEvidence({result,attempts,currentSource}:{result?:ExerciseResult;attempts:ExerciseAttempt[];currentSource:string}){
 return <div className="exercise-evidence" aria-live="polite">{!result&&attempts[0]&&<p>Last Submit: <b>{attempts[0].status}</b> · {attempts[0].source===currentSource?'Same source as saved attempt':'Historical source'}</p>}{result&&<><h3>{result.attempt?'Submit':'Run'}: {result.status}</h3><p>{result.truth} · {result.runtime.engine} · measured {result.elapsed_ms} ms</p>{result.error&&<p>{result.error.message}</p>}{result.checks.map(c=><div key={c.id}><Badge color={c.passed?'success':'warning'}>{c.visibility}: {c.passed?'passed':'failed'}</Badge><p>{c.message}</p>{c.visibility==='visible'&&<details><summary>Actual / expected</summary><pre>{JSON.stringify({actual:c.actual,expected:c.expected},null,2)}</pre></details>}</div>)}</>}
 <details><summary>Attempt history ({attempts.length})</summary>{attempts.map(a=><article key={a.id}><b>{a.status} · {a.created_at}</b><p>Exercise v{a.exercise_version} · {a.validator_version} · source revision {a.source_revision} · {a.source===currentSource?'Matches current source':'Historical source'}</p><details><summary>Submitted source and evidence</summary><pre>{a.source}</pre><pre>{JSON.stringify({source_hash:a.source_hash,fixtures:a.fixtures,runtime:a.runtime,checks:a.checks},null,2)}</pre></details></article>)}</details></div>;
}
export function ExerciseContext({exercise}:{exercise:ExerciseDefinition}) {
 return <div className="exercise-context"><Badge>{exercise.language} · {exercise.truth??'real'}</Badge><p>{exercise.runtime}</p>{exercise.runtime_requirements?.length?<p>Requires: {exercise.runtime_requirements.join(', ')}</p>:null}
 {exercise.data_context?.map(table=><details open key={table.name}><summary>Input: {table.name}</summary><p>{Object.entries(table.columns).map(([n,t])=>`${n}: ${t}`).join(', ')}</p>{table.catalog_ref&&<p>Catalog: {table.catalog_ref}</p>}<pre>{JSON.stringify(table.sample_rows,null,2)}</pre></details>)}
 {!!Object.keys(exercise.output_schema??{}).length&&<p>Output schema: {Object.entries(exercise.output_schema??{}).map(([n,t])=>`${n}: ${t}`).join(', ')}</p>}
 {Object.entries(exercise.constraints??{}).map(([name,value])=><p key={name}><b>{name}</b>: {value}</p>)}{exercise.context_refs?.map(ref=><p key={ref}>Context: {ref}</p>)}
 <details><summary>Result contract and provenance</summary><pre>{JSON.stringify({validation:exercise.validation,pack:exercise.pack,provenance:exercise.provenance},null,2)}</pre></details></div>;
}
