import {useState} from 'react';
import {Badge,Button,Field,Input,Select} from '@fluentui/react-components';
import type {ExerciseDefinition,ExerciseAttempt,ExerciseResult,PracticeReview} from '../../../packages/contracts/src/index.ts';

export function InterviewBrowser({exercises,attempts,reviews,resume,onOpen,busy}:{exercises:ExerciseDefinition[];attempts:ExerciseAttempt[];reviews:Record<string,PracticeReview>;resume:Record<string,string>;onOpen:(e:ExerciseDefinition)=>void;busy:boolean}){
 const [topic,setTopic]=useState(''),[difficulty,setDifficulty]=useState(''),[status,setStatus]=useState(''),[search,setSearch]=useState('');
 const solved=(e:ExerciseDefinition)=>attempts.some(a=>a.exercise_id===e.id&&a.exercise_version===e.version&&a.status==='passed');
 const list=exercises.filter(e=>(!topic||e.topics.includes(topic))&&(!difficulty||e.difficulty===difficulty)&&(!search||`${e.title} ${e.tags.join(' ')}`.toLowerCase().includes(search.toLowerCase()))&&(!status||(status==='solved'?solved(e):status==='review'?reviews[e.id]?.review:!solved(e))));
 return <div className="surface-page interview-browser"><h1>Interview Practice</h1><p>Standalone exercises in the shared notebook. Run tries visible checks; Submit records a versioned attempt against visible, hidden and edge checks.</p><p className="notice">Internal demo fixtures only. No CodeDELeet question corpus has been migrated. Status reflects the latest 200 attempts in this workspace.</p>
 <div className="practice-filters"><Field label="Search"><Input value={search} onChange={(_,d)=>setSearch(d.value)}/></Field><Field label="Topic"><Select value={topic} onChange={(_,d)=>setTopic(d.value)}><option value="">All topics</option>{[...new Set(exercises.flatMap(e=>e.topics))].map(t=><option key={t}>{t}</option>)}</Select></Field><Field label="Difficulty"><Select value={difficulty} onChange={(_,d)=>setDifficulty(d.value)}><option value="">All difficulties</option>{['easy','medium','hard'].map(t=><option key={t}>{t}</option>)}</Select></Field><Field label="Status"><Select value={status} onChange={(_,d)=>setStatus(d.value)}><option value="">All statuses</option>{['solved','unsolved','review'].map(t=><option key={t}>{t}</option>)}</Select></Field></div>
 <div className="case-grid">{list.map(e=><article className="case-card" key={e.id}><Badge appearance="tint">{e.difficulty} · {e.language}</Badge><h2>{e.title}</h2><p>{e.prompt}</p><p>Canonical: {e.canonical_placement.domain} / {e.canonical_placement.topic}<br/>Related: {e.related_associations.join(', ')}</p><p>{solved(e)?'Previously solved':'Unsolved'}{reviews[e.id]?.review?' · Review':''}</p>{e.recommendation&&<p>Recommendation {e.recommendation.rank}: {e.recommendation.reason}</p>}<Button disabled={busy} onClick={()=>onOpen(e)}>{resume[`${e.language}/${e.canonical_placement.topic}`]===e.id?'Resume practice':'Open exercise'}</Button></article>)}</div>{!list.length&&<p>No exercises match these filters.</p>}</div>;
}

export function ExerciseGuidance({exercise,hints,onHint,solution,onSolution,busy}:{exercise:ExerciseDefinition;hints:number;onHint:()=>void;solution?:string;onSolution:()=>void;busy:boolean}){
 return <div className="lesson-pane"><h3>Hints</h3>{exercise.hints.slice(0,hints).map((h,i)=><p key={i}>{h}</p>)}<Button size="small" disabled={busy||hints>=exercise.hints.length} onClick={onHint}>Reveal next hint</Button><h3>Reference solution</h3><Button size="small" disabled={busy||!exercise.solution.available} onClick={onSolution}>{solution?'Hide solution':'Reveal reference solution'}</Button>{solution&&<pre>{solution}</pre>}<details><summary>Explanation</summary><p>{exercise.explanation}</p></details><h3>Follow-up / reflection</h3>{exercise.follow_ups.map(p=><p key={p}>{p}</p>)}</div>;
}

export function ExerciseEvidence({result,attempts,currentSource}:{result?:ExerciseResult;attempts:ExerciseAttempt[];currentSource:string}){
 return <div className="exercise-evidence" aria-live="polite">{!result&&attempts[0]&&<p>Last Submit: <b>{attempts[0].status}</b> � {attempts[0].source===currentSource?'Same source as saved attempt':'Historical source'}</p>}{result&&<><h3>{result.attempt?'Submit':'Run'}: {result.status}</h3><p>{result.truth} · {result.runtime.engine} · measured {result.elapsed_ms} ms</p>{result.error&&<p>{result.error.message}</p>}{result.checks.map(c=><div key={c.id}><Badge color={c.passed?'success':'warning'}>{c.visibility}: {c.passed?'passed':'failed'}</Badge><p>{c.message}</p>{c.visibility==='visible'&&<details><summary>Actual / expected</summary><pre>{JSON.stringify({actual:c.actual,expected:c.expected},null,2)}</pre></details>}</div>)}</>}
 <details><summary>Attempt history ({attempts.length})</summary>{attempts.map(a=><article key={a.id}><b>{a.status} · {a.created_at}</b><p>Exercise v{a.exercise_version} · {a.validator_version} · source revision {a.source_revision} · {a.source===currentSource?'Matches current source':'Historical source'}</p><details><summary>Submitted source and evidence</summary><pre>{a.source}</pre><pre>{JSON.stringify({source_hash:a.source_hash,fixtures:a.fixtures,runtime:a.runtime,checks:a.checks},null,2)}</pre></details></article>)}</details></div>;
}
