import {Badge,Tab,TabList} from '@fluentui/react-components';
import {useState} from 'react';
import type {Simulation} from '../../../packages/contracts/src/index';

const panes=['Logical plan','Physical teaching plan','Jobs','Stages','Tasks preview','Shuffle / skew','Cost / runtime estimate','Truth / assumptions'];
export function SparkInspector({simulation:s}:{simulation:Simulation}){
 const [pane,setPane]=useState('Logical plan');
 const m=s.metrics,stages=m?.stages??[];
 if(s.status!=='modeled'||!m)return <p className="notice">UNAVAILABLE / UNSUPPORTED: {s.reason??'No physical evidence was saved for this run.'}</p>;
 return <section className="spark-inspector" aria-label="SparkLab run inspector">
  <div className="tag-row"><Badge appearance="tint">REAL LOCAL RESULT above</Badge><Badge color="warning" appearance="tint">SIMULATED DISTRIBUTED METRICS</Badge></div>
  <p>{s.profile_id} · AQE {s.aqe?'on':'off'} · {s.truth}. This is saved run evidence; changing the runtime selector applies to the next run.</p>
  <TabList selectedValue={pane} onTabSelect={(_,d)=>setPane(String(d.value))} size="small">{panes.map(name=><Tab key={name} value={name}>{name}</Tab>)}</TabList>
  <div className="spark-pane" role="region" aria-label={pane}>
  {pane==='Logical plan'&&<><p>Transformations build lazy plans. Run requests the bounded local notebook preview action ({s.action??'notebook_preview'}).</p><ol>{s.logical_plan?.map(n=><li key={n.id}><b>{n.id}: {n.operation} {n.source}</b> — {n.dependency}; parents {n.parents.join(', ')||'none'}<p>{n.concept}</p></li>)}</ol></>}
  {pane==='Physical teaching plan'&&<><p>Each logical operator receives a teaching stage; real Spark may fuse operators. Partition and exchange choices below are simulated. DuckLake scan facts are shown separately from modeled Spark behavior.</p>{stages.map(stage=><article key={stage.stage_id}><h4>{stage.stage_id}: {stage.operator}</h4><p>{stage.task_count} tasks · dependencies {stage.dependencies?.join(', ')||'none'} · {stage.sort?'sort required':'no modeled sort'} · broadcast {stage.broadcast_mb??0} MiB</p>{stage.source_evidence&&<p><b>Measured source:</b> {stage.source_evidence.source_files} Parquet file{stage.source_evidence.source_files===1?'':'s'} · snapshot {stage.source_evidence.snapshot_id??'unknown'} · {stage.source_evidence.small_file_count} small file{stage.source_evidence.small_file_count===1?'':'s'}</p>}<ul>{stage.notes?.map((note,i)=><li key={i}>{note}</li>)}</ul></article>)}</>}
  {pane==='Jobs'&&<><h4>{m.job_id??'Saved virtual job'}</h4><p>{stages.length} stages · {m.total_duration_s.toFixed(3)} simulated seconds · {m.core_hours} allocated core-hours · {m.cluster_utilization_pct??'unavailable'}% executor slot utilization</p><p>Startup {m.startup_overhead_s??0}s; scheduler overhead {m.scheduler_overhead_s??0}s. Tasks run in virtual executor slots; a dependent teaching stage waits for its parents.</p></>}
  {pane==='Stages'&&<div className="table-scroller"><table><thead><tr><th>Stage / dependencies</th><th>Tasks</th><th>Assumed rows in/out</th><th>Assumed bytes in/out</th><th>Seconds p50 / p95 / max</th></tr></thead><tbody>{stages.map(x=><tr key={x.stage_id}><td>{x.stage_id}: {x.name} / {x.dependencies?.join(', ')||'none'}</td><td>{x.task_count}</td><td>{x.input_rows} / {x.output_rows}</td><td>{x.input_bytes} / {x.output_bytes}</td><td>{x.p50_task_s} / {x.p95_task_s} / {x.max_task_s}</td></tr>)}</tbody></table></div>}
  {pane==='Tasks preview'&&<><p>First 12 tasks per stage. Task times are relative to their stage, not real telemetry.</p>{stages.map(x=><details key={x.stage_id}><summary>Stage {x.stage_id}: {x.task_count} tasks</summary><table><thead><tr><th>Task / slot</th><th>MiB</th><th>Start / finish (s)</th><th>Spill MiB</th><th>Skew</th></tr></thead><tbody>{x.tasks?.map(t=><tr key={t.task_id}><td>{t.task_id} / {t.worker_slot}</td><td>{t.partition_mb}</td><td>{t.start_s} / {t.finish_s}</td><td>{t.spill_mb}</td><td>{t.skewed?'yes':'no'}</td></tr>)}</tbody></table></details>)}</>}
  {pane==='Shuffle / skew'&&<><p>{m.shuffle_gb} GiB shuffle · {m.spill_gb} GiB spill. Spill follows assumed working-set memory and executor memory per slot.</p>{stages.map(x=><p key={x.stage_id}>{x.stage_id}: {x.shuffle_read_gb??0}/{x.shuffle_write_gb??0} GiB read/write · {x.skewed_tasks??0} skewed tasks · {x.straggler?'straggler tail':'no modeled straggler'} · spill {x.spill_gb??0} GiB</p>)}</>}
  {pane==='Cost / runtime estimate'&&<><h4>{s.datapass_credits?.total??s.cost?.sparklab.scc} fictional Datapass Credits</h4><p>{s.datapass_credits?.formula}</p><p>{s.datapass_credits?.explanation}</p><ul>{Object.entries(s.datapass_credits?.contributors??{}).map(([name,value])=><li key={name}>{name}: {value}</li>)}</ul><p>What changes: virtual slots, throughput, startup, memory pressure and AQE grouping. These comparisons reuse the same plan and assumptions; they do not grade or recompute result rows.</p><table><thead><tr><th>Profile</th><th>AQE</th><th>Seconds (change)</th><th>Credits</th></tr></thead><tbody>{s.comparisons?.map(c=><tr key={`${c.profile_id}-${c.aqe}`}><td>{c.profile_id}</td><td>{c.aqe?'on':'off'}</td><td>{c.duration_s} ({c.duration_delta_s>=0?'+':''}{c.duration_delta_s})</td><td>{c.credits}</td></tr>)}</tbody></table></>}
  {pane==='Truth / assumptions'&&<><h4>MEASURED + MODELED EVIDENCE</h4><p>DuckLake file counts, file bytes, snapshot IDs and delete-file counts are measured when present. Spark task counts, shuffle, spill, durations and cost remain simulations. A filter can be a pruning opportunity, but SparkLab does not claim an actual pruned-file count without scan telemetry.</p><pre>{JSON.stringify(s.assumptions??{status:'Legacy evidence; assumptions not recorded'},null,2)}</pre><h4>UNAVAILABLE / UNSUPPORTED</h4><p>Real Spark telemetry, actual DuckLake files-scanned/pruned counters, benchmark calibration, cache reuse, vendor billing and cluster provisioning are unavailable.</p></>}
  </div>
 </section>;
}
