import * as React from 'react';
import type {LabProject, Layer, Pane, StudioSession} from './types';
import {closeTab, importProject, LAYERS, moveTab, openLayer, splitSession, singlePaneSession, validateProject} from './project';
import {DbtStudio, LineageStudio} from './DbtStudio';
import {ModelStudio, ScdStudio} from './ModelStudio';
import {ChartsStudio} from './ChartsStudio';
import {GuidedSparkStudio, RuntimeStudio} from './RuntimeStudio';
import {FileImport, downloadText} from './controls';
import './analytics.css';
export interface AnalyticsWorkbenchProps {
  project: LabProject; onChange: (project: LabProject) => void; notebookContent: React.ReactNode;
  ownerTitle: string; onSave: () => void; busy?: boolean; preview?: boolean; restoreError?: string;
}
export function AnalyticsWorkbench({project,onChange,notebookContent,ownerTitle,onSave,busy=false,preview=false,restoreError}:AnalyticsWorkbenchProps) {
  const [error,setError]=React.useState(''),[focus,setFocus]=React.useState(false),[palette,setPalette]=React.useState(false),[search,setSearch]=React.useState('');
  const [newTabPane,setNewTabPane]=React.useState<Pane['id']|null>(null);
  const latest=React.useRef(project); latest.current=project;
  const root=React.useRef<HTMLDivElement>(null), area=React.useRef<HTMLDivElement>(null);
  const session=project.session;
  const safe=(action:()=>void)=>{try{action();setError('');}catch(e){setError(e instanceof Error?e.message:String(e));}};
  const commit=(next:LabProject)=>{
    if(busy)throw new Error('Wait for the current operation before editing the analytics attachment.');
    if(restoreError)throw new Error('The saved analytics document could not be restored. Export the original notebook before replacing it.');
    if(latest.current!==project)throw new Error('The document changed while a file was being read. Import cancelled; current edits were retained.');
    const candidate={...next,revision:project.revision+1};
    if(new TextEncoder().encode(JSON.stringify(candidate)).length>1_200_000)throw new Error('Analytics attachment exceeds 1.2 MB. Use smaller artifacts/row samples; the current design is retained. The whole notebook also has a backend size limit.');
    onChange(candidate);
  };
  const patchSession=(patch:Partial<StudioSession>)=>safe(()=>commit({...project,session:{...session,...patch}}));
  const select=(layer:Layer,pane:Pane['id']=session.activePane)=>safe(()=>{commit({...project,session:openLayer(session,layer,pane)});setNewTabPane(null);setPalette(false);});
  React.useEffect(()=>{const key=(e:KeyboardEvent)=>{
    if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();e.stopImmediatePropagation();setPalette(p=>!p);setSearch('');}
    if(e.key==='Escape'){setFocus(false);setPalette(false);setNewTabPane(null);}
  };window.addEventListener('keydown',key,true);return()=>window.removeEventListener('keydown',key,true);},[]);
  const currentPane=session.panes.find(p=>p.id===session.activePane)??session.panes[0];
  const currentLayer=currentPane.tabs.find(t=>t.id===currentPane.active)?.layer;
  const visible=session.panes.filter(p=>p.id!==session.collapsed);
  const notebookPanes=visible.filter(p=>p.tabs.find(t=>t.id===p.active)?.layer==='notebook');
  const liveNotebookPane=(notebookPanes.find(p=>p.id===session.activePane)??notebookPanes[0])?.id;
  const layerContent=(layer:Layer,pane:Pane)=>{
    const props={project,onChange:(next:LabProject)=>safe(()=>commit(next)),onError:setError};
    switch(layer){
      case 'notebook':return pane.id===liveNotebookPane?<div className="an-shared-notebook">{notebookContent}</div>:<div className="an-empty"><h3>Shared notebook reference</h3><p>Only one live notebook editor mounts at a time. Focus this pane to transfer editing without copying source.</p><button onClick={()=>patchSession({activePane:pane.id})}>Edit notebook here</button></div>;
      case 'dbt':return <DbtStudio {...props}/>;
      case 'lineage':return <LineageStudio {...props}/>;
      case 'model':return <ModelStudio {...props}/>;
      case 'scd':return <ScdStudio {...props}/>;
      case 'charts':return <ChartsStudio {...props}/>;
      case 'connections':return <RuntimeStudio/>;
      case 'sparklab':return <GuidedSparkStudio/>;
    }
  };
  return <div ref={root} className={`an-workbench ${focus?'an-focus':''}`} data-theme={session.theme} aria-label="Analytics workbench">
    {!focus&&<><div className="an-topline"><div className="an-owner"><span className="an-logo">D</span><div><b>{project.title}</b><small>{ownerTitle} / shared source</small></div><span className="an-badge">ANALYTICS M2</span></div><button onClick={()=>{setPalette(true);setSearch('');}}>Find a view <kbd>Ctrl K</kbd></button></div>
    <div className="an-commandbar"><button className={session.explorerOpen?'selected':''} aria-label="Toggle analytics explorer" aria-pressed={session.explorerOpen} onClick={()=>patchSession({explorerOpen:!session.explorerOpen})}>Explorer</button><button aria-label="Split right" onClick={()=>safe(()=>commit({...project,session:splitSession(session,'horizontal')}))}>Split right</button><button aria-label="Split down" onClick={()=>safe(()=>commit({...project,session:splitSession(session,'vertical')}))}>Split down</button><span className="an-command-spacer"/><button onClick={onSave} disabled={busy}>Save notebook + views</button><button aria-label="Toggle analytics context" aria-pressed={session.contextOpen} className={session.contextOpen?'selected':''} onClick={()=>patchSession({contextOpen:!session.contextOpen})}>Context</button><label className="an-theme-label">Theme<select aria-label="Analytics theme" value={session.theme} onChange={e=>patchSession({theme:e.target.value as StudioSession['theme']})}><option value="fluent">Fluent light</option><option value="neutral">Neutral</option><option value="dark">Dark slate</option></select></label><button onClick={()=>setFocus(true)}>Focus</button><details className="an-menu"><summary aria-label="Analytics more actions">More</summary><div><button onClick={()=>downloadText('datapass-analytics.json',JSON.stringify(project,null,2),'application/json')}>Export analytics JSON</button><FileImport label="Import analytics JSON" onError={setError} onRead={text=>safe(()=>{const candidate=importProject(text);if(window.confirm('Replace this notebook\'s analytics design, sources and layout? The notebook code itself will not be replaced.'))commit(candidate);})}/><button onClick={()=>safe(()=>commit({...project,session:singlePaneSession(session)}))}>Single pane (keep tabs)</button><button onClick={()=>patchSession({explorerOpen:false,contextOpen:false})}>Hide both sidebars</button><p>Analytics JSON is not a complete notebook or data backup. Export the notebook separately.</p></div></details></div></>}
    {focus&&<button className="an-exit-focus" onClick={()=>setFocus(false)}>Exit focus / Esc</button>}
    {(error||restoreError)&&<div className="an-error" role="alert"><span>{error||restoreError}</span><button onClick={()=>setError('')}>Dismiss</button>{restoreError&&<button onClick={()=>{if(window.confirm('The invalid attachment remains in the original notebook until you replace it. Export that notebook first. Replace analytics with a fresh design?'))onChange(project);}}>Replace invalid analytics</button>}</div>}
    <div className="an-body">{session.explorerOpen&&!focus&&<aside className="an-navigation" aria-label="Analytics layers"><div className="an-sidebar-title"><b>Workspace</b><button aria-label="Collapse analytics explorer" onClick={()=>patchSession({explorerOpen:false})}>x</button></div><div className="an-section-label">TOOLS / SAME DOCUMENT</div>{LAYERS.map(l=><button className={l.id===currentLayer?'selected':''} key={l.id} onClick={()=>select(l.id)} title={l.description}><span className={`an-layer-symbol an-symbol-${l.id}`}>{l.id==='dbt'?'dbt':l.id==='scd'?'SCD':l.id==='charts'?'BI':l.id==='notebook'?'{}':l.id==='lineage'?'-o':l.id==='model'?'*':l.id==='sparklab'?'S':'o'}</span><span>{l.label}</span></button>)}<div className="an-sidebar-note"><b>One source, many views</b><p>Tabs and panes do not clone notebook code, data, or run history.</p><small>dbt sources and designs are an attachment to this notebook in M2.</small></div></aside>}
    <div className={`an-panes ${session.direction}`} ref={area}>
      {session.panes.map((pane,index)=>{const tab=pane.tabs.find(t=>t.id===pane.active);if(session.collapsed===pane.id)return <button key={pane.id} className="an-collapsed-pane" aria-label={`Restore pane ${pane.id.toUpperCase()}`} onClick={()=>patchSession({collapsed:null,activePane:pane.id})}><span>{pane.id.toUpperCase()}</span><span>Restore</span></button>;
      return <React.Fragment key={pane.id}>{index===1&&!session.collapsed&&<div role="separator" aria-label="Resize workspace panes" aria-orientation={session.direction==='horizontal'?'vertical':'horizontal'} aria-valuemin={25} aria-valuemax={75} aria-valuenow={Math.round(session.ratio)} tabIndex={0} className="an-splitter" onKeyDown={e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home'].includes(e.key)){e.preventDefault();patchSession({ratio:e.key==='Home'?50:Math.max(25,Math.min(75,session.ratio+(['ArrowRight','ArrowDown'].includes(e.key)?2:-2)))});}}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);e.currentTarget.dataset.resizing='yes';}} onPointerMove={e=>{if(e.currentTarget.dataset.resizing!=='yes'||!area.current)return;const rect=area.current.getBoundingClientRect();const value=session.direction==='horizontal'?(e.clientX-rect.left)/rect.width:(e.clientY-rect.top)/rect.height;patchSession({ratio:Math.max(25,Math.min(75,value*100))});}} onPointerUp={e=>{delete e.currentTarget.dataset.resizing;}} onPointerCancel={e=>{delete e.currentTarget.dataset.resizing;}} onLostPointerCapture={e=>{delete e.currentTarget.dataset.resizing;}}/>}
      <section className={`an-pane ${session.activePane===pane.id?'active':''}`} style={{flex: session.collapsed||session.panes.length===1?'1 1 0':`${index===0?session.ratio:100-session.ratio} 1 0`}} aria-label={`Pane ${pane.id.toUpperCase()}`} onFocusCapture={()=>{if(session.activePane!==pane.id)patchSession({activePane:pane.id});}}>
        {!focus&&<div className="an-tabs"><div role="tablist" aria-label={`Pane ${pane.id.toUpperCase()} tabs`}>{pane.tabs.map(t=><div className="an-tab-group" key={t.id}><button role="tab" aria-selected={t.id===pane.active} id={`an-tab-${t.id}`} aria-controls={`an-panel-${pane.id}`} onClick={()=>patchSession({activePane:pane.id,panes:session.panes.map(p=>p.id===pane.id?{...p,active:t.id}:p)})}>{t.layer==='notebook'?ownerTitle:t.title}</button><button aria-label={`Close ${t.title} in pane ${pane.id.toUpperCase()}`} onClick={()=>safe(()=>commit({...project,session:closeTab(session,pane.id,t.id)}))}>x</button></div>)}</div><button className="an-add-tab" aria-label={`New tab in pane ${pane.id.toUpperCase()}`} onClick={()=>setNewTabPane(newTabPane===pane.id?null:pane.id)}>+</button>{session.panes.length===2&&<><button className="an-small-action" disabled={!tab} aria-label={`Move active tab from pane ${pane.id.toUpperCase()}`} title="Move tab to other pane" onClick={()=>safe(()=>commit({...project,session:moveTab(session,pane.id,pane.active)}))}>Move</button><button className="an-small-action" aria-label={`Collapse pane ${pane.id.toUpperCase()}`} onClick={()=>patchSession({collapsed:pane.id,activePane:pane.id==='a'?'b':'a'})}>Hide</button></>}</div>}
        {newTabPane===pane.id&&<div className="an-tab-picker" aria-label="Choose new view">{LAYERS.map(l=><button key={l.id} onClick={()=>select(l.id,pane.id)}><b>{l.label}</b><small>{l.description}</small></button>)}</div>}
        <div className="an-pane-content" role="tabpanel" id={`an-panel-${pane.id}`} aria-labelledby={tab?`an-tab-${tab.id}`:undefined}>{tab?layerContent(tab.layer,pane):<div className="an-empty"><span className="an-empty-mark">+</span><h3>Your next view</h3><p>Open a notebook, dbt source, model or chart here. No data is copied.</p><div className="an-empty-tools">{LAYERS.slice(0,6).map(l=><button key={l.id} onClick={()=>select(l.id,pane.id)}>{l.label}</button>)}</div></div>}</div>
      </section></React.Fragment>;})}
    </div>
    {session.contextOpen&&!focus&&<aside className="an-context" aria-label="Analytics context"><div className="an-sidebar-title"><b>Context</b><button aria-label="Collapse analytics context" onClick={()=>patchSession({contextOpen:false})}>x</button></div><span className="an-badge">{currentLayer==='notebook'?'Notebook runtime below':currentLayer==='scd'?'Local teaching model':'No live execution'}</span><h3>{LAYERS.find(l=>l.id===currentLayer)?.label??'Empty pane'}</h3><p>{LAYERS.find(l=>l.id===currentLayer)?.description}</p><dl><dt>Owner notebook</dt><dd>{ownerTitle}</dd><dt>Source files</dt><dd>{project.files.length}</dd><dt>Declared model tables</dt><dd>{project.model.tables.length}</dd><dt>dbt artifacts</dt><dd>{project.artifacts?`${project.artifacts.nodes.length} imported nodes`:'Not imported'}</dd><dt>Runner</dt><dd>Not connected to analytics layer</dd></dl><p>Show, hide and rearrange views without changing execution order. Schema relationships are designs; imported build evidence is historical.</p><button onClick={()=>select('connections')}>Runtime & setup</button></aside>}
    </div>
    {!focus&&<footer className="an-status"><span>{preview?'UI-only preview':'Notebook-attached analytics'} / no automatic cloud requests</span><span>Revision {project.revision} / {session.panes.length} pane{session.panes.length>1?'s':''} / {session.theme}</span></footer>}
    {palette&&<div className="an-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setPalette(false);}}><section className="an-palette" role="dialog" aria-modal="true" aria-label="Find workspace view" onKeyDown={e=>{if(e.key==='Tab'){const controls=e.currentTarget.querySelectorAll<HTMLElement>('input,button');const first=controls[0],last=controls[controls.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}}><input autoFocus aria-label="Search workspace views" placeholder="Search views, or type a model filename..." value={search} onChange={e=>setSearch(e.target.value)}/>{LAYERS.filter(l=>`${l.label} ${l.description}`.toLowerCase().includes(search.toLowerCase())).map(l=><button key={l.id} onClick={()=>select(l.id)}><b>{l.label}</b><small>{l.description}</small></button>)}{search.length>1&&project.files.filter(f=>f.path.toLowerCase().includes(search.toLowerCase())).slice(0,8).map(f=><button key={f.path} onClick={()=>safe(()=>{commit({...project,selectedFile:f.path,session:openLayer(session,'dbt')});setPalette(false);})}><b>{f.path}</b><small>dbt source file</small></button>)}<button onClick={()=>setPalette(false)}>Close / Esc</button></section></div>}
  </div>;
}
