import * as React from 'react';
import type {LabProps} from './DbtStudio';
import type {Board} from './types';
import {aggregateBoard, boardYaml, importBoardYaml, importRows, sampleBoard, snapshotFreshness} from './charts';
import {FileImport, RowsTable, SourceEditor, Title, downloadText} from './controls';
const fmt = (n: number) => new Intl.NumberFormat('en-US', {maximumFractionDigits: 2}).format(n);
export function ChartsStudio({project,onChange,onError,catalogInputs}:LabProps) {
  const [tab,setTab]=React.useState('visual'); const board=project.board;
  const set=(patch:Partial<Board>)=>onChange({...project,board:{...board,...patch}});
  const safe=(f:()=>void)=>{try{f();}catch(e){onError(String(e));}};
  let problem=''; let data:ReturnType<typeof aggregateBoard>={points:[],total:0,ignored:0,stale:false,groups:0};
  try{data=aggregateBoard(board);}catch(e){problem=String(e);}
  const freshness=snapshotFreshness(board.snapshot,catalogInputs);if(freshness.state==='stale')data={...data,stale:true};
  const points=data.points; const lo=Math.min(0,...points.map(p=>p.value)),hi=Math.max(1,...points.map(p=>p.value)),range=hi-lo;
  const py=(value:number)=>250-(value-lo)/range*205, zero=py(0); const width=690,pad=60,plot=width-pad-20;
  return <section className="an-layer"><Title eyebrow="BI / SQL TO BOARD" title="Charts"><span className="an-badge">{board.snapshot.origin==='sample'?'Sample result snapshot':board.snapshot.origin==='real_local'?'Verified local query snapshot':'Imported result snapshot'}</span></Title><p className="an-lead">Shape a board from result rows. Export dbt Charts YAML for the actual <code>dct</code> renderer; this visual preview is native Datapass.</p>
  <div className="an-actions"><FileImport label="Import dbt Charts YAML" accept=".yml,.yaml" limit={100_000} onError={onError} onRead={text=>safe(()=>onChange({...project,board:importBoardYaml(text)}))}/><FileImport label="Import result JSON" limit={2_000_000} onError={onError} onRead={text=>safe(()=>{const snapshot=importRows(text,board.query);set({snapshot,x:snapshot.columns.includes(board.x)?board.x:snapshot.columns[0]??'',y:snapshot.columns.includes(board.y)?board.y:snapshot.columns.find(c=>snapshot.rows.some(r=>typeof r[c]==='number'))??snapshot.columns[1]??''});})}/><button onClick={()=>safe(()=>downloadText('revenue.yml',boardYaml(board),'application/yaml'))}>Export dbt Charts YAML</button><button onClick={()=>downloadText('chart-rows.json',JSON.stringify(board.snapshot.rows,null,2),'application/json')}>Export result rows</button><button onClick={()=>{if(window.confirm('Replace this board with the sample board? Notebook source is unchanged.'))onChange({...project,board:sampleBoard()});}}>Reset sample board</button></div>
  <div className="an-subtabs" role="tablist" aria-label="Chart views">{[['visual','Board'],['sql','SQL & provenance'],['yaml','dbt Charts YAML'],['rows','Data snapshot']].map(([id,label])=><button role="tab" aria-selected={tab===id} key={id} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {tab==='visual'&&<><div className="an-chart-controls"><label>Title<input aria-label="Board title" value={board.title} maxLength={120} onChange={e=>set({title:e.target.value})}/></label><label>Chart<select aria-label="Chart type" value={board.chartType} onChange={e=>set({chartType:e.target.value as Board['chartType']})}><option value="bar">Bar</option><option value="line">Line</option><option value="kpi">KPI</option><option value="table">Table</option></select></label><label>Group by<select aria-label="Chart dimension" value={board.x} onChange={e=>set({x:e.target.value})}>{board.snapshot.columns.map(c=><option key={c}>{c}</option>)}</select></label><label>Measure<select aria-label="Chart measure" disabled={board.aggregation==='count'} value={board.y} onChange={e=>set({y:e.target.value})}>{board.snapshot.columns.map(c=><option key={c}>{c}</option>)}</select></label><label>Aggregate<select aria-label="Chart aggregation" value={board.aggregation} onChange={e=>set({aggregation:e.target.value as Board['aggregation']})}><option value="sum">Sum</option><option value="mean">Mean</option><option value="count">Row count</option></select></label></div>
  <div className="an-board"><div className="an-board-title"><div><small>{board.snapshot.origin==='sample'?'TEACHING FIXTURE':board.snapshot.origin==='real_local'?'LOCAL QUERY RESULT':'USER-SUPPLIED ROWS'}</small><h3>{board.title}</h3></div><span className="an-badge">{board.snapshot.rows.length} input rows</span></div>
  {problem?<div role="alert" className="an-warning">{problem}</div>:data.stale?<div className="an-empty"><h3>Query or registered inputs changed. This snapshot is stale.</h3><p>{freshness.message}</p><p>Run SQL for the new query and apply its result, import fresh rows, or restore the exact snapshot query.</p></div>:!points.length?<div className="an-empty">No compatible values. Choose a dimension and a numeric measure, or use Row count.</div>:board.chartType==='kpi'?<div className="an-kpi"><b>{fmt(data.total)}</b><span>{board.aggregation==='mean'?'Mean over all non-null numeric rows':board.aggregation==='count'?'Row count':'Sum over all numeric rows'}</span></div>:board.chartType==='table'?<RowsTable label="Aggregated chart data" columns={['dimension','metric']} rows={points.map(p=>({dimension:p.label,metric:p.value}))}/>:<svg className="an-chart-svg" viewBox={`0 0 ${width} 305`} role="img" aria-label={`${board.title}, ${board.chartType} chart, ${data.groups} groups; data table is available below`}>
  {[0,1,2,3,4].map(i=>{const value=lo+range*i/4; return <g className="an-chart-grid" key={i}><line x1={pad} y1={py(value)} x2={width-20} y2={py(value)}/><text x={pad-8} y={py(value)+4} textAnchor="end">{fmt(value)}</text></g>;})}<line className="an-zero-line" x1={pad} x2={width-20} y1={zero} y2={zero}/>
  {board.chartType==='line'&&<polyline className="an-trend" points={points.map((p,i)=>`${pad+(i+.5)*plot/points.length},${py(p.value)}`).join(' ')}/>}
  {points.map((p,i)=>{const slot=plot/points.length,x=pad+(i+.5)*slot;return <g key={i}>{board.chartType==='bar'?<rect className="an-bar" x={x-slot*.3} width={Math.max(1,slot*.6)} y={Math.min(py(p.value),zero)} height={Math.max(1,Math.abs(py(p.value)-zero))} rx="4"><title>{p.label}: {fmt(p.value)}</title></rect>:<circle className="an-point" cx={x} cy={py(p.value)} r="4"><title>{p.label}: {fmt(p.value)}</title></circle>}{points.length<=12&&<><text className="an-chart-value" x={x} y={py(p.value)+(p.value>=0?-10:16)} textAnchor="middle">{fmt(p.value)}</text><text className="an-chart-label" x={x} y={280} textAnchor="middle">{p.label.length>15?p.label.slice(0,13)+'...':p.label}</text></>}</g>;})}</svg>}
  <p className="an-muted">{data.ignored?`${data.ignored} rows have non-numeric/null measures and were ignored. `:''}{data.groups>80?'First 80 groups shown; KPI totals use all rows. ':''}{board.snapshot.origin==='real_local'?`Rows verified against local run ${board.snapshot.run_id}. Native Datapass visualization, not the dbt Charts renderer.`:'No live database query or dbt Charts rendering happened in this preview.'}</p></div>
  <details><summary>Accessible aggregated data</summary><RowsTable label="Chart accessible data" columns={['dimension','metric']} rows={data.stale?[]:points.map(p=>({dimension:p.label,metric:p.value}))}/></details></>}
  {tab==='sql'&&<><div className="an-note">Editing SQL invalidates the displayed result, but does not run a query. Use the shared-catalog Run SQL action, or import externally produced JSON rows.</div><SourceEditor label="Board SQL query" source={board.query} onChange={query=>{if(query.length<=100_000)set({query});else onError('Query exceeds 100 KB.');}}/><button onClick={()=>set({query:board.snapshot.query})}>Restore snapshot query</button><div className="an-card"><h3>Snapshot provenance</h3><p>Origin: {board.snapshot.origin}. {board.snapshot.importedAt?`Imported at ${board.snapshot.importedAt}.`:''} {board.snapshot.origin==='real_local'?`Verified local run ${board.snapshot.run_id} in workspace ${board.snapshot.workspace_id}.`:'Import assigns your current SQL text as the snapshot label; Datapass cannot independently verify that those rows came from this query.'}</p><p>{freshness.message}</p><pre>{board.snapshot.query}</pre></div></>}
  {tab==='yaml'&&<><p className="an-note">Single-chart SQL YAML interoperability (source: db; bar, line, KPI and dimension/metric table). Import rejects unsupported options and clears result evidence. A dbt Charts board definition, not a compiled dashboard. Run <code>dct validate charts/revenue.yml</code> in the exported sample project. The real renderer and adapters are optional Python dependencies, not bundled into this UI.</p><SourceEditor label="dbt Charts YAML" source={boardYaml(board)} language="yaml" readOnly onChange={()=>{}}/></>}
  {tab==='rows'&&<RowsTable label="Chart input snapshot" columns={board.snapshot.columns} rows={board.snapshot.rows}/>}
  </section>;
}
