import * as React from 'react';
import type {Graph, LabProject} from './types';
import {attachRunResults, draftGraph, graphLevels, importManifest, manifestGraph, relatedNodes} from './dbt';
import {sourcePath} from './validation';
import {updateFile} from './project';
import {FileImport, SourceEditor, Title, downloadText, RowsTable} from './controls';
export interface LabProps {project: LabProject; onChange: (project: LabProject) => void; onError: (message: string) => void; evidence?:{bundle:import('./types').ArtifactBundle;runId:string;resourceRevision:number;stale:boolean};nativeRunner?:boolean;catalogInputs?:Array<{name:string;version?:string;fresh:boolean}>}
export function DbtStudio({project, onChange, onError, evidence, nativeRunner}: LabProps) {
  const [tab, setTab] = React.useState('source'), [newPath, setNewPath] = React.useState('models/marts/my_model.sql');
  const [search, setSearch] = React.useState('');
  const file = project.files.find(f => f.path === project.selectedFile) ?? project.files[0];
  const artifact=evidence?.bundle??project.artifacts;
  const imported = artifact?.nodes.find(n => n.path === file?.path);
  const results = artifact?.results ?? [];
  const safe = (action: () => void) => {try {action();} catch(e) {onError(String(e));}};
  return <section className="an-layer"><Title eyebrow="TRANSFORM / ARTIFACT-FIRST" title="dbt Studio"><span className="an-badge">{evidence?"Verified local invocation":nativeRunner?"Workspace dbt project":"Runner not connected"}</span></Title>
    <p className="an-lead">Author SQL and YAML. Explicit local runs and imported artifacts remain separate evidence sources.</p>
    <div className="an-actions"><FileImport label="Import manifest.json" onError={onError} onRead={text => safe(() => onChange({...project, artifacts: importManifest(text)}))}/><FileImport label="Import run_results.json" onError={onError} onRead={text => safe(() => {if (!project.artifacts) throw new Error('Import the matching manifest first.'); onChange({...project, artifacts: attachRunResults(project.artifacts, text)});})}/>{!nativeRunner&&<button disabled title="Use the optional local CLI from the ZIP; no cloud runner is connected.">Run dbt build</button>}<button onClick={() => downloadText('datapass-dbt-source.json', JSON.stringify({schemaVersion: 1, files: project.files}, null, 2), 'application/json')}>Export project sources</button></div>
    <div className="an-dbt-layout"><aside className="an-files"><input aria-label="Filter dbt files" placeholder="Find a model, test or seed..." value={search} onChange={e => setSearch(e.target.value)}/><div className="an-file-tree">{project.files.filter(f => f.path.toLowerCase().includes(search.toLowerCase())).map(f => <button key={f.path} className={f.path === file?.path ? 'selected' : ''} onClick={() => {onChange({...project, selectedFile: f.path}); setTab('source');}}><span className="an-file-kind">{f.path.endsWith('.sql') ? 'SQL' : f.path.endsWith('.csv') ? 'CSV' : 'YML'}</span><span>{f.path.split('/').pop()}<small>{f.path.split('/').slice(0, -1).join('/') || 'project'}</small></span></button>)}</div><details><summary>Add source file</summary><input aria-label="New dbt file path" value={newPath} onChange={e => setNewPath(e.target.value)} maxLength={220}/><button onClick={() => safe(() => {const path = sourcePath(newPath); if (project.files.some(f => f.path === path)) throw new Error('This path already exists.'); if (project.files.length >= 60) throw new Error('Project file limit reached.'); onChange({...project, files: [...project.files, {path, source: path.endsWith('.sql') ? "select * from {{ ref('stg_orders') }}\n" : ''}], selectedFile: path});})}>Create file</button></details></aside>
    <div className="an-dbt-editor"><div className="an-subtabs" role="tablist" aria-label="dbt detail"><button role="tab" aria-selected={tab === 'source'} onClick={() => setTab('source')}>Source</button><button role="tab" aria-selected={tab === 'compiled'} onClick={() => setTab('compiled')}>Compiled SQL</button><button role="tab" aria-selected={tab === 'results'} onClick={() => setTab('results')}>Build evidence {results.length ? `(${results.length})` : ''}</button></div>
    {tab === 'source' && file && <><div className="an-file-heading"><code>{file.path}</code><button onClick={() => downloadText(file.path.split('/').pop()!, file.source)}>Download file</button></div><SourceEditor source={file.source} label="dbt source editor" language={file.path.endsWith('.sql') ? 'sql' : 'yaml'} onChange={source => safe(() => onChange(updateFile(project, file.path, source)))}/><div className="an-note">Saving a draft does not compile Jinja or run a model. Use an explicit local action after reviewing the project.</div></>}
    {tab === 'compiled' && (imported?.compiled ? <><div className="an-warning">{evidence?`Compiled SQL from local run ${evidence.runId}, resource revision ${evidence.resourceRevision}${evidence.stale?" (stale relative to this draft)":""}.`:"Historical compiled SQL from the imported manifest. It is not recompiled when you edit the draft."}</div><SourceEditor label={evidence?"Local dbt compiled SQL":"Imported compiled SQL"} source={imported.compiled} onChange={() => {}} readOnly/></> : <div className="an-empty"><h3>No compiled SQL for this file</h3><p>Import a manifest generated by a dbt invocation that includes compiled code. Parsing alone may not populate it.</p></div>)}
    {tab === 'results' && <><div className="an-note">{artifact ? `${evidence?'Local':'Imported'} project: ${artifact.projectName || 'unnamed'} / generated ${artifact.generatedAt || 'unknown'} / invocation ${artifact.invocationId || 'unknown'}` : 'No artifact imported. No successful build is assumed.'}</div><RowsTable label={evidence?"Local dbt results":"Imported dbt results"} rows={results.map(r => ({node: r.id, status: r.status, elapsed_seconds: r.seconds, failures: r.failures, message: r.message}))}/><p className="an-muted">{evidence?`Authenticated artifact files for local run ${evidence.runId}. ${evidence.stale?"The draft has changed since that source checkpoint.":""}`:"Imported evidence is historical and user-supplied, not an authenticated execution by Datapass."} Manifest and run-results must share a nonempty invocation ID.</p></>}
    </div></div>
  </section>;
}
function GraphView({graph}: {graph: Graph}) {
  const [selected, setSelected] = React.useState(''), [direction, setDirection] = React.useState<'all' | 'upstream' | 'downstream'>('all'), [zoom, setZoom] = React.useState(100);
  const levels = graphLevels(graph), slots = new Map<number, number>();
  const positions = new Map(graph.nodes.map(n => {const level = levels.get(n.id) ?? 0, row = slots.get(level) ?? 0; slots.set(level, row + 1); return [n.id, {x: 30 + level * 250, y: 35 + row * 122}];}));
  const active = selected && graph.nodes.some(n => n.id === selected) ? selected : '';
  const visible = direction === 'all' || !active ? new Set(graph.nodes.map(n => n.id)) : relatedNodes(graph, active, direction); visible.add(active);
  const width = Math.max(780, ...[...positions.values()].map(p => p.x + 230)), height = Math.max(370, ...[...positions.values()].map(p => p.y + 130));
  const node = graph.nodes.find(n => n.id === active);
  return <><div className="an-actions"><label>Impact <select aria-label="Lineage direction" value={direction} onChange={e => setDirection(e.target.value as typeof direction)}><option value="all">All models</option><option value="upstream">Upstream of selected</option><option value="downstream">Downstream of selected</option></select></label><label>Zoom <input aria-label="Lineage zoom" type="range" min={50} max={130} value={zoom} onChange={e => setZoom(Number(e.target.value))}/></label><small>{graph.nodes.length} nodes / {graph.edges.length} dependencies</small></div>
  <div className="an-graph-scroll"><div className="an-graph" style={{width: width * zoom / 100, height: height * zoom / 100}}><div style={{transform: `scale(${zoom / 100})`, transformOrigin: '0 0', width, height}}><svg width={width} height={height} aria-hidden="true">{graph.edges.map(e => {const a = positions.get(e.from), b = positions.get(e.to); if (!a || !b) return null; const shown = visible.has(e.from) && visible.has(e.to); return <g key={e.id} className={shown ? '' : 'an-dim'}><path d={`M${a.x + 202},${a.y + 38} C${a.x + 225},${a.y + 38} ${b.x - 25},${b.y + 38} ${b.x - 6},${b.y + 38}`}/><path className="an-arrow" d={`M${b.x - 12},${b.y + 34} L${b.x - 6},${b.y + 38} L${b.x - 12},${b.y + 42}`}/></g>;})}</svg>{graph.nodes.map(n => {const p = positions.get(n.id)!; return <button key={n.id} className={`an-node ${n.kind} ${selected === n.id ? 'selected' : ''} ${visible.has(n.id) ? '' : 'an-dim'}`} style={{left: p.x, top: p.y}} onClick={() => setSelected(n.id)}><span>{n.kind}</span><b>{n.label}</b><small>{n.detail || 'Dependency reference'}</small></button>;})}</div></div></div>
  {node && <div className="an-selection"><b>{node.label}</b><code>{node.id}</code><span>{graph.edges.filter(e => e.to === node.id).length} direct inputs / {graph.edges.filter(e => e.from === node.id).length} direct dependents</span></div>}</>;
}
export function LineageStudio({project,evidence}: LabProps) {
  const [source, setSource] = React.useState<'draft' | 'manifest'>('draft'), [tests, setTests] = React.useState(false);
  const artifact=evidence?.bundle??project.artifacts;
  const graph = source === 'manifest' && artifact ? manifestGraph(artifact, tests) : draftGraph(project.files);
  return <section className="an-layer"><Title eyebrow="DEPENDENCIES / CHANGE IMPACT" title="Lineage"><span className="an-badge">{graph.origin === 'imported-manifest' ? (evidence?'Verified local manifest':'Imported manifest') : 'Draft references only'}</span></Title><p className="an-lead">Follow transformations from seeds to models. Select a model to explore its upstream inputs or downstream dependents.</p>
  <div className="an-actions"><button className={source === 'draft' ? 'selected' : ''} onClick={() => setSource('draft')}>Draft references</button><button className={source === 'manifest' ? 'selected' : ''} disabled={!artifact} onClick={() => setSource('manifest')}>{evidence?"Local manifest":"Imported manifest"}</button>{source === 'manifest' && <label><input type="checkbox" checked={tests} onChange={e => setTests(e.target.checked)}/> Include dbt tests</label>}</div>
  <GraphView graph={graph}/><div className="an-note">{graph.origin === 'draft-reference-scan' ? 'Conservative literal ref()/source() scan, not a dbt compiler or general SQL parser. Macro-generated dependencies may be missing. Import a manifest for dbt-resolved model dependencies.' : `Model-level dependencies from ${evidence?'a verified local':'an imported'} dbt manifest. This is not automatic column-level SQL lineage.`} Authored column mappings live in Data model.</div>
  {!!graph.warnings.length && <details className="an-warning"><summary>{graph.warnings.length} reference warnings</summary>{graph.warnings.map((w, i) => <p key={i}>{w}</p>)}</details>}</section>;
}
