import * as React from 'react';
import type {ModelTable, Relationship} from './types';
import type {LabProps} from './DbtStudio';
import {addRelationship, CHANGE_EVENTS, DATA_TYPES, ddlPreview, lookupAt, modelChecks, newTable, removeTable, replayScd, scdExerciseAnswer} from './modeling';
import {freshId, identifier} from './validation';
import {RowsTable, SourceEditor, Title, downloadText} from './controls';
export function ModelStudio({project, onChange, onError}: LabProps) {
  const [selected, setSelected] = React.useState('sales'), [mode, setMode] = React.useState('diagram');
  const [newName, setNewName] = React.useState('dim_product'), [from, setFrom] = React.useState(JSON.stringify(['sales','s-customer'])), [to, setTo] = React.useState(JSON.stringify(['customers','c-key']));
  const [cardinality, setCardinality] = React.useState<Relationship['cardinality']>('many-to-one'), [expression, setExpression] = React.useState('Join by business key');
  const drag = React.useRef<{pointer: number; x: number; y: number; startX: number; startY: number} | null>(null);
  const model = project.model, table = model.tables.find(t => t.id === selected), checks = modelChecks(model);
  const safe = (action: () => void) => {try {action();} catch(e) {onError(String(e));}};
  const changeTable = (next: ModelTable) => onChange({...project, model: {...model, tables: model.tables.map(t => t.id === next.id ? next : t)}});
  const endpoint = (pair: string) => {const [table, column] = JSON.parse(pair) as [string,string]; return {table, column};};
  const relation = () => {const a = endpoint(from), b = endpoint(to); return {fromTable: a.table, fromColumn: a.column, toTable: b.table, toColumn: b.column, cardinality};};
  const options = model.tables.flatMap(t => t.columns.map(c => <option key={JSON.stringify([t.id,c.id])} value={JSON.stringify([t.id,c.id])}>{t.name}.{c.name}</option>));
  let ddl = ''; try {ddl = ddlPreview(model);} catch(e) {ddl = `-- Correct the schema design before exporting: ${String(e)}`;}
  const label = (tableId: string, colId: string) => {const t = model.tables.find(t => t.id === tableId); return `${t?.name}.${t?.columns.find(c => c.id === colId)?.name}`;};
  return <section className="an-layer"><Title eyebrow="MODEL / SCHEMA DESIGN" title="Facts, dimensions & keys"><span className="an-badge">Authored design</span></Title><p className="an-lead">Declare the grain, connect columns and reason about cardinality. A relationship here never alters a real database.</p>
    <div className="an-actions"><button className={mode === 'diagram' ? 'selected' : ''} onClick={() => setMode('diagram')}>Schema</button><button className={mode === 'columns' ? 'selected' : ''} onClick={() => setMode('columns')}>Column mappings</button><button className={mode === 'ddl' ? 'selected' : ''} onClick={() => setMode('ddl')}>DDL preview</button><input aria-label="New table name" value={newName} maxLength={60} onChange={e => setNewName(e.target.value)}/><button onClick={() => safe(() => {if (model.tables.length >= 30) throw new Error('Maximum 30 design tables.'); if (model.tables.some(t => t.name === newName)) throw new Error('Table name already exists.'); const t = newTable(newName); onChange({...project, model: {...model, tables: [...model.tables, t]}}); setSelected(t.id);})}>Add table</button></div>
    {mode === 'diagram' && <div className="an-model-layout"><div className="an-model-scroll"><div className="an-model-board" style={{width: Math.max(1030, ...model.tables.map(t => t.x + 290)), height: Math.max(620, ...model.tables.map(t => t.y + 130 + t.columns.length * 30))}}>
      <svg width="100%" height="100%" aria-hidden="true">{model.relationships.map(r => {const a = model.tables.find(t => t.id === r.fromTable), b = model.tables.find(t => t.id === r.toTable); if (!a || !b) return null; const ay = a.y + 50 + a.columns.findIndex(c => c.id === r.fromColumn) * 30 + 16, by = b.y + 50 + b.columns.findIndex(c => c.id === r.toColumn) * 30 + 16; const right = a.x < b.x, x1 = a.x + (right ? 250 : 0), x2 = b.x + (right ? 0 : 250); return <g key={r.id}><path d={`M ${x1} ${ay} C ${(x1+x2)/2} ${ay} ${(x1+x2)/2} ${by} ${x2} ${by}`}/><text x={(x1+x2)/2} y={(ay+by)/2-8}>{r.cardinality === 'many-to-one' ? '* : 1' : r.cardinality === 'one-to-one' ? '1 : 1' : '* : *'}</text></g>;})}</svg>
      {model.tables.map(t => <article key={t.id} className={`an-model-table ${t.role} ${selected === t.id ? 'selected' : ''}`} style={{left: t.x, top: t.y}}><button className="an-model-handle" aria-label={`Select or move ${t.name}`} onClick={() => setSelected(t.id)} onPointerDown={e => {if (e.button !== 0) return; setSelected(t.id); drag.current = {pointer: e.pointerId, x: e.clientX, y: e.clientY, startX: t.x, startY: t.y}; e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e => {const d = drag.current; if (!d || d.pointer !== e.pointerId) return; changeTable({...t, x: Math.max(0, Math.min(2400, d.startX + e.clientX - d.x)), y: Math.max(0, Math.min(2400, d.startY + e.clientY - d.y))});}} onPointerUp={() => {drag.current = null;}} onPointerCancel={() => {drag.current = null;}} onLostPointerCapture={() => {drag.current = null;}} onKeyDown={e => {if (!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)) return; e.preventDefault(); changeTable({...t, x: Math.max(0, Math.min(2400,t.x + (e.key === 'ArrowLeft' ? -20 : e.key === 'ArrowRight' ? 20 : 0))), y: Math.max(0,Math.min(2400,t.y + (e.key === 'ArrowUp' ? -20 : e.key === 'ArrowDown' ? 20 : 0)))});}}><b>{t.name}</b><small>{t.role}</small></button>{t.columns.map(c => <div className="an-model-column" key={c.id}><span className={c.primary ? 'an-pk' : ''}>{c.primary ? 'PK' : model.relationships.some(r => r.fromTable === t.id && r.fromColumn === c.id) ? 'FK' : ''}</span><b>{c.name}</b><small>{c.type}</small></div>)}<p>{t.grain || 'Define the grain'}</p></article>)}</div></div>
      <aside className="an-model-properties">{table ? <><h3>Table properties</h3><label>Name<input aria-label="Selected table name" value={table.name} maxLength={60} onChange={e => {if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(e.target.value)) changeTable({...table, name: e.target.value});}}/></label><label>Role<select aria-label="Table role" value={table.role} onChange={e => changeTable({...table, role: e.target.value as ModelTable['role']})}><option value="fact">Fact</option><option value="dimension">Dimension</option><option value="source">Source</option></select></label><label>Grain<textarea aria-label="Table grain" maxLength={500} value={table.grain} onChange={e => changeTable({...table, grain: e.target.value})}/></label><h4>Columns</h4>{table.columns.map(c => <div className="an-column-edit" key={c.id}><input aria-label={`Name of ${c.name}`} value={c.name} maxLength={60} onChange={e => {if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(e.target.value)) changeTable({...table, columns: table.columns.map(x => x.id === c.id ? {...c, name: e.target.value} : x)});}}/><select aria-label={`Type of ${c.name}`} value={c.type} onChange={e => changeTable({...table, columns: table.columns.map(x => x.id === c.id ? {...c,type: e.target.value} : x)})}>{DATA_TYPES.map(t => <option key={t}>{t}</option>)}</select><label><input type="checkbox" checked={c.primary} onChange={e => changeTable({...table, columns: table.columns.map(x => x.id === c.id ? {...c,primary: e.target.checked,nullable: e.target.checked ? false : c.nullable} : x)})}/> PK</label><label><input type="checkbox" checked={c.nullable} onChange={e => changeTable({...table, columns: table.columns.map(x => x.id === c.id ? {...c,nullable: e.target.checked} : x)})}/> Nullable</label></div>)}<button onClick={() => safe(() => {if (table.columns.length >= 60) throw new Error('Maximum 60 columns per table.'); let i = table.columns.length + 1; while (table.columns.some(c => c.name === `column_${i}`)) i++; changeTable({...table, columns: [...table.columns, {id: freshId('column'),name:`column_${i}`,type:'VARCHAR',primary:false,nullable:true}]});})}>Add column</button><button className="an-danger" onClick={() => {if (window.confirm(`Remove ${table.name} and its design relationships? No real data will be deleted.`)) {onChange({...project,model:removeTable(model,table.id)}); setSelected('');}}}>Remove design table</button></> : <p>Select a table to edit columns and grain. Drag its title or use arrow keys to arrange it.</p>}</aside></div>}
    {mode === 'ddl' && <><button onClick={() => safe(() => downloadText('schema-design.sql', ddlPreview(model)))}>Export DDL</button><SourceEditor label="Schema DDL preview" source={ddl} language="sql" readOnly onChange={() => {}}/></>}
    <div className="an-card"><h3>{mode === 'columns' ? 'Authored column lineage' : 'Relationship designer'}</h3><div className="an-actions"><label>From<select aria-label="Relationship from" value={from} onChange={e => setFrom(e.target.value)}>{options}</select></label><label>To<select aria-label="Relationship to" value={to} onChange={e => setTo(e.target.value)}>{options}</select></label>{mode === 'columns' ? <input aria-label="Column mapping expression" maxLength={1000} value={expression} onChange={e => setExpression(e.target.value)}/> : <select aria-label="Cardinality" value={cardinality} onChange={e => setCardinality(e.target.value as Relationship['cardinality'])}><option value="many-to-one">Many to one (* : 1)</option><option value="one-to-one">One to one (1 : 1)</option><option value="many-to-many">Many to many (* : *)</option></select>}<button onClick={() => safe(() => {if (mode === 'columns') {if (model.mappings.length >= 200) throw new Error('Maximum 200 column mappings.'); const r = relation(); for(const [ti,ci] of [[r.fromTable,r.fromColumn],[r.toTable,r.toColumn]]) if (!model.tables.find(t=>t.id===ti)?.columns.some(c=>c.id===ci)) throw new Error('Select existing endpoints.'); onChange({...project, model:{...model,mappings:[...model.mappings,{...r,id:freshId('mapping'),expression}]}});} else {if (model.relationships.length >= 120) throw new Error('Maximum 120 relationships.'); onChange({...project,model:addRelationship(model,relation())});}})}>{mode === 'columns' ? 'Add mapping' : 'Add relationship'}</button></div>
    {(mode === 'columns' ? model.mappings : model.relationships).map(r => <div className="an-relationship" key={r.id}><code>{label(r.fromTable,r.fromColumn)}</code><span>to</span><code>{label(r.toTable,r.toColumn)}</code><small>{'expression' in r ? r.expression : r.cardinality}</small><button aria-label={`Remove ${r.id}`} onClick={() => onChange({...project,model:{...model,...(mode==='columns'?{mappings:model.mappings.filter(x=>x.id!==r.id)}:{relationships:model.relationships.filter(x=>x.id!==r.id)})}})}>Remove</button></div>)}<small>{mode === 'columns' ? 'These mappings are authored explanations, not SQL-parser-derived column lineage. Expressions are text, never executed.' : 'Cardinality is a design declaration. Key uniqueness and referential integrity require data checks when a runtime is connected.'}</small></div>
    <details className="an-card" open={checks.some(c=>c.severity==='error')}><summary>Design review / {checks.length} findings</summary>{checks.length ? checks.map(c=><p className={c.severity==='error'?'an-error-text':''} key={c.id}><b>{c.severity.toUpperCase()}</b> {c.message}</p>):<p>No structural design warnings. This does not prove anything about actual table contents.</p>}</details>
  </section>;
}
export function ScdStudio({project,onChange}:LabProps) {
  const {type,step,answer}=project.scd;
  const [checked,setChecked]=React.useState(false),[asOf,setAsOf]=React.useState('2026-02-15');
  const rows=replayScd(CHANGE_EVENTS,type,step), result=scdExerciseAnswer(type,step), at=type===2?lookupAt(rows,101,asOf):undefined;
  const update=(patch:Partial<LabProps['project']['scd']>)=>{setChecked(false);onChange({...project,scd:{...project.scd,...patch}});};
  const columns=type===2?['customer_key','customer_id','name','city','valid_from','valid_to','is_current']:type===3?['customer_key','customer_id','name','city','previous_city']:['customer_key','customer_id','name','city'];
  return <section className="an-layer"><Title eyebrow="DIMENSIONAL MODELING / GUIDED EXERCISE" title="Slowly changing dimensions"><span className="an-badge">Deterministic teaching model</span></Title><p className="an-lead">The same customer moves from Geneva to Oslo to Trondheim. Compare what each dimension strategy retains.</p>
  <div className="an-scd-types">{([1,2,3] as const).map(t=><button key={t} className={t===type?'selected':''} onClick={()=>update({type:t})}><b>Type {t}</b><span>{t===1?'Overwrite the value':t===2?'Add a historical version':'Keep the previous value'}</span></button>)}</div>
  <div className="an-actions"><button disabled={step===0} onClick={()=>update({step:step-1})}>Previous event</button><input aria-label="SCD event step" type="range" min={0} max={CHANGE_EVENTS.length} value={step} onChange={e=>update({step:Number(e.target.value)})}/><b>{step} / {CHANGE_EVENTS.length} events</b><button disabled={step===CHANGE_EVENTS.length} onClick={()=>update({step:step+1})}>Next event</button><button onClick={()=>update({step:0,answer:''})}>Reset replay</button></div>
  <div className="an-events">{CHANGE_EVENTS.map((e,i)=><button key={i} className={i<step?'applied':''} onClick={()=>update({step:i+1})}><small>{e.at}</small><b>{e.name}</b><span>{e.city}</span><em>{i===3?'Unchanged city':i<2?'New customer':'City changed'}</em></button>)}</div>
  <div className="an-card"><h3>Dimension after event {step}</h3><RowsTable label="SCD dimension rows" columns={columns} rows={rows.map(r=>({...r}))}/><p className="an-note">{result.explanation}{type===2?' Validity uses [valid_from, valid_to): inclusive start, exclusive end. A new version gets a new surrogate key.':''}</p></div>
  {type===2 && <div className="an-card"><h3>Historical fact lookup</h3><label>Customer 101 on <input aria-label="SCD lookup date" type="date" value={asOf} onChange={e=>setAsOf(e.target.value)}/></label><p>{at?`Fact joins to customer_key ${at.customer_key}, city ${at.city}.`:'No matching dimension version in the events applied so far.'}</p></div>}
  <div className="an-card an-exercise"><h3>Check your understanding</h3><p>After these {step} events, how many dimension rows should Type {type} contain?</p><div className="an-actions"><input aria-label="SCD expected row count" inputMode="numeric" value={answer} onChange={e=>update({answer:e.target.value.slice(0,10)})}/><button onClick={()=>setChecked(true)}>Check reasoning</button></div>{checked&&<p role="status" className={answer.trim()===result.expected?'an-success':'an-warning'}>{answer.trim()===result.expected?'Correct.':`Not yet. Expected ${result.expected} rows.`} {result.explanation}</p>}<small>This local check grades only the row-count answer for the displayed fixture. It does not execute or grade SQL/PySpark code.</small></div></section>;
}
