import * as React from 'react';
import {GUIDED_SPARK_LESSON} from './guidedSpark';
import {JsonDownload, RowsTable, SourceEditor, Title} from './controls';
export function RuntimeStudio() {
  return <section className="an-layer"><Title eyebrow="RUNTIME BOUNDARIES / NO VM REQUIRED" title="Local first. Connect later."/><p className="an-lead">This analytics layer edits and visualizes documents. The existing notebook runtime remains separate; opening a layer does not start compute.</p><div className="an-runtime-grid">{[
    ['DuckDB SQL','Local engine','Use the existing trusted local Datapass service. No Oracle VM or scheduler is required.'],
    ['DuckLake','Canonical local lakehouse','DuckDB compute plus catalog metadata and Parquet data. Keep DuckDB mode available when extensions are not installed.'],
    ['Python / pandas','Optional local environment','pandas is a Python library, not a separate remote cluster. Enable trusted local Python and install pandas explicitly. Never execute untrusted notebooks on your computer.'],
    ['Polars','First-class local compute','Useful for DataFrame exercises, not a prerequisite. It can use the same Python environment and workspace data; no separate product shell is needed.'],
    ['dbt Core + dbt-duckdb','Real local project runtime','Build the exported sample project locally. Import its manifest and matching run-results here. No VM, Docker, GitLab or dbt Cloud account is necessary.'],
    ['dbt Charts / dct','Optional local CLI','Author boards here, export YAML, validate/render with dct. Native preview is not the upstream dct renderer.'],
    ['MotherDuck','Explicit optional remote connection','The free tier is quota-limited. Keep tokens in environment/profile configuration outside the browser. This UI does not establish or test a connection.'],
  ].map(([title,state,description])=><article className="an-card" key={title}><span className="an-badge">{state}</span><h3>{title}</h3><p>{description}</p></article>)}</div>
  <div className="an-card"><h3>The first real dbt loop</h3><pre>Export source JSON from dbt Studio{ '\n'}python tools/materialize_dbt.py --source exported.json --output my-dbt-project{'\n'}python -m pip install dbt-duckdb{'\n'}dbt build --project-dir my-dbt-project --profiles-dir my-dbt-project{'\n'}Import target/manifest.json + target/run_results.json</pre><p>The included sample project already has models, tests and seed data. Run it only after reviewing the source. dbt project macros can execute code; local execution is not sandboxing.</p></div><div className="an-warning"><b>Deferred:</b> Public multi-user execution, cloud credentials and remote job dispatch. These are not required for the local product. A dbt dependency graph is not an Airflow scheduler.</div></section>;
}
export function GuidedSparkStudio() {
  const l=GUIDED_SPARK_LESSON;
  return <section className="an-layer"><Title eyebrow="DEDICATED MODULE / CONTRACT PREPARATION" title="Guided SparkLab"><span className="an-badge">Not connected</span></Title><p className="an-lead">A curated exercise defines supported operations, versioned fixture rows and expected results before any service is called. This is not a general PySpark kernel.</p>
  <div className="an-actions"><JsonDownload name="guided-spark-lesson.json" value={l}>Export lesson contract</JsonDownload><button disabled title="No endpoint is configured or qualified in this milestone.">Run guided exercise</button></div><div className="an-card"><h3>{l.title}</h3><p>Allowed operations: {l.allowedOperations.join(', ')}. Fixture: {l.fixtureVersion}.</p><SourceEditor label="Guided Spark starter example" source={l.starter} language="python" readOnly onChange={()=>{}}/><RowsTable label="Guided Spark lesson fixture" rows={l.rows.map(r=>({...r}))}/></div>
  <div className="an-card"><h3>Integration contract with fastapispark</h3><pre>Lesson + fixture version + supported syntax{'\n'}  - compile source using POST /v1/spark/compile{'\n'}  - reject unsupported operations or compiler warnings{'\n'}  - validate against this lesson, server-side as well as client-side{'\n'}  - execute only the lesson fixture using POST /v1/spark/execute{'\n'}  - check all result rows, not only the displayed preview{'\n'}  - store the attempt separately from layout/source revisions</pre><p>{l.truth}</p><p>Current helper code only validates a compile-response envelope and prepares a bounded request. It neither makes a network request nor certifies the service as safe for arbitrary input. Server-side argument validation, version negotiation, full-result grading, authentication and conformance tests remain integration gates.</p></div></section>;
}
