import { adfModules, databricksModules } from '../data/curriculum';
import type { AzureProduct, PageKey } from '../types/app';

export function AzureHub({ product, onProduct, onNavigate }:{product:AzureProduct;onProduct:(p:AzureProduct)=>void;onNavigate:(p:PageKey)=>void}){
  return <div className="learning-hub-page azure-hub"><section className="hub-hero azure-hub-hero"><div><span className="eyebrow">Azure data engineering</span><h1>Orchestration + lakehouse compute</h1><p>Use Azure Data Factory to orchestrate data movement and external compute. Use Azure Databricks for Spark, Delta Lake, Unity Catalog, streaming, Lakeflow pipelines/jobs and SQL serving.</p><div className="hero-actions"><button className={product==='adf'?'primary-button':'secondary-button'} onClick={()=>onProduct('adf')}>Azure Data Factory</button><button className={product==='databricks'?'primary-button':'secondary-button'} onClick={()=>onProduct('databricks')}>Azure Databricks</button></div></div><div className="azure-integration-flow"><div><strong>Sources</strong><small>SQL · files · APIs · SaaS</small></div><b>→</b><div><strong>ADF</strong><small>Copy · control flow · schedule</small></div><b>→</b><div><strong>Databricks</strong><small>Spark · Delta · Lakeflow</small></div><b>→</b><div><strong>Serving</strong><small>Delta · SQL Warehouse</small></div></div></section>
  <section className="hub-section"><div className="section-title-row"><div><span className="eyebrow">Azure Data Factory</span><h2>Classic ADF workbenches</h2></div></div><div className="module-grid compact-modules">{adfModules.map(m=><article className="module-card azure" key={m.id}><h3>{m.title}</h3><p>{m.summary}</p><div className="module-concepts">{m.concepts.map(c=><span key={c}>{c}</span>)}</div><button className="secondary-button" onClick={()=>onNavigate(m.id==='adf-databricks'?'dbx-adf-integration':'pipeline')}>Open</button></article>)}</div></section>
  <section className="hub-section"><div className="section-title-row"><div><span className="eyebrow">Azure Databricks</span><h2>Lakehouse engineering workbenches</h2><p>{databricksModules.length} modules mapped from your uploaded Microsoft Learn/DP-750 training material.</p></div><button className="secondary-button" onClick={()=>{onProduct('databricks');onNavigate('dbx-home')}}>Open Databricks workspace</button></div></section>
  <section className="integration-banner"><div><span className="eyebrow">Recommended bridge exercise</span><h2>ADF runs a Databricks notebook</h2><p>Practice the service boundary explicitly: ADF owns orchestration; Databricks owns the Spark transformation.</p></div><button className="primary-button" onClick={()=>onNavigate('dbx-adf-integration')}>Start lab</button></section></div>
}
