import { useState } from 'react';
import type { CaseStudy } from '../types/app';

export function FabricRuntimeStudio({ caseStudy }: { caseStudy: CaseStudy }) {
  const [runtime, setRuntime] = useState('Workspace default');
  const [library, setLibrary] = useState(false);
  const [published, setPublished] = useState(false);
  const [jobRun, setJobRun] = useState(false);
  const [retry, setRetry] = useState(true);
  const [snapshot, setSnapshot] = useState(false);
  const [mlv, setMlv] = useState(false);
  const useSpark = caseStudy.id === 'turbine-realtime';
  return <div className="studio-page runtime-studio">
    <div className="page-heading studio-heading"><div><span className="eyebrow">Fabric Data Engineering</span><h1>Environment + Spark Job Definition</h1><p>Mirror the real operating boundary: Workspace default is often enough. Attach a published Environment when teams need reusable Spark runtime, compute, libraries or resource settings. Create Spark Job Definitions only when Spark is actually the correct production engine.</p></div><button className="primary-button" onClick={() => setPublished(true)}>Publish environment</button></div>
    <div className="runtime-grid">
      <section className="surface-card"><div className="surface-card-title"><div><span className="fabric-item-icon">ENV</span><strong>ENV_DataEngineering</strong></div><span className={`status-pill ${published ? 'success' : ''}`}>{published ? 'Published' : 'Draft'}</span></div>
        <div className="form-grid"><label>Notebook / job environment<select value={runtime} onChange={e => setRuntime(e.target.value)}><option>Workspace default</option><option>ENV_DataEngineering</option></select></label><label>Fabric runtime<select><option>Current supported runtime</option><option>Previous compatible runtime</option></select></label><label>Compute profile<select><option>Starter / managed defaults</option><option>Custom Spark compute</option></select></label><label>Dynamic allocation<select><option>Enabled</option><option>Disabled</option></select></label></div>
        <div className="subsurface"><div className="subsurface-title"><strong>Public libraries + resources</strong><button className="secondary-button" onClick={() => setLibrary(true)}>+ Add library</button></div>{library ? <div className="library-row"><code>great-expectations</code><span>compatible version</span><span>PyPI</span><button className="text-button" onClick={() => setLibrary(false)}>Remove</button></div> : <div className="empty-inline">No custom libraries. Workspace default remains the simpler choice when custom Spark dependencies are not needed.</div>}</div>
        <div className="learning-box wide"><strong>Real-life rule</strong><p>Use an Environment to standardize Spark settings and dependencies across notebooks and Spark Job Definitions. Do not create one simply to make every notebook look “production.”</p></div>
      </section>
      <section className="surface-card"><div className="surface-card-title"><div><span className="fabric-item-icon">SJD</span><strong>SJD_{caseStudy.id.replaceAll('-', '_')}</strong></div><span className={`status-pill ${jobRun ? 'success' : ''}`}>{jobRun ? 'Succeeded' : 'Not run'}</span></div>
        <div className="form-stack"><label>Main definition file<input defaultValue="jobs/transform_gold.py" /></label><label>Reference files<input defaultValue="lib/quality.py lib/io.py" /></label><label>Default Lakehouse<input defaultValue={`LH_${caseStudy.id.replaceAll('-', '_')}`} /></label><label>Environment<input value={runtime === 'Workspace default' ? 'Workspace default' : 'ENV_DataEngineering'} readOnly /></label><label>Command-line arguments<input defaultValue="--layer silver --target gold --mode incremental" /></label><label className="toggle-row"><input type="checkbox" checked={retry} onChange={e => setRetry(e.target.checked)} /><span><strong>Retry policy</strong><small>Restart the job on transient failure; keep the job idempotent</small></span></label></div>
        <div className="spark-scope-banner"><strong>{useSpark ? 'Spark justified for this production scenario' : 'Use Spark when justified, not by default'}</strong><span>{useSpark ? 'Production: distributed telemetry workload · App: representative local rows with simulated stages/partitions' : 'This case is primarily relational. Prefer SQL/dbt/Python unless production scale changes the requirement.'}</span></div>
        <div className="job-code"><pre>{useSpark ? `from pyspark.sql import functions as F\n\ndf = spark.table("bronze.turbine_events")\nfeatures = (df\n  .repartition("turbine_id")\n  .withColumn("temperature_delta", F.col("gearbox_temp_c") - 65))\nfeatures.write.mode("append").saveAsTable("silver.turbine_features")` : `# Production-shaped definition only if Spark becomes justified\n# For the current case, prefer the SQL/dbt/Python workbenches.\n\nprint("No distributed Spark requirement yet")`}</pre></div>
        <div className="card-actions"><button className="secondary-button" onClick={() => setSnapshot(true)}>View run snapshot</button><button className="primary-button" onClick={() => setJobRun(true)}>▶ Run Spark job</button></div>{jobRun && <div className="run-success-box"><strong>Run succeeded</strong><span>{useSpark ? '3 simulated stages · representative rows written' : 'No-op learning run · review whether Spark should exist in this architecture'}</span></div>}{snapshot && <div className="learning-box wide"><strong>Run snapshot</strong><p>Main/reference files, arguments, Lakehouse context, environment, retry settings and Spark properties are captured for the historical run. In Fabric, snapshots help you inspect or restore the job definition state used for a past execution.</p></div>}
      </section>
      <aside className="learning-side-panel standalone"><div className="pane-title">Practice checklist</div><Task ok={runtime === 'Workspace default' || runtime === 'ENV_DataEngineering'} text="Choose Workspace default vs attached Environment deliberately"/><Task ok={library || runtime === 'Workspace default'} text="Avoid unnecessary custom dependencies"/><Task ok={published} text="Publish the environment before shared use"/><Task ok={retry} text="Configure retry only for idempotent jobs"/><Task ok={jobRun} text="Execute the Spark Job Definition"/><Task ok={snapshot} text="Inspect the historical run snapshot"/><Task ok={mlv} text="Create a materialized lake view concept"/><button className="secondary-button wide-button" onClick={() => setMlv(true)}>+ Materialized lake view</button><div className="learning-box"><strong>When to use Spark Job Definition</strong><p>Application-style batch/streaming Spark job with a main file, optional references, arguments and a default Lakehouse. If the requirement is ordinary relational modeling, the dbt/SQL path is usually simpler.</p></div></aside>
    </div>
  </div>;
}
function Task({ok,text}:{ok:boolean;text:string}){return <div className={`check-row ${ok?'done':''}`}><span>{ok?'✓':'○'}</span><p>{text}</p></div>}
