import { useState } from 'react';

export function FabricDeploymentStudio(){
  const [deployed,setDeployed]=useState<'none'|'test'|'prod'>('none');
  const [git,setGit]=useState(false);
  return <div className="studio-page deployment-studio"><div className="page-heading studio-heading"><div><span className="eyebrow">Lifecycle</span><h1>Deployment pipelines + source control</h1><p>Practice the development → test → production promotion model without connecting a real repository.</p></div><button className="secondary-button" onClick={()=>setGit(true)}>{git?'✓ Source control connected':'Configure source control'}</button></div>
  <div className="deployment-flow"><Stage name="Development" workspace="DE-Lab-Dev" items="8 items" active/><span className="deployment-arrow">→</span><Stage name="Test" workspace="DE-Lab-Test" items={deployed==='test'||deployed==='prod'?'8 items':'0 items'} active={deployed==='test'||deployed==='prod'}/><span className="deployment-arrow">→</span><Stage name="Production" workspace="DE-Lab-Prod" items={deployed==='prod'?'8 items':'0 items'} active={deployed==='prod'}/></div>
  <div className="deployment-actions"><button className="primary-button" onClick={()=>setDeployed('test')}>Deploy Dev → Test</button><button className="primary-button" disabled={deployed==='none'} onClick={()=>setDeployed('prod')}>Deploy Test → Prod</button></div>
  <div className="deployment-grid"><section className="surface-card"><h2>Items in deployment</h2><table className="manage-table"><thead><tr><th>Item</th><th>Type</th><th>Dev</th><th>Test</th><th>Prod</th></tr></thead><tbody>{[['PL_Ingest','Pipeline'],['LH_Training','Lakehouse'],['NB_Transform','Notebook'],['DF_Clean','Dataflow Gen2'],['WH_Analytics','Warehouse']].map(r=><tr key={r[0]}><td><strong>{r[0]}</strong></td><td>{r[1]}</td><td>Current</td><td>{deployed==='none'?'Missing':'Synced'}</td><td>{deployed==='prod'?'Synced':'Missing'}</td></tr>)}</tbody></table></section><aside className="learning-side-panel standalone"><div className="pane-title">CI/CD mental model</div><div className="concept-card"><strong>Source control</strong><span>Track authoring definitions and collaborate.</span></div><div className="concept-card"><strong>Deployment pipeline</strong><span>Promote Fabric items between environments.</span></div><div className="concept-card"><strong>Environment binding</strong><span>Connections/IDs can differ between Dev, Test, and Prod.</span></div>{git&&<div className="run-success-box"><strong>Training repository configured</strong><span>main · simulated</span></div>}</aside></div></div>
}
function Stage({name,workspace,items,active}:{name:string;workspace:string;items:string;active:boolean}){return <div className={`deployment-stage ${active?'active':''}`}><span>{name}</span><strong>{workspace}</strong><small>{items}</small></div>}
