import { useMemo, useState } from 'react';
import type { CaseStudy, DataWorkspace, WorkspaceTable } from '../types/app';

function fabricItemType(table: WorkspaceTable): string {
  if (table.layer === 'warehouse') return 'Warehouse table';
  if (table.layer === 'stream') return 'Event / stream table';
  return 'Lakehouse table';
}

export function FabricGovernanceStudio({ caseStudy, workspace }: { caseStudy: CaseStudy; workspace: DataWorkspace }) {
  const [tab, setTab] = useState<'Catalog'|'Security'|'Lineage'|'Impact'>('Catalog');
  const [endorsed, setEndorsed] = useState(false);
  const [security, setSecurity] = useState(false);
  const [impact, setImpact] = useState(false);
  const [query, setQuery] = useState('');
  const assets = useMemo(() => workspace.tables.filter((table) => !query.trim() || `${table.schema}.${table.name} ${table.layer}`.toLowerCase().includes(query.trim().toLowerCase())), [workspace.tables, query]);
  const lineage = (workspace.lineage ?? []).slice(0, 12);
  const impactTarget = workspace.tables.find((table) => table.layer === 'silver') ?? workspace.tables.find((table) => table.layer === 'gold') ?? workspace.tables[0];
  const impactName = impactTarget ? `${impactTarget.schema}.${impactTarget.name}` : '';
  const downstream = (workspace.lineage ?? []).filter((edge) => edge.from.toLowerCase() === impactName.toLowerCase());
  return <div className="studio-page governance-studio">
    <div className="page-heading studio-heading"><div><span className="eyebrow">OneLake Catalog + governance</span><h1>Discover, secure, and trace Fabric data</h1><p>Practice the control plane around the same live learning assets created by Pipeline, Notebook, SQL and dbt.</p></div><button className="primary-button" onClick={()=>setEndorsed(true)}>{endorsed?'✓ Endorsed':'Endorse selected item'}</button></div>
    <div className="governance-tabs">{(['Catalog','Security','Lineage','Impact'] as const).map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>
    {tab==='Catalog'&&<div className="catalog-browser"><aside className="catalog-filters"><strong>OneLake catalog</strong><label><input type="checkbox" defaultChecked/> Lakehouse</label><label><input type="checkbox" defaultChecked/> Warehouse</label><label><input type="checkbox" defaultChecked/> Eventhouse / stream</label><hr/><strong>Workspace evidence</strong><small>Snapshot {workspace.snapshot}</small><small>{workspace.tables.length} tables</small><small>{workspace.lineage.length} lineage edges</small></aside><main className="catalog-results"><div className="catalog-search"><input placeholder="Search live OneLake catalog" value={query} onChange={(event)=>setQuery(event.target.value)}/><select><option>DE Learning</option></select></div><table className="manage-table"><thead><tr><th>Item</th><th>Type</th><th>Layer</th><th>Rows</th><th>Endorsement</th><th>Source</th></tr></thead><tbody>{assets.slice(0,20).map((table)=><tr key={`${table.schema}.${table.name}`}><td><strong>{table.schema}.{table.name}</strong></td><td>{fabricItemType(table)}</td><td>{table.layer}</td><td>{table.rows.length}</td><td>{endorsed?'Promoted':'—'}</td><td>{table.runtimeSource}</td></tr>)}</tbody></table>{!assets.length&&<div className="empty-state-card"><strong>No matching assets</strong><span>Change the search text or create data in another Fabric workbench.</span></div>}</main></div>}
    {tab==='Security'&&<div className="governance-content"><section className="surface-card"><h2>Access layers</h2><div className="security-layer-grid"><Layer title="Workspace role" value="Contributor" text="Controls workspace-level abilities."/><Layer title="Item permission" value="Read + ReadData" text="Controls an individual Fabric item."/><Layer title="OneLake security" value={security?'RLS policy active':'Not configured'} text="Fine-grained table/data access."/></div><button className="primary-button" onClick={()=>setSecurity(true)}>Apply training RLS policy</button>{security&&<pre className="policy-code">Region = USERPRINCIPALNAME() → security_map.region</pre>}</section><aside className="learning-side-panel standalone"><div className="pane-title">Security principle</div><p>Do not confuse workspace access with data access. A user can discover an item but still be restricted from specific rows, columns, or data paths.</p></aside></div>}
    {tab==='Lineage'&&<div className="governance-content"><section className="surface-card"><div className="surface-card-title"><div><span className="eyebrow">Live lineage</span><strong>{lineage.length} recent relationship{lineage.length===1?'':'s'}</strong></div><span className="status-pill">snapshot {workspace.snapshot}</span></div>{lineage.length?<div className="production-lineage-list">{lineage.map((edge)=><div className="production-lineage-row" key={edge.id}><code>{edge.from}</code><b>→</b><code>{edge.to}</code><small>{edge.actor} · {edge.operation} · snapshot {edge.snapshot}</small></div>)}</div>:<div className="empty-state-card"><strong>No emitted lineage yet</strong><span>Run Copy, Notebook, SQL, dbt or the production workflow; the resulting relationships will appear here.</span></div>}</section><aside className="learning-side-panel standalone"><div className="pane-title">Why this matters</div><p>The lineage view is now generated from actual representative operations in the shared workspace rather than a fixed diagram.</p></aside></div>}
    {tab==='Impact'&&<div className="governance-content"><section className="surface-card"><h2>Impact analysis</h2><p>Simulate a breaking change to <code>{impactName || 'a curated table'}</code>.</p><button className="secondary-button" onClick={()=>setImpact(true)}>Analyze downstream impact</button>{impact&&<div className="impact-list">{downstream.length?downstream.map((edge,index)=><div key={edge.id}><span className={index===0?'severity-high':'severity-medium'}>{index===0?'High':'Medium'}</span><strong>{edge.to}</strong><small>{edge.actor} depends on this asset through {edge.operation}</small></div>):<div><span className="severity-low">Low</span><strong>No emitted downstream dependency</strong><small>Create a downstream SQL/dbt/Pipeline table first, then rerun impact analysis.</small></div>}<div><span className="severity-low">Future</span><strong>Power BI semantic model</strong><small>Reserved for a later pass</small></div></div>}</section></div>}
  </div>;
}
function Layer({title,value,text}:{title:string;value:string;text:string}){return <div className="security-layer"><span>{title}</span><strong>{value}</strong><p>{text}</p></div>}
