import {CatalogHost} from '../studio/workspace/CatalogHost';
import {useEffect,useMemo,useRef,useState,Fragment,type ReactNode} from 'react';
import {Badge,Button,Field,Input,MessageBar,MessageBarBody,Select,Tab,TabList,Textarea} from '@fluentui/react-components';
import {Add24Regular,ArrowDownload24Regular,ArrowUpload24Regular,Dismiss16Regular,PanelLeft24Regular,Save24Regular} from '@fluentui/react-icons';
import type {Asset,Capabilities,Workspace} from '../../../../packages/contracts/src/index.ts';
import {evidenceOf,isGraph,projectGraph,runtimeTargets,type DataModelResource,type GraphResource,type Resource,type RootWorkbench,type ViewInstance} from '../../../../packages/contracts/src/foundation.ts';
import {addGraphNode,addResource,closePane,closeView,connectGraph,deleteGraphItems,exampleResource,moveView,newId,openResource,patchView,replaceResource,removeResource,splitPane} from '../../../../packages/contracts/src/workbench.ts';
import {sourceOf,type RootNotebook} from '../notebook';
import {CodeEditor} from '../CodeEditor';
import {ResultView} from '../ResultView';
import {GraphCanvas} from './GraphCanvas';
import type {WorkbenchController} from './useWorkbench';
import './foundation.css';
import {ResourceHost,hostedKinds,type ResourceServices} from '../studio/workspace/ResourceHost';
import {creatableResources,createStudioResource} from '../studio/workspace/resourceFactories';
import {ResourcePalette} from '../studio/workspace/ResourcePalette';
import {studioUI} from './workspaceResources';

function download(name:string,value:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const kindLabels:Record<Resource['kind'],string>={'dbt-project':'dbt project','model-design':'Data model / SCD','chart-board':'Charts',pipeline:'Pipeline Lab',figure:'ConceptMotion',exercise:'Arena',workflow:'Workflow',lineage:'Lineage','data-model':'Data model',notebook:'Notebook',catalog:'Catalog',evidence:'Evidence'};
const newBase=(title:string)=>({schema_version:1 as const,id:newId('resource'),title,revision:0});

interface Props {
 controller:WorkbenchController;workspace:Workspace<RootNotebook>;notebook:RootNotebook|null;
 assets:Asset[];capabilities:Capabilities|null;busy:boolean;liveNotebook:ReactNode;
 services:ResourceServices;onCreateNotebook?:()=>void;onOpenNotebook:(id:string)=>void;onSave:()=>void;onImport:(value:unknown,owner:string)=>void;
}
export function WorkbenchSurface({controller,workspace,notebook,assets,capabilities,busy,liveNotebook,onOpenNotebook,onSave,onImport,services,onCreateNotebook}:Props){
 const state=controller.document;
 const [error,setError]=useState(''),[maximized,setMaximized]=useState<string|null>(null);
 const file=useRef<HTMLInputElement>(null);
 const [palette,setPalette]=useState(false);const area=useRef<HTMLDivElement>(null);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();e.stopImmediatePropagation();setPalette(p=>!p)}if(e.key==='Escape'){setPalette(false);setMaximized(null)}};window.addEventListener('keydown',key,true);return()=>window.removeEventListener('keydown',key,true)},[]);
 const safe=(action:()=>void)=>{try{action();setError('')}catch(e){setError(e instanceof Error?e.message:String(e))}};
 const update=(change:(state:RootWorkbench)=>RootWorkbench,record=true)=>safe(()=>controller.change(change,record));
 if(!state)return <p className="surface-page">Opening workbench references...</p>;
 const ui=state.ui??studioUI();
 const resources=new Map(state.resources.map(r=>[r.id,r]));
 const visible=state.panes.filter(p=>!maximized||!state.panes.some(x=>x.id===maximized)||p.id===maximized);
 // Exactly one live editor mounts for the active canonical notebook. Other panes read its source.
 const liveCandidates=visible.flatMap(p=>{const v=state.views.find(v=>v.id===p.active_view_id),r=v&&resources.get(v.resource_id);return v&&r?.kind==='notebook'&&r.notebook_id===notebook?.id?[{pane:p.id,view:v.id}]:[]});
 const editorView=(liveCandidates.find(v=>v.pane===state.active_pane_id)??liveCandidates[0])?.view;
 const availableNotebooks={...workspace.notebooks,...(notebook?{[notebook.id]:notebook}:{})};
 const add=(resource:Resource)=>update(current=>openResource(addResource(current,resource),resource.id));
 function renderResource(resource:Resource,view:ViewInstance){
  if(view.mode==='spec')return <div className="foundation-spec"><p>Canonical resource, not an execution result. Use Import layout / designs to validate externally authored JSON.</p><CodeEditor language="json" modelId={`${workspace.id}/resource/${resource.id}/${view.id}`} active value={JSON.stringify(resource,null,2)} readOnly onChange={()=>{}} onRun={()=>{}}/></div>;
  if(hostedKinds.has(resource.kind))return <ResourceHost resource={resource} resources={state!.resources} view={view} services={services} disabled={busy} change={update}/>;
  if(isGraph(resource))return <GraphEditor resource={resource} view={view} resources={state!.resources} assets={assets} capabilities={capabilities} disabled={busy}
   onView={patch=>update(current=>patchView(current,view.id,patch))}
   onResource={next=>update(current=>replaceResource(current,next))} onError={setError}/>;
  if(resource.kind==='notebook'){
   const doc=availableNotebooks[resource.notebook_id];
   if(!doc)return <p className="foundation-empty">Notebook reference unavailable. Source is not fabricated or imported by this view.</p>;
   if(view.id===editorView)return <div className="foundation-live-notebook"><div className="foundation-note"><Badge color="success" appearance="tint">Shared editor</Badge> Existing notebook engine and runtime. Run and Save remain in the main command bar.</div>{liveNotebook}</div>;
   return <div className="foundation-notebook-preview"><div className="foundation-note"><Badge appearance="outline">Shared read-only view</Badge><Button disabled={busy} onClick={()=>{update(current=>({...current,active_pane_id:state!.panes.find(p=>p.view_ids.includes(view.id))!.id}),false);onOpenNotebook(doc.id)}}>Edit here</Button></div><p>This pane references the same document. Editing here transfers editor focus; it does not create another notebook.</p>{doc.blocks.filter(b=>b.type!=='notebook-output').map(b=><section key={b.id}><h4>{b.title}</h4><pre>{sourceOf(doc,b)}</pre></section>)}</div>;
  }
  if(resource.kind==='catalog')return <CatalogHost key={workspace.id} assets={assets} services={services} disabled={busy}/>;
  return <div className="foundation-data"><p>Existing persisted runs; opening this view does not run a cell. Local measurements and modeled cluster metrics remain separate.</p>{[...workspace.runs].reverse().map(run=>{const truth=evidenceOf(run);return <article key={run.id}><h4>{run.cell_id}</h4><Badge appearance="outline">{truth.semantic}</Badge>{truth.simulation==='simulated'&&<Badge appearance="tint" color="warning">Separate simulated metrics</Badge>}<ResultView run={run} historical/></article>})}{!workspace.runs.length&&<p>No execution history yet. Design graphs do not create successful runs.</p>}</div>;
 }
 return <section className={`foundation persona-${state.persona}`} aria-label="Modular workbench">
  <div className="foundation-toolbar"><div><strong>Datapass Workbench</strong><Badge appearance="outline">Local-first</Badge></div><Select aria-label="Experience skin" value={ui.skin} disabled={busy} onChange={(_,d)=>update(c=>({...c,ui:{...ui,skin:d.value as typeof ui.skin}}))}><option value="studio">Datapass Studio</option><option value="fabric">Fabric-inspired</option><option value="databricks">Databricks-inspired</option><option value="arena">Arena</option></Select><Select aria-label="Workbench theme" value={ui.theme} disabled={busy} onChange={(_,d)=>update(c=>({...c,ui:{...ui,theme:d.value as typeof ui.theme}}))}><option value="fluent">Fluent Light</option><option value="neutral">Neutral Light</option><option value="dark">Dark</option></Select><Button aria-label="Split right" disabled={busy||state.panes.length===3} onClick={()=>update(c=>({...splitPane(c),direction:'horizontal'}))}>Split right</Button><Button aria-label="Split down" disabled={busy||state.panes.length===3} onClick={()=>update(c=>({...splitPane(c),direction:'vertical'}))}>Split down</Button><Button onClick={()=>setPalette(true)}>Find / Ctrl K</Button><Button aria-pressed={ui.explorer_open} onClick={()=>update(c=>({...c,ui:{...ui,explorer_open:!ui.explorer_open}}))}>Explorer</Button><Button aria-pressed={ui.context_open} onClick={()=>update(c=>({...c,ui:{...ui,context_open:!ui.context_open}}))}>Context</Button><Button disabled={busy||!controller.canUndo} onClick={()=>safe(controller.undo)}>Undo layout / design</Button><Button disabled={busy||!controller.canRedo} onClick={()=>safe(controller.redo)}>Redo</Button><Button appearance="primary" icon={<Save24Regular/>} disabled={busy} onClick={onSave}>Save workspace</Button></div>
  {error&&<MessageBar intent="error"><MessageBarBody>{error} Your previous valid design is retained.</MessageBarBody></MessageBar>}
  <div className="foundation-truth"><Badge appearance="tint" color="warning">Explicit execution</Badge><span>Execution is explicit. Design, imported evidence, local results and simulated metrics stay distinct.</span><span>{controller.dirty?'Unsaved layout / design':'Saved or derived workspace view'}</span></div>
  <div className="foundation-body">{ui.explorer_open&&<aside className="foundation-resources" aria-label="Shared resources"><h3>Resources</h3><p>One source, multiple views.</p>
   {state.resources.map(r=><div className="foundation-resource-row" key={r.id}><Button appearance="subtle" disabled={busy} onClick={()=>update(current=>openResource(current,r.id))}><span><strong>{r.title}</strong><small>{kindLabels[r.kind]}{isGraph(r)?' / design':''}</small></span></Button></div>)}
   <details open><summary>Add a resource</summary>{creatableResources.map(([kind,label])=><Button key={kind} disabled={busy} onClick={()=>add(createStudioResource(kind))}>{label}</Button>)}{onCreateNotebook&&<Button disabled={busy} onClick={onCreateNotebook}>New notebook</Button>}{(['workflow','lineage','data-model'] as const).map(kind=><Button key={kind} icon={<Add24Regular/>} disabled={busy} onClick={()=>add(exampleResource(kind))}>{kindLabels[kind]} example</Button>)}</details>
   <details><summary>Link existing notebook</summary>{Object.values(availableNotebooks).map(n=><Button key={n.id} disabled={busy} onClick={()=>safe(()=>controller.linkNotebook(n))}>{n.title}</Button>)}</details>
   <details><summary>Shared services</summary><Button disabled={busy} onClick={()=>{const found=state.resources.find(r=>r.kind==='catalog');if(found)update(c=>openResource(c,found.id));else add({...newBase('Shared catalog'),kind:'catalog'})}}>Catalog</Button><Button disabled={busy} onClick={()=>{const found=state.resources.find(r=>r.kind==='evidence');if(found)update(c=>openResource(c,found.id));else add({...newBase('Run evidence'),kind:'evidence'})}}>Evidence</Button></details>
   <div className="foundation-files"><Button icon={<ArrowDownload24Regular/>} disabled={busy} onClick={()=>download('datapass-workbench.json',state)}>Export layout / designs</Button><Button icon={<ArrowUpload24Regular/>} disabled={busy} onClick={()=>file.current?.click()}>Import layout / designs</Button><input ref={file} type="file" accept=".json" hidden disabled={busy} onChange={event=>{const chosen=event.currentTarget.files?.[0],owner=workspace.id;event.currentTarget.value='';if(!chosen)return;if(chosen.size>2_000_000){setError('Import exceeds the 2 MB limit.');return}void chosen.text().then(text=>{const value:unknown=JSON.parse(text);if(!controller.dirty||window.confirm('Replace the unsaved workbench layout/design? Notebook source is unaffected.'))onImport(value,owner)}).catch(e=>setError(String(e)))}}/><small>References and designs only. This is not a data or notebook backup.</small></div>
  </aside>}<div ref={area} className={`foundation-panes ${state.direction}`}>
   {visible.map((pane,index)=>{const view=state.views.find(v=>v.id===pane.active_view_id),resource=view&&resources.get(view.resource_id);return <Fragment key={pane.id}>{index>0&&<div className="foundation-divider" role="separator" aria-label="Resize workspace panes" aria-orientation={state.direction==='horizontal'?'vertical':'horizontal'} aria-valuemin={25} aria-valuemax={400} aria-valuenow={Math.round(pane.weight*100)} tabIndex={0} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();update(c=>({...c,panes:c.panes.map(p=>p.id===pane.id?{...p,weight:Math.max(.25,Math.min(4,p.weight+(['ArrowLeft','ArrowUp'].includes(e.key)?.1:-.1)))}:p)}))}}} onPointerDown={e=>{if(busy)return;controller.checkpoint();e.currentTarget.setPointerCapture(e.pointerId);e.currentTarget.dataset.resizing='yes'}} onPointerMove={e=>{if(busy||e.currentTarget.dataset.resizing!=='yes'||!area.current)return;const rect=area.current.getBoundingClientRect();const ratio=state.direction==='horizontal'?(e.clientX-rect.left)/rect.width:(e.clientY-rect.top)/rect.height;const a=visible[index-1],sum=a.weight+pane.weight;const prior=visible.slice(0,index-1).reduce((v,p)=>v+p.weight,0),all=visible.reduce((v,p)=>v+p.weight,0);const left=Math.max(.25,Math.min(sum-.25,ratio*all-prior));update(c=>({...c,panes:c.panes.map(p=>p.id===a.id?{...p,weight:Math.min(4,left)}:p.id===pane.id?{...p,weight:Math.min(4,sum-left)}:p)}),false)}} onPointerUp={e=>{delete e.currentTarget.dataset.resizing}} onPointerCancel={e=>{delete e.currentTarget.dataset.resizing}} onLostPointerCapture={e=>{delete e.currentTarget.dataset.resizing}}/>}<section className={`foundation-pane ${state.active_pane_id===pane.id?'focused':''}`} style={{flexGrow:pane.weight}} aria-label={`Workbench pane ${state.panes.indexOf(pane)+1}`} onFocusCapture={()=>{if(!busy&&state.active_pane_id!==pane.id)update(current=>({...current,active_pane_id:pane.id}),false)}}>
    <div className="foundation-tabbar" role="tablist" aria-label="Resource tabs">{pane.view_ids.map(id=>{const v=state.views.find(v=>v.id===id)!,r=resources.get(v.resource_id)!;return <div key={id}><button role="tab" aria-selected={id===pane.active_view_id} aria-controls={`panel-${pane.id}`} id={`tab-${id}`} disabled={busy} onClick={()=>update(current=>({...current,active_pane_id:pane.id,panes:current.panes.map(p=>p.id===pane.id?{...p,active_view_id:id}:p)}),false)}>{r.title}</button><Button size="small" appearance="subtle" icon={<Dismiss16Regular/>} aria-label={`Close ${r.title} view`} disabled={busy} onClick={()=>update(current=>closeView(current,id))}/></div>})}<Button aria-label="New resource tab" onClick={()=>{update(c=>({...c,active_pane_id:pane.id}),false);setPalette(true)}}>+</Button></div>
    <div className="foundation-pane-tools"><Button size="small" disabled={busy} onClick={()=>setMaximized(maximized===pane.id?null:pane.id)}>{maximized===pane.id?'Show all panes':'Focus pane'}</Button><Button size="small" disabled={busy||state.panes.length===1} onClick={()=>{update(c=>closePane(c,pane.id));setMaximized(null)}}>Close pane</Button>{view&&<><Select size="small" aria-label="Move active tab" value="" disabled={busy||state.panes.length===1} onChange={(_,d)=>{if(d.value)update(c=>moveView(c,view.id,d.value))}}><option value="">Move tab to...</option>{state.panes.filter(p=>p.id!==pane.id).map(p=><option key={p.id} value={p.id}>Pane {state.panes.indexOf(p)+1}</option>)}</Select><Select aria-label="Pane size" size="small" value={String(pane.weight)} disabled={busy} onChange={(_,d)=>update(c=>({...c,panes:c.panes.map(p=>p.id===pane.id?{...p,weight:Number(d.value)}:p)}))}><option value="0.5">Narrow</option><option value="1">Equal</option><option value="2">Wide</option></Select></>}</div>
    {view&&resource?<><div className="foundation-viewbar"><Badge appearance="outline">{kindLabels[resource.kind]}</Badge><TabList size="small" selectedValue={view.mode} onTabSelect={(_,d)=>{if(!busy)update(c=>patchView(c,view.id,{mode:d.value as ViewInstance['mode']}))}}><Tab value="visual">View</Tab><Tab value="spec">Resource JSON</Tab></TabList><small title={resource.id}>Revision {resource.revision}</small><input aria-label="Canonical resource title" value={resource.title} maxLength={160} disabled={busy} onChange={e=>{const title=e.target.value;if(title.trim())update(c=>replaceResource(c,{...resource,title}))}}/><Button size="small" disabled={busy} onClick={()=>{if(window.confirm("Remove this design/reference and its views? Underlying notebooks, tables and runs are not deleted."))update(c=>removeResource(c,resource.id))}}>Remove resource</Button></div><div role="tabpanel" id={`panel-${pane.id}`} aria-labelledby={`tab-${view.id}`} className="foundation-pane-content">{renderResource(resource,view)}</div></>:<p className="foundation-empty">Choose a resource to open it in this pane. Closing a tab never deletes its source.</p>}
   </section></Fragment>})}
  </div>{ui.context_open&&<aside className="foundation-context" aria-label="Resource context"><h3>Context</h3><p>One canonical resource; panes only hold references.</p>{(()=>{const v=state.views.find(v=>v.id===state.panes.find(p=>p.id===state.active_pane_id)?.active_view_id),r=v&&resources.get(v.resource_id);return r?<dl><dt>Resource</dt><dd>{r.title}</dd><dt>Identity</dt><dd><code>{r.id}</code></dd><dt>Revision</dt><dd>{r.revision}</dd><dt>Open views</dt><dd>{state.views.filter(v=>v.resource_id===r.id).length}</dd><dt>Execution</dt><dd>{r.kind==='notebook'?'See cell runtime truth':r.kind==='dbt-project'||r.kind==='pipeline'?'Explicit local job; see run evidence':'Design / snapshot; no implicit execution'}</dd></dl>:null})()}{state.migrations?.filter(m=>m.status==='recovery').map(m=><p role="alert" key={m.notebook_id+m.fingerprint}>{m.message}</p>)}</aside>}</div>
 {palette&&<ResourcePalette resources={state.resources} onOpen={id=>update(c=>openResource(c,id))} onCreate={kind=>add(createStudioResource(kind))} onNewNotebook={onCreateNotebook} onClose={()=>setPalette(false)}/>}
 </section>;
}

interface GraphEditorProps {resource:GraphResource;view:ViewInstance;resources:Resource[];assets:Asset[];capabilities:Capabilities|null;disabled:boolean;onView:(patch:Partial<ViewInstance>)=>void;onResource:(resource:GraphResource)=>void;onError:(error:string)=>void}
function GraphEditor({resource,view,resources,assets,capabilities,disabled,onView,onResource,onError}:GraphEditorProps){
 const graph=useMemo(()=>projectGraph(resource),[resource]);
 const [from,setFrom]=useState(''),[to,setTo]=useState('');
 const safe=(action:()=>void)=>{try{action()}catch(e){onError(String(e instanceof Error?e.message:e))}};
 const selected=graph.nodes.find(n=>n.id===view.selected_node);
 const edge=graph.edges.find(e=>e.id===view.selected_edge);
 const bind=(value:string|null,onChange:(name:string|null)=>void)=><Field label="Shared catalog binding"><Select value={value??''} onChange={(_,d)=>onChange(d.value||null)}><option value="">Unbound design</option>{value&&!assets.some(a=>a.name===value)&&<option value={value}>{value} (not in current catalog)</option>}{assets.map(a=><option value={a.name} key={a.name}>{a.name}{a.fresh?'':' (stale)'}</option>)}</Select><small>Reference only; does not copy data or create a table.</small></Field>;
 function nodeProperties(){
  if(!selected)return <p>Select a node to edit its domain properties.</p>;
  if(resource.kind==='workflow'){
   const task=resource.tasks.find(n=>n.id===selected.id)!;
   const patch=(values:Partial<typeof task>)=>onResource({...resource,tasks:resource.tasks.map(t=>t.id===task.id?{...t,...values}:t)});
   return <><Field label="Task label"><Input value={task.label} maxLength={160} onChange={(_,d)=>patch({label:d.value})}/></Field><Field label="Target runtime"><Select value={task.runtime} onChange={(_,d)=>patch({runtime:d.value as typeof task.runtime})}>{runtimeTargets(capabilities).map(r=><option key={r.id} value={r.id}>{r.label}{r.available?'':' / unavailable'}</option>)}</Select><small>{runtimeTargets(capabilities).find(r=>r.id===task.runtime)?.reason}</small></Field><Field label="Notebook reference"><Select value={task.notebook_resource_id??''} onChange={(_,d)=>patch({notebook_resource_id:d.value||null})}><option value="">No notebook linked</option>{resources.filter(r=>r.kind==='notebook').map(r=><option value={r.id} key={r.id}>{r.title}</option>)}</Select></Field><p>Dependency edges describe intended order. This design does not schedule or run its notebook references.</p></>;
  }
  if(resource.kind==='lineage'){
   const node=resource.datasets.find(n=>n.id===selected.id)!;
   const patch=(values:Partial<typeof node>)=>onResource({...resource,datasets:resource.datasets.map(n=>n.id===node.id?{...n,...values}:n)});
   return <><Field label="Dataset label"><Input value={node.label} maxLength={160} onChange={(_,d)=>patch({label:d.value})}/></Field>{bind(node.asset_ref,asset_ref=>patch({asset_ref}))}<p>Authored table-level derivation, not automatically observed column lineage. Use distinct nodes for versioned inputs and outputs.</p></>;
  }
  const table=resource.tables.find(n=>n.id===selected.id)!;
  const patch=(values:Partial<typeof table>)=>onResource({...resource,tables:resource.tables.map(t=>t.id===table.id?{...t,...values}:t)});
  return <><Field label="Table label"><Input value={table.label} maxLength={160} onChange={(_,d)=>patch({label:d.value})}/></Field>{bind(table.asset_ref,asset_ref=>patch({asset_ref}))}<Field label="Grain"><Textarea value={table.grain} maxLength={2000} onChange={(_,d)=>patch({grain:d.value})}/></Field><Field label="Table role"><Select value={table.role} onChange={(_,d)=>patch({role:d.value as typeof table.role})}><option value="table">Table</option><option value="fact">Fact</option><option value="dimension">Dimension</option></Select></Field><Field label="SCD intent"><Select value={table.scd} onChange={(_,d)=>patch({scd:Number(d.value) as typeof table.scd})}>{[0,1,2,3].map(v=><option value={v} key={v}>{v===0?'Not modeled':`Type ${v}`}</option>)}</Select><small>Metadata only; no SCD transformation is executed.</small></Field><details open><summary>Columns ({table.columns.length})</summary>{table.columns.map(c=><div className="foundation-column" key={c.id}><code>{c.id}</code><Input aria-label={`Type of ${c.id}`} value={c.data_type} maxLength={160} onChange={(_,d)=>patch({columns:table.columns.map(col=>col.id===c.id?{...col,data_type:d.value}:col)})}/><Select aria-label={`Key role of ${c.id}`} value={c.key} onChange={(_,d)=>patch({columns:table.columns.map(col=>col.id===c.id?{...col,key:d.value as typeof c.key}:col)})}><option value="none">No key</option><option value="primary">Primary</option><option value="foreign">Foreign</option></Select><Button size="small" onClick={()=>patch({columns:table.columns.filter(col=>col.id!==c.id)})}>Remove column</Button></div>)}<Button onClick={()=>patch({columns:[...table.columns,{id:newId('column'),data_type:'VARCHAR',key:'none',nullable:true}]})}>Add column</Button></details></>;
 }
 function edgeProperties(){
  if(!edge)return null;
  if(resource.kind==='workflow'){const value=resource.dependencies.find(e=>e.id===edge.id)!;return <Field label="Dependency condition"><Select value={value.condition} onChange={(_,d)=>onResource({...resource,dependencies:resource.dependencies.map(e=>e.id===edge.id?{...e,condition:d.value as typeof value.condition}:e)})}><option value="success">After success</option><option value="completion">After completion</option></Select></Field>}
  if(resource.kind==='lineage'){const value=resource.derivations.find(e=>e.id===edge.id)!;return <Field label="Derivation explanation"><Textarea value={value.note} maxLength={2000} onChange={(_,d)=>onResource({...resource,derivations:resource.derivations.map(e=>e.id===edge.id?{...e,note:d.value}:e)})}/></Field>}
  const rel=resource.relationships.find(e=>e.id===edge.id)!;
  const patch=(values:Partial<typeof rel>)=>onResource({...resource,relationships:resource.relationships.map(e=>e.id===edge.id?{...e,...values}:e)});
  return <><Field label="Relationship cardinality"><Select value={rel.cardinality} onChange={(_,d)=>patch({cardinality:d.value as typeof rel.cardinality})}>{['one-to-many','many-to-one','one-to-one','many-to-many'].map(c=><option key={c} value={c}>{c}</option>)}</Select></Field>{(['source','target'] as const).map(side=><Field key={side} label={`${side} column`}><Select value={rel[`${side}_column`]} onChange={(_,d)=>patch({[`${side}_column`]:d.value})}>{(resource as DataModelResource).tables.find(t=>t.id===rel[side])!.columns.map(c=><option key={c.id} value={c.id}>{c.id}</option>)}</Select></Field>)}<p>Cardinality is declared, not verified against table rows. Relationship cycles are allowed; workflow cycles are not.</p></>;
 }
 return <div className="foundation-graph-editor"><fieldset disabled={disabled} className="foundation-graph-toolbar"><Button size="small" icon={<Add24Regular/>} onClick={()=>safe(()=>onResource(addGraphNode(resource)))}>Add {resource.kind==='workflow'?'task':resource.kind==='lineage'?'dataset':'table'}</Button><Button size="small" disabled={!selected&&!edge} onClick={()=>safe(()=>onResource(deleteGraphItems(resource,selected?[selected.id]:[],edge?[edge.id]:[])))}>Delete selected</Button><Button size="small" onClick={()=>onView({positions:{}})}>Reset positions</Button><Select size="small" aria-label="Connect source node" value={from} onChange={(_,d)=>setFrom(d.value)}><option value="">Source node</option>{graph.nodes.map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</Select><Select size="small" aria-label="Connect target node" value={to} onChange={(_,d)=>setTo(d.value)}><option value="">Target node</option>{graph.nodes.map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</Select><Button size="small" disabled={!graph.nodes.some(n=>n.id===from)||!graph.nodes.some(n=>n.id===to)} onClick={()=>safe(()=>onResource(connectGraph(resource,from,to)))}>Connect</Button></fieldset>
  <GraphCanvas graph={graph} view={view} disabled={disabled} onView={onView} onConnect={(source,target)=>safe(()=>onResource(connectGraph(resource,source,target)))}/>
  <details className="foundation-inspector" open><summary>Properties / {resource.kind}</summary><fieldset disabled={disabled}><Field label="Resource title"><Input value={resource.title} maxLength={160} onChange={(_,d)=>onResource({...resource,title:d.value})}/></Field><Field label="Selected node"><Select value={view.selected_node??''} onChange={(_,d)=>onView({selected_node:d.value||null,selected_edge:null})}><option value="">Choose a node</option>{graph.nodes.map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</Select></Field>{edge?edgeProperties():nodeProperties()}</fieldset></details>
 </div>;
}
