import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { readFileSync, readdirSync } from 'node:fs';
import { resolve } from 'node:path';
const root=resolve(import.meta.dirname,'..');
execFileSync(process.platform==='win32'?'tsc.cmd':'tsc',['-p','tsconfig.build.json'],{cwd:root,stdio:'inherit'});
const stamp=Date.now();
const { caseStudies }=await import(`${resolve(root,'.compiled/data/caseStudies.js')}?audit=${stamp}`);
const { validateCaseStudy }=await import(`${resolve(root,'.compiled/lib/validation.js')}?audit=${stamp}`);
for(const study of caseStudies) assert.deepEqual(validateCaseStudy(study),[],`${study.id}: ${validateCaseStudy(study).join(' | ')}`);

const app=readFileSync(resolve(root,'src/App.tsx'),'utf8');
for(const label of ['Airflow Lab','dbt Lab','Hybrid Project','Concept library','Reset run/UI state'])assert.ok(app.includes(label),`UI control missing: ${label}`);
const airflow=readFileSync(resolve(root,'src/pages/AirflowLab.tsx'),'utf8');
for(const label of ['Reset run','Step','Run simulation','Overview','Graph','Grid','Schedule','Code','Logs','Sample data','Restore example'])assert.ok(airflow.includes(label)||readFileSync(resolve(root,'src/components/CodeEditor.tsx'),'utf8').includes(label),`Airflow control missing: ${label}`);
const dbt=readFileSync(resolve(root,'src/pages/DbtLab.tsx'),'utf8');
for(const label of ['Reset command','Run {command} (simulated)','Lineage','Compiled SQL','Command','Tests & contracts','Snapshots','Docs','File / model','current + parents','current + children'])assert.ok(dbt.includes(label),`dbt control missing: ${label}`);
const hybrid=readFileSync(resolve(root,'src/pages/HybridLab.tsx'),'utf8');
for(const label of ['Cross-link map','Airflow DAG','dbt lineage','Execution','Run hybrid simulation'])assert.ok(hybrid.includes(label),`Hybrid control missing: ${label}`);
assert.ok(hybrid.includes('dbt run scopes + tests')&&!hybrid.includes('dbt build + tests'),'Hybrid execution copy must reflect separate simulated run/test phases rather than claiming dbt build');

function tsxFiles(dir){ return readdirSync(dir,{withFileTypes:true}).flatMap((entry)=>entry.isDirectory()?tsxFiles(resolve(dir,entry.name)):(entry.name.endsWith('.tsx')?[resolve(dir,entry.name)]:[])); }
for (const absolute of tsxFiles(resolve(root,'src'))) {
  const file=absolute.slice(root.length+1).replaceAll('\\','/');
  const source=readFileSync(absolute,'utf8');
  for (const match of source.matchAll(/<Button\b([\s\S]*?)>/g)) assert.ok(/onClick=|disabled=/.test(match[1]),`${file}: Fluent Button without click/disabled behavior`);
  for (const match of source.matchAll(/<button\b([\s\S]*?)>/g)) assert.ok(/onClick=|disabled=/.test(match[1]),`${file}: native button without click/disabled behavior`);
  for (const match of source.matchAll(/<select\b([\s\S]*?)>/g)) assert.ok(/onChange=/.test(match[1]),`${file}: select without onChange`);
}
assert.ok(app.includes('saveString(storageKeys.theme'),'Theme persistence wiring missing');
assert.ok(app.includes('saveJson(storageKeys.caseByLab'),'Case selection persistence wiring missing');
assert.ok(app.includes('loadCaseSelection')&&app.includes('validCaseIds'),'Persisted case selection must be schema/ID validated before use');
assert.ok(airflow.includes('[study.id,resetToken]'),'Airflow case switch reset effect missing');
assert.ok(dbt.includes('[study.id,resetToken]'),'dbt case switch reset effect missing');
assert.ok(hybrid.includes('[study.id,resetToken]'),'Hybrid case switch reset effect missing');
assert.ok(airflow.includes('changeScenario')&&airflow.includes('createAirflowRun'),'Airflow scenario changes must reset execution state');
assert.ok(dbt.includes('changeScenario')&&dbt.includes('createDbtBuild'),'dbt scenario changes must reset stale build state');
assert.ok(hybrid.includes('changeScenario')&&hybrid.includes('resetHybrid'),'Hybrid scenario changes must reset stale execution state');
assert.ok(dbt.includes("setSelectedModelId(model?.id??'')"),'Selecting a non-model dbt file must clear stale model selection');
assert.ok(dbt.includes('modelSqlOverrides'),'dbt command simulation must consume locally edited model SQL');
assert.ok(dbt.includes('selectedCommandModels.length===0'),'model-scoped dbt commands must disable rather than silently broaden when no model is selected');
assert.ok(dbt.includes("subLabel:'seed'"),'dbt lineage must render seed resources as first-class nodes');
assert.ok(dbt.includes('contractStates')&&dbt.includes('snapshotStates'),'dbt UI must surface contract preflight and snapshot resource states');
assert.ok(dbt.includes('includeProjectResources')&&dbt.includes("selectionMode==='all'"),'project-wide dbt build must explicitly opt into seed/snapshot resources');
assert.ok(dbt.includes('simulateSnapshot')&&dbt.includes('snapshotYaml'),'Snapshots tab must be backed by the bounded SCD2 simulator and current YAML lesson output');
assert.ok(dbt.includes('snapshotDependencyId')&&dbt.includes("subLabel:`snapshot · ${snapshot.strategy}`"),'dbt lineage must render snapshots as first-class dependency nodes');
const dbtTypes=readFileSync(resolve(root,'src/types.ts'),'utf8');
const caseStudySource=readFileSync(resolve(root,'src/data/caseStudies.ts'),'utf8');
const caseOverview=readFileSync(resolve(root,'src/components/CaseOverview.tsx'),'utf8');
assert.ok(!/DbtTestDefinition[\s\S]{0,700}'contract'/.test(dbtTypes),'model contracts must not be encoded as dbt data-test types');
assert.ok(!/type:\s*'contract'/.test(caseStudySource),'case studies must not represent model contracts as ordinary dbt tests');
assert.ok(dbtTypes.includes('MockProjectBrief')&&dbtTypes.includes('MockProjectCheckpoint'),'guided mock-project metadata types are missing');
assert.ok(caseStudySource.includes("id:'mock_marketplace'")&&caseStudySource.includes('mockProject:{'),'guided mock case-study source is missing');
assert.ok(caseOverview.includes('Start from the requirements')&&caseOverview.includes('Reference answer')&&caseOverview.includes('Acceptance checks'),'mock project overview must expose requirements-first practice and collapsible checkpoint guidance');
assert.ok(caseOverview.includes('Reveal after you make your own plan')&&caseOverview.includes('Reference architecture rationale'),'mock case must keep the reference architecture rationale collapsed until deliberately revealed');
assert.ok(caseOverview.includes('Your design note')&&caseOverview.includes('mockAnswersKey')&&caseOverview.includes('Clear practice state'),'mock project must provide locally persisted learner design drafts with an explicit reset control');
assert.ok(caseOverview.includes('mockReviewKey')&&caseOverview.includes('self-review')&&caseOverview.includes('Browser storage is unavailable'),'mock project must expose manual self-review without pretending automatic grading and must disclose blocked browser persistence');
assert.ok(dbt.includes("path.includes('sla_targets')"),'mock dbt seed must expose concrete SLA target sample data rather than a generic placeholder');
const snapshotSimulator=readFileSync(resolve(root,'src/lib/snapshotSimulator.ts'),'utf8');
assert.ok(snapshotSimulator.includes('dbt_valid_from')&&snapshotSimulator.includes('dbt_valid_to')&&snapshotSimulator.includes('simulateSnapshot'),'snapshot simulator must expose bounded SCD2 validity history');
assert.ok(snapshotSimulator.includes('strategy: ${snapshot.strategy}')&&snapshotSimulator.includes('check_cols'),'snapshot YAML lesson must support timestamp/check configuration paths');
const dbtSimulator=readFileSync(resolve(root,'src/lib/dbtSimulator.ts'),'utf8');
assert.ok(dbtSimulator.includes("command==='test'")&&dbtSimulator.includes("command==='build'")&&dbtSimulator.includes('selectDbtModels'),'dbt run/test/build command semantics or selectors missing');
assert.ok(dbtSimulator.includes('runEligibleProjectSnapshots')&&dbtSimulator.includes('referenced model'),'project-wide snapshots must honor source/seed/model dependency readiness instead of being auto-successful');
const airflowSimulator=readFileSync(resolve(root,'src/lib/airflowSimulator.ts'),'utf8');
assert.ok(airflowSimulator.includes('simulationStepBudget')&&!airflowSimulator.includes('i<100 && state.status'),'Airflow run-to-end guard must scale with scenario work instead of using the old hard-coded 100-step cap');
const schedulePanel=readFileSync(resolve(root,'src/components/SchedulePanel.tsx'),'utf8');
const scheduleSimulator=readFileSync(resolve(root,'src/lib/scheduleSimulator.ts'),'utf8');
assert.ok(schedulePanel.includes('previewDataIntervals')&&scheduleSimulator.includes('parseBoundedCron'),'Schedule page must use bounded cron interval logic, not a display heuristic');
assert.ok(scheduleSimulator.includes('value>7')&&scheduleSimulator.includes('end>7'),'Bounded cron parser must reject invalid weekday values rather than wrapping them modulo seven');
const graphCanvas=readFileSync(resolve(root,'src/components/GraphCanvas.tsx'),'utf8');
assert.ok(graphCanvas.includes('groupBoxes')&&graphCanvas.includes('graph-group'),'DAG graph must render task-group boundaries');
assert.ok(graphCanvas.includes('aria-label')&&graphCanvas.includes('aria-pressed')&&graphCanvas.includes("event.key===' '"),'Graph nodes must expose keyboard-accessible button semantics');
assert.ok(graphCanvas.includes('selectable?: boolean')&&graphCanvas.includes("role={selectable?'button':undefined}"),'Graph canvas must support non-interactive resource nodes without exposing dead button semantics');
assert.ok(graphCanvas.includes('useId')&&graphCanvas.includes('graph-arrow-'),'Each graph SVG must use a unique marker ID so multiple graph canvases cannot collide in one document');
assert.ok(dbt.includes("setTab('data')")&&dbt.includes("setSelectedPath(`seeds/${seed}`)"),'dbt lineage sources/seeds must navigate to useful sample-data/file surfaces');
assert.ok(hybrid.includes('selectable:false'),'Hybrid non-model dbt resources must not masquerade as clickable inspector controls');
assert.ok(hybrid.includes('runPhaseStatus')&&hybrid.includes('testPhaseStatus')&&hybrid.includes('run scope:'),'Hybrid UI must distinguish the Airflow-triggered dbt run phase from the later test gate.');
const explorer=readFileSync(resolve(root,'src/components/Explorer.tsx'),'utf8');
assert.ok(explorer.includes('role="treeitem"')&&explorer.includes('aria-selected'),'Project explorer must expose tree-item selection semantics');
assert.ok(app.includes("event.key==='Escape'"),'Concept dialog must close with Escape');
const styles=readFileSync(resolve(root,'src/styles.css'),'utf8');
assert.ok(styles.includes('.state-upstream_failed'),'upstream_failed must have a distinct visual state');
assert.ok(styles.includes('.mock-project-card')&&styles.includes('.mock-checkpoint'),'mock project practice surface styling missing');
assert.ok(styles.includes('.mock-answer')&&styles.includes('.mock-progress'),'mock learner-draft/progress styling missing');
const concepts=readFileSync(resolve(root,'src/data/concepts.ts'),'utf8');
assert.ok(concepts.includes('upstream_failed')&&concepts.includes('leaf tasks'),'Airflow teaching copy must explain upstream_failed and leaf-state DagRun caveat');
const dataPreview=readFileSync(resolve(root,'src/components/DataPreview.tsx'),'utf8');
assert.ok(dataPreview.includes('useEffect'),'Dataset preview must reset invalid selection when case-study datasets change');
const inspector=readFileSync(resolve(root,'src/components/Inspector.tsx'),'utf8');
assert.ok(inspector.includes('Logical start')&&inspector.includes('Logical finish'),'Airflow inspector must expose logical task timing');
assert.ok(inspector.includes('Run by Airflow')&&inspector.includes('Test gate'),'dbt inspector must distinguish model execution ownership from test-gate orchestration');
assert.ok(dbt.includes('study.airflow.dagId')&&hybrid.includes('study.airflow.dagId'),'dbt-to-Airflow cross-links must identify the DAG and task, not only a bare task name');
const editor=readFileSync(resolve(root,'src/components/CodeEditor.tsx'),'utf8');
assert.ok(editor.includes('Restore example')&&editor.includes('edited locally'),'Editor restore/dirty-state controls missing');
assert.ok(airflow.includes('Browser storage unavailable')&&dbt.includes('Browser storage unavailable'),'Code editors must not claim persistence when browser storage writes fail');
console.log(`PASS consistency/dead-control/state-reset/edit-propagation audit across ${caseStudies.length} case studies`);
